import type { LucideIcon } from "lucide-react";
import {
  AlignLeft,
  AppWindow,
  Box,
  ChevronDown,
  Code,
  Columns2,
  Columns3,
  Copyright,
  CreditCard,
  Database,
  FileInput,
  FlaskConical,
  GalleryHorizontal,
  GalleryHorizontalEnd,
  Group,
  Hash,
  Heading,
  Heading1,
  History,
  Image,
  Images,
  LayoutGrid,
  LayoutTemplate,
  Link,
  Link2,
  ListChecks,
  ListOrdered,
  MapPin,
  Menu,
  MessageSquare,
  Minus,
  MousePointerClick,
  Newspaper,
  PanelBottom,
  PanelTop,
  Repeat,
  Rocket,
  Rows3,
  Search,
  Share2,
  Sparkles,
  Square,
  SquareStack,
  StretchVertical,
  Table2,
  Users,
  Video,
  Blocks,
} from "lucide-react";

/** Lucide icon per palette block — quick visual scan in the block library. */
export const BLOCK_ICONS: Record<string, LucideIcon> = {
  Section: LayoutTemplate,
  Container: Square,
  Row: Columns2,
  Column: Rows3,
  Grid: LayoutGrid,
  Slider: GalleryHorizontalEnd,
  Card: CreditCard,
  Group: Group,
  Spacer: StretchVertical,
  Div: Box,
  Divider: Minus,
  Tabs: AppWindow,
  Accordion: ChevronDown,
  Heading: Heading,
  Paragraph: AlignLeft,
  "Section Heading": Heading1,
  Button: MousePointerClick,
  Link: Link,
  Badge: Hash,
  Image: Image,
  Icon: Sparkles,
  Embed: Code,
  Navbar: Menu,
  NavMenu: Menu,
  "Nav Link": Link2,
  "Nav Dropdown": ChevronDown,
  "Nav Mega": LayoutGrid,
  Topbar: PanelTop,
  Video: Video,
  Gallery: Images,
  Map: MapPin,
  "Logo Carousel": GalleryHorizontal,
  "Content Carousel": Images,
  "Video Testimonial Carousel": MessageSquare,
  "Article Card Grid": Newspaper,
  "Hero Section": Rocket,
  "Feature List": ListChecks,
  "Counter Section": Hash,
  "Step Cards": ListOrdered,
  "Pricing Table": Table2,
  "Team Grid": Users,
  Timeline: History,
  Modal: SquareStack,
  Countdown: History,
  "Progress Bar": ListOrdered,
  "Rich Text": FileInput,
  "Comparison Table": Table2,
  "Before / After": Images,
  "Masonry Gallery": LayoutGrid,
  "Code Block": Code,
  Table: Table2,
  Newsletter: FileInput,
  "Cookie Banner": PanelBottom,
  "Floating CTA": MousePointerClick,
  Lottie: Sparkles,
  Calendar: History,
  "Event Timeline": History,
  "Stepper Form": ListOrdered,
  "Design Frame": Square,
  "Pricing Calculator": CreditCard,
  "Social Feed": Share2,
  Form: FileInput,
  Search: Search,
  "Collection List": Database,
  Repeater: Repeat,
  Experiment: FlaskConical,
  Footer: PanelBottom,
  "Footer Columns": Columns3,
  "Footer Links": Link2,
  "Social Icons": Share2,
  "Copyright Block": Copyright,
};

export const iconFor = (name: string): LucideIcon => BLOCK_ICONS[name] ?? Blocks;
