FROM oven/bun:1 AS builder
WORKDIR /app
COPY . .
RUN bun install
RUN bun --cwd apps/admin run build

FROM nginx:alpine
COPY --from=builder /app/apps/admin/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
