FROM oven/bun:1 AS builder
WORKDIR /app
COPY . .
RUN bun install
RUN bun --cwd apps/renderer run build

FROM node:20-alpine
WORKDIR /app
RUN npm install -g bun
COPY --from=builder /app /app
WORKDIR /app/apps/renderer
EXPOSE 3000
CMD ["bun", "run", "start"]
