FROM oven/bun:1 AS builder
WORKDIR /app
COPY . .
RUN bun install
RUN bunx turbo run build --filter=@ob-cms/api

FROM node:20-alpine
WORKDIR /app
RUN npm install -g bun
COPY --from=builder /app /app
WORKDIR /app/apps/api
EXPOSE 3001
CMD ["bun", "run", "start:prod"]
