FROM oven/bun:1 AS builder
WORKDIR /app
COPY . .
RUN bun install
RUN bunx turbo run build --filter=@ob-cms/worker

FROM oven/bun:1-alpine
WORKDIR /app
COPY --from=builder /app /app
WORKDIR /app/apps/worker
CMD ["bun", "run", "start"]
