/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateApiKeyDto
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const apiKeysControllerList = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/api-keys`, method: 'GET', signal
    },
      );
    }




export const getApiKeysControllerListQueryKey = () => {
    return [
    `/api/v1/api-keys`
    ] as const;
    }


export const getApiKeysControllerListQueryOptions = <TData = Awaited<ReturnType<typeof apiKeysControllerList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiKeysControllerList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiKeysControllerListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiKeysControllerList>>> = ({ signal }) => apiKeysControllerList(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiKeysControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiKeysControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof apiKeysControllerList>>>
export type ApiKeysControllerListQueryError = unknown


export function useApiKeysControllerList<TData = Awaited<ReturnType<typeof apiKeysControllerList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiKeysControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiKeysControllerList>>,
          TError,
          Awaited<ReturnType<typeof apiKeysControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiKeysControllerList<TData = Awaited<ReturnType<typeof apiKeysControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiKeysControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiKeysControllerList>>,
          TError,
          Awaited<ReturnType<typeof apiKeysControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiKeysControllerList<TData = Awaited<ReturnType<typeof apiKeysControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiKeysControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiKeysControllerList<TData = Awaited<ReturnType<typeof apiKeysControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiKeysControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiKeysControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const apiKeysControllerCreate = (
    createApiKeyDto: CreateApiKeyDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/api-keys`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createApiKeyDto, signal
    },
      );
    }




export const getApiKeysControllerCreateMutationKey = () => ['apiKeysControllerCreate'] as const;

export const getApiKeysControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiKeysControllerCreate>>, TError,ApiKeysControllerCreateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof apiKeysControllerCreate>>, TError,ApiKeysControllerCreateMutationVariables, TContext> => {

const mutationKey = getApiKeysControllerCreateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiKeysControllerCreate>>, ApiKeysControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  apiKeysControllerCreate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ApiKeysControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof apiKeysControllerCreate>>>
    export type ApiKeysControllerCreateMutationBody = CreateApiKeyDto
    export type ApiKeysControllerCreateMutationError = unknown
    export type ApiKeysControllerCreateMutationVariables = {data: CreateApiKeyDto}

    export const useApiKeysControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiKeysControllerCreate>>, TError,ApiKeysControllerCreateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof apiKeysControllerCreate>>,
        TError,
        ApiKeysControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getApiKeysControllerCreateMutationOptions(options), queryClient);
    }
    export const apiKeysControllerRevoke = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/api-keys/${id}`, method: 'DELETE', signal
    },
      );
    }




export const getApiKeysControllerRevokeMutationKey = () => ['apiKeysControllerRevoke'] as const;

export const getApiKeysControllerRevokeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiKeysControllerRevoke>>, TError,ApiKeysControllerRevokeMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof apiKeysControllerRevoke>>, TError,ApiKeysControllerRevokeMutationVariables, TContext> => {

const mutationKey = getApiKeysControllerRevokeMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiKeysControllerRevoke>>, ApiKeysControllerRevokeMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  apiKeysControllerRevoke(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ApiKeysControllerRevokeMutationResult = NonNullable<Awaited<ReturnType<typeof apiKeysControllerRevoke>>>

    export type ApiKeysControllerRevokeMutationError = unknown
    export type ApiKeysControllerRevokeMutationVariables = {id: string}

    export const useApiKeysControllerRevoke = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiKeysControllerRevoke>>, TError,ApiKeysControllerRevokeMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof apiKeysControllerRevoke>>,
        TError,
        ApiKeysControllerRevokeMutationVariables,
        TContext
      > => {
      return useMutation(getApiKeysControllerRevokeMutationOptions(options), queryClient);
    }
