/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List this site's audit events (scoped, append-only)
 */
export const auditControllerList = (
    siteId: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/sites/${siteId}/audit`, method: 'GET', signal
    },
      );
    }




export const getAuditControllerListQueryKey = (siteId: string,) => {
    return [
    `/api/v1/sites/${siteId}/audit`
    ] as const;
    }


export const getAuditControllerListQueryOptions = <TData = Awaited<ReturnType<typeof auditControllerList>>, TError = unknown>(siteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditControllerList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuditControllerListQueryKey(siteId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof auditControllerList>>> = ({ signal }) => auditControllerList(siteId, signal);





   return  { queryKey, queryFn, enabled: siteId !== null && siteId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof auditControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuditControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof auditControllerList>>>
export type AuditControllerListQueryError = unknown


export function useAuditControllerList<TData = Awaited<ReturnType<typeof auditControllerList>>, TError = unknown>(
 siteId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof auditControllerList>>,
          TError,
          Awaited<ReturnType<typeof auditControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuditControllerList<TData = Awaited<ReturnType<typeof auditControllerList>>, TError = unknown>(
 siteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof auditControllerList>>,
          TError,
          Awaited<ReturnType<typeof auditControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuditControllerList<TData = Awaited<ReturnType<typeof auditControllerList>>, TError = unknown>(
 siteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List this site's audit events (scoped, append-only)
 */

export function useAuditControllerList<TData = Awaited<ReturnType<typeof auditControllerList>>, TError = unknown>(
 siteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuditControllerListQueryOptions(siteId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
