/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DisableTotpDto,
  ForgotPasswordDto,
  LoginDto,
  RegenerateBackupCodesDto,
  ResetPasswordDto,
  SignupDto,
  TotpCodeDto
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Register a local user; sets the session + refresh cookies
 */
export const authControllerSignup = (
    signupDto: SignupDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signupDto, signal
    },
      );
    }




export const getAuthControllerSignupMutationKey = () => ['authControllerSignup'] as const;

export const getAuthControllerSignupMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerSignup>>, TError,AuthControllerSignupMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerSignup>>, TError,AuthControllerSignupMutationVariables, TContext> => {

const mutationKey = getAuthControllerSignupMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerSignup>>, AuthControllerSignupMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  authControllerSignup(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerSignupMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerSignup>>>
    export type AuthControllerSignupMutationBody = SignupDto
    export type AuthControllerSignupMutationError = unknown
    export type AuthControllerSignupMutationVariables = {data: SignupDto}

    /**
 * @summary Register a local user; sets the session + refresh cookies
 */
export const useAuthControllerSignup = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerSignup>>, TError,AuthControllerSignupMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerSignup>>,
        TError,
        AuthControllerSignupMutationVariables,
        TContext
      > => {
      return useMutation(getAuthControllerSignupMutationOptions(options), queryClient);
    }
    /**
 * @summary Log in (TOTP required if 2FA on); sets session + refresh cookies
 */
export const authControllerLogin = (
    loginDto: LoginDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginDto, signal
    },
      );
    }




export const getAuthControllerLoginMutationKey = () => ['authControllerLogin'] as const;

export const getAuthControllerLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,AuthControllerLoginMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,AuthControllerLoginMutationVariables, TContext> => {

const mutationKey = getAuthControllerLoginMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogin>>, AuthControllerLoginMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  authControllerLogin(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>
    export type AuthControllerLoginMutationBody = LoginDto
    export type AuthControllerLoginMutationError = unknown
    export type AuthControllerLoginMutationVariables = {data: LoginDto}

    /**
 * @summary Log in (TOTP required if 2FA on); sets session + refresh cookies
 */
export const useAuthControllerLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,AuthControllerLoginMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogin>>,
        TError,
        AuthControllerLoginMutationVariables,
        TContext
      > => {
      return useMutation(getAuthControllerLoginMutationOptions(options), queryClient);
    }
    /**
 * @summary Rotate refresh token; issue a fresh access cookie
 */
export const authControllerRefresh = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/auth/refresh`, method: 'POST', signal
    },
      );
    }




export const getAuthControllerRefreshMutationKey = () => ['authControllerRefresh'] as const;

export const getAuthControllerRefreshMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError,void, TContext> => {

const mutationKey = getAuthControllerRefreshMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRefresh>>, void> = () => {


          return  authControllerRefresh()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRefresh>>>

    export type AuthControllerRefreshMutationError = unknown


    /**
 * @summary Rotate refresh token; issue a fresh access cookie
 */
export const useAuthControllerRefresh = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerRefresh>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerRefreshMutationOptions(options), queryClient);
    }
    /**
 * @summary Clear both cookies + revoke the refresh token
 */
export const authControllerLogout = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/auth/logout`, method: 'POST', signal
    },
      );
    }




export const getAuthControllerLogoutMutationKey = () => ['authControllerLogout'] as const;

export const getAuthControllerLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext> => {

const mutationKey = getAuthControllerLogoutMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogout>>, void> = () => {


          return  authControllerLogout()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogout>>>

    export type AuthControllerLogoutMutationError = unknown


    /**
 * @summary Clear both cookies + revoke the refresh token
 */
export const useAuthControllerLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerLogoutMutationOptions(options), queryClient);
    }
    /**
 * @summary Current user + memberships + isPlatformAdmin + totpEnabled
 */
export const authControllerMe = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/auth/me`, method: 'GET', signal
    },
      );
    }




export const getAuthControllerMeQueryKey = () => {
    return [
    `/api/v1/auth/me`
    ] as const;
    }


export const getAuthControllerMeQueryOptions = <TData = Awaited<ReturnType<typeof authControllerMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerMe>>> = ({ signal }) => authControllerMe(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerMeQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerMe>>>
export type AuthControllerMeQueryError = unknown


export function useAuthControllerMe<TData = Awaited<ReturnType<typeof authControllerMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerMe>>,
          TError,
          Awaited<ReturnType<typeof authControllerMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerMe<TData = Awaited<ReturnType<typeof authControllerMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerMe>>,
          TError,
          Awaited<ReturnType<typeof authControllerMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerMe<TData = Awaited<ReturnType<typeof authControllerMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Current user + memberships + isPlatformAdmin + totpEnabled
 */

export function useAuthControllerMe<TData = Awaited<ReturnType<typeof authControllerMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerMe>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Generate a TOTP secret + otpauth URL (not yet enabled)
 */
export const authControllerSetup2fa = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/auth/2fa/setup`, method: 'POST', signal
    },
      );
    }




export const getAuthControllerSetup2faMutationKey = () => ['authControllerSetup2fa'] as const;

export const getAuthControllerSetup2faMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerSetup2fa>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerSetup2fa>>, TError,void, TContext> => {

const mutationKey = getAuthControllerSetup2faMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerSetup2fa>>, void> = () => {


          return  authControllerSetup2fa()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerSetup2faMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerSetup2fa>>>

    export type AuthControllerSetup2faMutationError = unknown


    /**
 * @summary Generate a TOTP secret + otpauth URL (not yet enabled)
 */
export const useAuthControllerSetup2fa = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerSetup2fa>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerSetup2fa>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerSetup2faMutationOptions(options), queryClient);
    }
    /**
 * @summary Verify a TOTP code, enable 2FA, and return backup codes (shown once)
 */
export const authControllerEnable2fa = (
    totpCodeDto: TotpCodeDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/auth/2fa/enable`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: totpCodeDto, signal
    },
      );
    }




export const getAuthControllerEnable2faMutationKey = () => ['authControllerEnable2fa'] as const;

export const getAuthControllerEnable2faMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerEnable2fa>>, TError,AuthControllerEnable2faMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerEnable2fa>>, TError,AuthControllerEnable2faMutationVariables, TContext> => {

const mutationKey = getAuthControllerEnable2faMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerEnable2fa>>, AuthControllerEnable2faMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  authControllerEnable2fa(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerEnable2faMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerEnable2fa>>>
    export type AuthControllerEnable2faMutationBody = TotpCodeDto
    export type AuthControllerEnable2faMutationError = unknown
    export type AuthControllerEnable2faMutationVariables = {data: TotpCodeDto}

    /**
 * @summary Verify a TOTP code, enable 2FA, and return backup codes (shown once)
 */
export const useAuthControllerEnable2fa = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerEnable2fa>>, TError,AuthControllerEnable2faMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerEnable2fa>>,
        TError,
        AuthControllerEnable2faMutationVariables,
        TContext
      > => {
      return useMutation(getAuthControllerEnable2faMutationOptions(options), queryClient);
    }
    /**
 * @summary Regenerate backup codes (verify code or password); shown once
 */
export const authControllerRegenerateBackupCodes = (
    regenerateBackupCodesDto: RegenerateBackupCodesDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/auth/2fa/backup-codes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: regenerateBackupCodesDto, signal
    },
      );
    }




export const getAuthControllerRegenerateBackupCodesMutationKey = () => ['authControllerRegenerateBackupCodes'] as const;

export const getAuthControllerRegenerateBackupCodesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRegenerateBackupCodes>>, TError,AuthControllerRegenerateBackupCodesMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerRegenerateBackupCodes>>, TError,AuthControllerRegenerateBackupCodesMutationVariables, TContext> => {

const mutationKey = getAuthControllerRegenerateBackupCodesMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRegenerateBackupCodes>>, AuthControllerRegenerateBackupCodesMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  authControllerRegenerateBackupCodes(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerRegenerateBackupCodesMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRegenerateBackupCodes>>>
    export type AuthControllerRegenerateBackupCodesMutationBody = RegenerateBackupCodesDto
    export type AuthControllerRegenerateBackupCodesMutationError = unknown
    export type AuthControllerRegenerateBackupCodesMutationVariables = {data: RegenerateBackupCodesDto}

    /**
 * @summary Regenerate backup codes (verify code or password); shown once
 */
export const useAuthControllerRegenerateBackupCodes = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRegenerateBackupCodes>>, TError,AuthControllerRegenerateBackupCodesMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerRegenerateBackupCodes>>,
        TError,
        AuthControllerRegenerateBackupCodesMutationVariables,
        TContext
      > => {
      return useMutation(getAuthControllerRegenerateBackupCodesMutationOptions(options), queryClient);
    }
    /**
 * @summary Disable 2FA (verify a code or the password)
 */
export const authControllerDisable2fa = (
    disableTotpDto: DisableTotpDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/auth/2fa/disable`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: disableTotpDto, signal
    },
      );
    }




export const getAuthControllerDisable2faMutationKey = () => ['authControllerDisable2fa'] as const;

export const getAuthControllerDisable2faMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerDisable2fa>>, TError,AuthControllerDisable2faMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerDisable2fa>>, TError,AuthControllerDisable2faMutationVariables, TContext> => {

const mutationKey = getAuthControllerDisable2faMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerDisable2fa>>, AuthControllerDisable2faMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  authControllerDisable2fa(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerDisable2faMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerDisable2fa>>>
    export type AuthControllerDisable2faMutationBody = DisableTotpDto
    export type AuthControllerDisable2faMutationError = unknown
    export type AuthControllerDisable2faMutationVariables = {data: DisableTotpDto}

    /**
 * @summary Disable 2FA (verify a code or the password)
 */
export const useAuthControllerDisable2fa = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerDisable2fa>>, TError,AuthControllerDisable2faMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerDisable2fa>>,
        TError,
        AuthControllerDisable2faMutationVariables,
        TContext
      > => {
      return useMutation(getAuthControllerDisable2faMutationOptions(options), queryClient);
    }
    /**
 * @summary Request a password reset (always 200, no enumeration)
 */
export const authControllerForgotPassword = (
    forgotPasswordDto: ForgotPasswordDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/auth/forgot-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: forgotPasswordDto, signal
    },
      );
    }




export const getAuthControllerForgotPasswordMutationKey = () => ['authControllerForgotPassword'] as const;

export const getAuthControllerForgotPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerForgotPassword>>, TError,AuthControllerForgotPasswordMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerForgotPassword>>, TError,AuthControllerForgotPasswordMutationVariables, TContext> => {

const mutationKey = getAuthControllerForgotPasswordMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerForgotPassword>>, AuthControllerForgotPasswordMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  authControllerForgotPassword(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerForgotPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerForgotPassword>>>
    export type AuthControllerForgotPasswordMutationBody = ForgotPasswordDto
    export type AuthControllerForgotPasswordMutationError = unknown
    export type AuthControllerForgotPasswordMutationVariables = {data: ForgotPasswordDto}

    /**
 * @summary Request a password reset (always 200, no enumeration)
 */
export const useAuthControllerForgotPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerForgotPassword>>, TError,AuthControllerForgotPasswordMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerForgotPassword>>,
        TError,
        AuthControllerForgotPasswordMutationVariables,
        TContext
      > => {
      return useMutation(getAuthControllerForgotPasswordMutationOptions(options), queryClient);
    }
    /**
 * @summary Consume a reset token and set a new password
 */
export const authControllerResetPassword = (
    resetPasswordDto: ResetPasswordDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/auth/reset-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetPasswordDto, signal
    },
      );
    }




export const getAuthControllerResetPasswordMutationKey = () => ['authControllerResetPassword'] as const;

export const getAuthControllerResetPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerResetPassword>>, TError,AuthControllerResetPasswordMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerResetPassword>>, TError,AuthControllerResetPasswordMutationVariables, TContext> => {

const mutationKey = getAuthControllerResetPasswordMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerResetPassword>>, AuthControllerResetPasswordMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  authControllerResetPassword(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerResetPassword>>>
    export type AuthControllerResetPasswordMutationBody = ResetPasswordDto
    export type AuthControllerResetPasswordMutationError = unknown
    export type AuthControllerResetPasswordMutationVariables = {data: ResetPasswordDto}

    /**
 * @summary Consume a reset token and set a new password
 */
export const useAuthControllerResetPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerResetPassword>>, TError,AuthControllerResetPasswordMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerResetPassword>>,
        TError,
        AuthControllerResetPasswordMutationVariables,
        TContext
      > => {
      return useMutation(getAuthControllerResetPasswordMutationOptions(options), queryClient);
    }
