/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApproveDto,
  BlogControllerListParams,
  BlogControllerListTermsParams,
  BulkPostsDto,
  CreatePostDto,
  CreateTranslationDto,
  RejectDto,
  SavePostLayoutDto,
  SchedulePostDto,
  SubmitReviewDto,
  TermDto,
  UpdatePostDto,
  UpdateTermDto
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const blogControllerList = (
    params?: BlogControllerListParams,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts`, method: 'GET',
        params, signal
    },
      );
    }




export const getBlogControllerListQueryKey = (params?: BlogControllerListParams,) => {
    return [
    `/api/v1/posts`, ...(params ? [params] : [])
    ] as const;
    }


export const getBlogControllerListQueryOptions = <TData = Awaited<ReturnType<typeof blogControllerList>>, TError = unknown>(params?: BlogControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBlogControllerListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof blogControllerList>>> = ({ signal }) => blogControllerList(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof blogControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BlogControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof blogControllerList>>>
export type BlogControllerListQueryError = unknown


export function useBlogControllerList<TData = Awaited<ReturnType<typeof blogControllerList>>, TError = unknown>(
 params: undefined |  BlogControllerListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof blogControllerList>>,
          TError,
          Awaited<ReturnType<typeof blogControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBlogControllerList<TData = Awaited<ReturnType<typeof blogControllerList>>, TError = unknown>(
 params?: BlogControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof blogControllerList>>,
          TError,
          Awaited<ReturnType<typeof blogControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBlogControllerList<TData = Awaited<ReturnType<typeof blogControllerList>>, TError = unknown>(
 params?: BlogControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBlogControllerList<TData = Awaited<ReturnType<typeof blogControllerList>>, TError = unknown>(
 params?: BlogControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBlogControllerListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const blogControllerCreate = (
    createPostDto: CreatePostDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPostDto, signal
    },
      );
    }




export const getBlogControllerCreateMutationKey = () => ['blogControllerCreate'] as const;

export const getBlogControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerCreate>>, TError,BlogControllerCreateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerCreate>>, TError,BlogControllerCreateMutationVariables, TContext> => {

const mutationKey = getBlogControllerCreateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerCreate>>, BlogControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  blogControllerCreate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerCreate>>>
    export type BlogControllerCreateMutationBody = CreatePostDto
    export type BlogControllerCreateMutationError = unknown
    export type BlogControllerCreateMutationVariables = {data: CreatePostDto}

    export const useBlogControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerCreate>>, TError,BlogControllerCreateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerCreate>>,
        TError,
        BlogControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary List distinct categories/tags with usage counts
 */
export const blogControllerListTerms = (
    params?: BlogControllerListTermsParams,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/terms`, method: 'GET',
        params, signal
    },
      );
    }




export const getBlogControllerListTermsQueryKey = (params?: BlogControllerListTermsParams,) => {
    return [
    `/api/v1/posts/terms`, ...(params ? [params] : [])
    ] as const;
    }


export const getBlogControllerListTermsQueryOptions = <TData = Awaited<ReturnType<typeof blogControllerListTerms>>, TError = unknown>(params?: BlogControllerListTermsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerListTerms>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBlogControllerListTermsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof blogControllerListTerms>>> = ({ signal }) => blogControllerListTerms(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof blogControllerListTerms>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BlogControllerListTermsQueryResult = NonNullable<Awaited<ReturnType<typeof blogControllerListTerms>>>
export type BlogControllerListTermsQueryError = unknown


export function useBlogControllerListTerms<TData = Awaited<ReturnType<typeof blogControllerListTerms>>, TError = unknown>(
 params: undefined |  BlogControllerListTermsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerListTerms>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof blogControllerListTerms>>,
          TError,
          Awaited<ReturnType<typeof blogControllerListTerms>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBlogControllerListTerms<TData = Awaited<ReturnType<typeof blogControllerListTerms>>, TError = unknown>(
 params?: BlogControllerListTermsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerListTerms>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof blogControllerListTerms>>,
          TError,
          Awaited<ReturnType<typeof blogControllerListTerms>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBlogControllerListTerms<TData = Awaited<ReturnType<typeof blogControllerListTerms>>, TError = unknown>(
 params?: BlogControllerListTermsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerListTerms>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List distinct categories/tags with usage counts
 */

export function useBlogControllerListTerms<TData = Awaited<ReturnType<typeof blogControllerListTerms>>, TError = unknown>(
 params?: BlogControllerListTermsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerListTerms>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBlogControllerListTermsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Create a standalone category/tag
 */
export const blogControllerCreateTerm = (
    termDto: TermDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/terms`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: termDto, signal
    },
      );
    }




export const getBlogControllerCreateTermMutationKey = () => ['blogControllerCreateTerm'] as const;

export const getBlogControllerCreateTermMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerCreateTerm>>, TError,BlogControllerCreateTermMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerCreateTerm>>, TError,BlogControllerCreateTermMutationVariables, TContext> => {

const mutationKey = getBlogControllerCreateTermMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerCreateTerm>>, BlogControllerCreateTermMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  blogControllerCreateTerm(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerCreateTermMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerCreateTerm>>>
    export type BlogControllerCreateTermMutationBody = TermDto
    export type BlogControllerCreateTermMutationError = unknown
    export type BlogControllerCreateTermMutationVariables = {data: TermDto}

    /**
 * @summary Create a standalone category/tag
 */
export const useBlogControllerCreateTerm = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerCreateTerm>>, TError,BlogControllerCreateTermMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerCreateTerm>>,
        TError,
        BlogControllerCreateTermMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerCreateTermMutationOptions(options), queryClient);
    }
    /**
 * @summary Rename a category/tag everywhere it is used
 */
export const blogControllerUpdateTerm = (
    kind: string,
    slug: string,
    updateTermDto: UpdateTermDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/terms/${kind}/${slug}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateTermDto, signal
    },
      );
    }




export const getBlogControllerUpdateTermMutationKey = () => ['blogControllerUpdateTerm'] as const;

export const getBlogControllerUpdateTermMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerUpdateTerm>>, TError,BlogControllerUpdateTermMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerUpdateTerm>>, TError,BlogControllerUpdateTermMutationVariables, TContext> => {

const mutationKey = getBlogControllerUpdateTermMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerUpdateTerm>>, BlogControllerUpdateTermMutationVariables> = (props) => {
          const {kind,slug,data} = props ?? {};

          return  blogControllerUpdateTerm(kind,slug,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerUpdateTermMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerUpdateTerm>>>
    export type BlogControllerUpdateTermMutationBody = UpdateTermDto
    export type BlogControllerUpdateTermMutationError = unknown
    export type BlogControllerUpdateTermMutationVariables = {kind: string;slug: string;data: UpdateTermDto}

    /**
 * @summary Rename a category/tag everywhere it is used
 */
export const useBlogControllerUpdateTerm = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerUpdateTerm>>, TError,BlogControllerUpdateTermMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerUpdateTerm>>,
        TError,
        BlogControllerUpdateTermMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerUpdateTermMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a category/tag from every post
 */
export const blogControllerDeleteTerm = (
    kind: string,
    slug: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/terms/${kind}/${slug}`, method: 'DELETE', signal
    },
      );
    }




export const getBlogControllerDeleteTermMutationKey = () => ['blogControllerDeleteTerm'] as const;

export const getBlogControllerDeleteTermMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerDeleteTerm>>, TError,BlogControllerDeleteTermMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerDeleteTerm>>, TError,BlogControllerDeleteTermMutationVariables, TContext> => {

const mutationKey = getBlogControllerDeleteTermMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerDeleteTerm>>, BlogControllerDeleteTermMutationVariables> = (props) => {
          const {kind,slug} = props ?? {};

          return  blogControllerDeleteTerm(kind,slug,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerDeleteTermMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerDeleteTerm>>>

    export type BlogControllerDeleteTermMutationError = unknown
    export type BlogControllerDeleteTermMutationVariables = {kind: string;slug: string}

    /**
 * @summary Delete a category/tag from every post
 */
export const useBlogControllerDeleteTerm = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerDeleteTerm>>, TError,BlogControllerDeleteTermMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerDeleteTerm>>,
        TError,
        BlogControllerDeleteTermMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerDeleteTermMutationOptions(options), queryClient);
    }
    export const blogControllerBulkPublish = (
    bulkPostsDto: BulkPostsDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/bulk/publish`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bulkPostsDto, signal
    },
      );
    }




export const getBlogControllerBulkPublishMutationKey = () => ['blogControllerBulkPublish'] as const;

export const getBlogControllerBulkPublishMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerBulkPublish>>, TError,BlogControllerBulkPublishMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerBulkPublish>>, TError,BlogControllerBulkPublishMutationVariables, TContext> => {

const mutationKey = getBlogControllerBulkPublishMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerBulkPublish>>, BlogControllerBulkPublishMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  blogControllerBulkPublish(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerBulkPublishMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerBulkPublish>>>
    export type BlogControllerBulkPublishMutationBody = BulkPostsDto
    export type BlogControllerBulkPublishMutationError = unknown
    export type BlogControllerBulkPublishMutationVariables = {data: BulkPostsDto}

    export const useBlogControllerBulkPublish = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerBulkPublish>>, TError,BlogControllerBulkPublishMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerBulkPublish>>,
        TError,
        BlogControllerBulkPublishMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerBulkPublishMutationOptions(options), queryClient);
    }
    export const blogControllerBulkTrash = (
    bulkPostsDto: BulkPostsDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/bulk/trash`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bulkPostsDto, signal
    },
      );
    }




export const getBlogControllerBulkTrashMutationKey = () => ['blogControllerBulkTrash'] as const;

export const getBlogControllerBulkTrashMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerBulkTrash>>, TError,BlogControllerBulkTrashMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerBulkTrash>>, TError,BlogControllerBulkTrashMutationVariables, TContext> => {

const mutationKey = getBlogControllerBulkTrashMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerBulkTrash>>, BlogControllerBulkTrashMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  blogControllerBulkTrash(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerBulkTrashMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerBulkTrash>>>
    export type BlogControllerBulkTrashMutationBody = BulkPostsDto
    export type BlogControllerBulkTrashMutationError = unknown
    export type BlogControllerBulkTrashMutationVariables = {data: BulkPostsDto}

    export const useBlogControllerBulkTrash = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerBulkTrash>>, TError,BlogControllerBulkTrashMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerBulkTrash>>,
        TError,
        BlogControllerBulkTrashMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerBulkTrashMutationOptions(options), queryClient);
    }
    export const blogControllerBulkRestore = (
    bulkPostsDto: BulkPostsDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/bulk/restore`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bulkPostsDto, signal
    },
      );
    }




export const getBlogControllerBulkRestoreMutationKey = () => ['blogControllerBulkRestore'] as const;

export const getBlogControllerBulkRestoreMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerBulkRestore>>, TError,BlogControllerBulkRestoreMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerBulkRestore>>, TError,BlogControllerBulkRestoreMutationVariables, TContext> => {

const mutationKey = getBlogControllerBulkRestoreMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerBulkRestore>>, BlogControllerBulkRestoreMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  blogControllerBulkRestore(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerBulkRestoreMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerBulkRestore>>>
    export type BlogControllerBulkRestoreMutationBody = BulkPostsDto
    export type BlogControllerBulkRestoreMutationError = unknown
    export type BlogControllerBulkRestoreMutationVariables = {data: BulkPostsDto}

    export const useBlogControllerBulkRestore = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerBulkRestore>>, TError,BlogControllerBulkRestoreMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerBulkRestore>>,
        TError,
        BlogControllerBulkRestoreMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerBulkRestoreMutationOptions(options), queryClient);
    }
    export const blogControllerGet = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}`, method: 'GET', signal
    },
      );
    }




export const getBlogControllerGetQueryKey = (id: string,) => {
    return [
    `/api/v1/posts/${id}`
    ] as const;
    }


export const getBlogControllerGetQueryOptions = <TData = Awaited<ReturnType<typeof blogControllerGet>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBlogControllerGetQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof blogControllerGet>>> = ({ signal }) => blogControllerGet(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof blogControllerGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BlogControllerGetQueryResult = NonNullable<Awaited<ReturnType<typeof blogControllerGet>>>
export type BlogControllerGetQueryError = unknown


export function useBlogControllerGet<TData = Awaited<ReturnType<typeof blogControllerGet>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof blogControllerGet>>,
          TError,
          Awaited<ReturnType<typeof blogControllerGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBlogControllerGet<TData = Awaited<ReturnType<typeof blogControllerGet>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof blogControllerGet>>,
          TError,
          Awaited<ReturnType<typeof blogControllerGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBlogControllerGet<TData = Awaited<ReturnType<typeof blogControllerGet>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBlogControllerGet<TData = Awaited<ReturnType<typeof blogControllerGet>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBlogControllerGetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const blogControllerUpdate = (
    id: string,
    updatePostDto: UpdatePostDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePostDto, signal
    },
      );
    }




export const getBlogControllerUpdateMutationKey = () => ['blogControllerUpdate'] as const;

export const getBlogControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerUpdate>>, TError,BlogControllerUpdateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerUpdate>>, TError,BlogControllerUpdateMutationVariables, TContext> => {

const mutationKey = getBlogControllerUpdateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerUpdate>>, BlogControllerUpdateMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  blogControllerUpdate(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerUpdate>>>
    export type BlogControllerUpdateMutationBody = UpdatePostDto
    export type BlogControllerUpdateMutationError = unknown
    export type BlogControllerUpdateMutationVariables = {id: string;data: UpdatePostDto}

    export const useBlogControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerUpdate>>, TError,BlogControllerUpdateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerUpdate>>,
        TError,
        BlogControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerUpdateMutationOptions(options), queryClient);
    }
    /**
 * @summary Move a post to trash (soft delete)
 */
export const blogControllerRemove = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}`, method: 'DELETE', signal
    },
      );
    }




export const getBlogControllerRemoveMutationKey = () => ['blogControllerRemove'] as const;

export const getBlogControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerRemove>>, TError,BlogControllerRemoveMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerRemove>>, TError,BlogControllerRemoveMutationVariables, TContext> => {

const mutationKey = getBlogControllerRemoveMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerRemove>>, BlogControllerRemoveMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  blogControllerRemove(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerRemove>>>

    export type BlogControllerRemoveMutationError = unknown
    export type BlogControllerRemoveMutationVariables = {id: string}

    /**
 * @summary Move a post to trash (soft delete)
 */
export const useBlogControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerRemove>>, TError,BlogControllerRemoveMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerRemove>>,
        TError,
        BlogControllerRemoveMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerRemoveMutationOptions(options), queryClient);
    }
    /**
 * @summary List the sibling-locale translations of a post
 */
export const blogControllerListTranslations = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}/translations`, method: 'GET', signal
    },
      );
    }




export const getBlogControllerListTranslationsQueryKey = (id: string,) => {
    return [
    `/api/v1/posts/${id}/translations`
    ] as const;
    }


export const getBlogControllerListTranslationsQueryOptions = <TData = Awaited<ReturnType<typeof blogControllerListTranslations>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerListTranslations>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBlogControllerListTranslationsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof blogControllerListTranslations>>> = ({ signal }) => blogControllerListTranslations(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof blogControllerListTranslations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BlogControllerListTranslationsQueryResult = NonNullable<Awaited<ReturnType<typeof blogControllerListTranslations>>>
export type BlogControllerListTranslationsQueryError = unknown


export function useBlogControllerListTranslations<TData = Awaited<ReturnType<typeof blogControllerListTranslations>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerListTranslations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof blogControllerListTranslations>>,
          TError,
          Awaited<ReturnType<typeof blogControllerListTranslations>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBlogControllerListTranslations<TData = Awaited<ReturnType<typeof blogControllerListTranslations>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerListTranslations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof blogControllerListTranslations>>,
          TError,
          Awaited<ReturnType<typeof blogControllerListTranslations>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBlogControllerListTranslations<TData = Awaited<ReturnType<typeof blogControllerListTranslations>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerListTranslations>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List the sibling-locale translations of a post
 */

export function useBlogControllerListTranslations<TData = Awaited<ReturnType<typeof blogControllerListTranslations>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blogControllerListTranslations>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBlogControllerListTranslationsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Create a translation of a post in another locale (clones body)
 */
export const blogControllerCreateTranslation = (
    id: string,
    createTranslationDto: CreateTranslationDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}/translations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTranslationDto, signal
    },
      );
    }




export const getBlogControllerCreateTranslationMutationKey = () => ['blogControllerCreateTranslation'] as const;

export const getBlogControllerCreateTranslationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerCreateTranslation>>, TError,BlogControllerCreateTranslationMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerCreateTranslation>>, TError,BlogControllerCreateTranslationMutationVariables, TContext> => {

const mutationKey = getBlogControllerCreateTranslationMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerCreateTranslation>>, BlogControllerCreateTranslationMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  blogControllerCreateTranslation(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerCreateTranslationMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerCreateTranslation>>>
    export type BlogControllerCreateTranslationMutationBody = CreateTranslationDto
    export type BlogControllerCreateTranslationMutationError = unknown
    export type BlogControllerCreateTranslationMutationVariables = {id: string;data: CreateTranslationDto}

    /**
 * @summary Create a translation of a post in another locale (clones body)
 */
export const useBlogControllerCreateTranslation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerCreateTranslation>>, TError,BlogControllerCreateTranslationMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerCreateTranslation>>,
        TError,
        BlogControllerCreateTranslationMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerCreateTranslationMutationOptions(options), queryClient);
    }
    /**
 * @summary Autosave the visual-builder draft layout for a post
 */
export const blogControllerSaveLayout = (
    id: string,
    savePostLayoutDto: SavePostLayoutDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}/layout`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: savePostLayoutDto, signal
    },
      );
    }




export const getBlogControllerSaveLayoutMutationKey = () => ['blogControllerSaveLayout'] as const;

export const getBlogControllerSaveLayoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerSaveLayout>>, TError,BlogControllerSaveLayoutMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerSaveLayout>>, TError,BlogControllerSaveLayoutMutationVariables, TContext> => {

const mutationKey = getBlogControllerSaveLayoutMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerSaveLayout>>, BlogControllerSaveLayoutMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  blogControllerSaveLayout(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerSaveLayoutMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerSaveLayout>>>
    export type BlogControllerSaveLayoutMutationBody = SavePostLayoutDto
    export type BlogControllerSaveLayoutMutationError = unknown
    export type BlogControllerSaveLayoutMutationVariables = {id: string;data: SavePostLayoutDto}

    /**
 * @summary Autosave the visual-builder draft layout for a post
 */
export const useBlogControllerSaveLayout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerSaveLayout>>, TError,BlogControllerSaveLayoutMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerSaveLayout>>,
        TError,
        BlogControllerSaveLayoutMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerSaveLayoutMutationOptions(options), queryClient);
    }
    export const blogControllerPublish = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}/publish`, method: 'POST', signal
    },
      );
    }




export const getBlogControllerPublishMutationKey = () => ['blogControllerPublish'] as const;

export const getBlogControllerPublishMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerPublish>>, TError,BlogControllerPublishMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerPublish>>, TError,BlogControllerPublishMutationVariables, TContext> => {

const mutationKey = getBlogControllerPublishMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerPublish>>, BlogControllerPublishMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  blogControllerPublish(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerPublishMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerPublish>>>

    export type BlogControllerPublishMutationError = unknown
    export type BlogControllerPublishMutationVariables = {id: string}

    export const useBlogControllerPublish = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerPublish>>, TError,BlogControllerPublishMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerPublish>>,
        TError,
        BlogControllerPublishMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerPublishMutationOptions(options), queryClient);
    }
    /**
 * @summary Submit a draft post for review (draft → in_review)
 */
export const blogControllerSubmitReview = (
    id: string,
    submitReviewDto: SubmitReviewDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}/submit-review`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: submitReviewDto, signal
    },
      );
    }




export const getBlogControllerSubmitReviewMutationKey = () => ['blogControllerSubmitReview'] as const;

export const getBlogControllerSubmitReviewMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerSubmitReview>>, TError,BlogControllerSubmitReviewMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerSubmitReview>>, TError,BlogControllerSubmitReviewMutationVariables, TContext> => {

const mutationKey = getBlogControllerSubmitReviewMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerSubmitReview>>, BlogControllerSubmitReviewMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  blogControllerSubmitReview(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerSubmitReviewMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerSubmitReview>>>
    export type BlogControllerSubmitReviewMutationBody = SubmitReviewDto
    export type BlogControllerSubmitReviewMutationError = unknown
    export type BlogControllerSubmitReviewMutationVariables = {id: string;data: SubmitReviewDto}

    /**
 * @summary Submit a draft post for review (draft → in_review)
 */
export const useBlogControllerSubmitReview = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerSubmitReview>>, TError,BlogControllerSubmitReviewMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerSubmitReview>>,
        TError,
        BlogControllerSubmitReviewMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerSubmitReviewMutationOptions(options), queryClient);
    }
    /**
 * @summary Approve a post in review (in_review → approved)
 */
export const blogControllerApprove = (
    id: string,
    approveDto: ApproveDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}/approve`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: approveDto, signal
    },
      );
    }




export const getBlogControllerApproveMutationKey = () => ['blogControllerApprove'] as const;

export const getBlogControllerApproveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerApprove>>, TError,BlogControllerApproveMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerApprove>>, TError,BlogControllerApproveMutationVariables, TContext> => {

const mutationKey = getBlogControllerApproveMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerApprove>>, BlogControllerApproveMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  blogControllerApprove(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerApproveMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerApprove>>>
    export type BlogControllerApproveMutationBody = ApproveDto
    export type BlogControllerApproveMutationError = unknown
    export type BlogControllerApproveMutationVariables = {id: string;data: ApproveDto}

    /**
 * @summary Approve a post in review (in_review → approved)
 */
export const useBlogControllerApprove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerApprove>>, TError,BlogControllerApproveMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerApprove>>,
        TError,
        BlogControllerApproveMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerApproveMutationOptions(options), queryClient);
    }
    /**
 * @summary Reject a post back to the author (in_review → draft)
 */
export const blogControllerReject = (
    id: string,
    rejectDto: RejectDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}/reject`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rejectDto, signal
    },
      );
    }




export const getBlogControllerRejectMutationKey = () => ['blogControllerReject'] as const;

export const getBlogControllerRejectMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerReject>>, TError,BlogControllerRejectMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerReject>>, TError,BlogControllerRejectMutationVariables, TContext> => {

const mutationKey = getBlogControllerRejectMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerReject>>, BlogControllerRejectMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  blogControllerReject(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerRejectMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerReject>>>
    export type BlogControllerRejectMutationBody = RejectDto
    export type BlogControllerRejectMutationError = unknown
    export type BlogControllerRejectMutationVariables = {id: string;data: RejectDto}

    /**
 * @summary Reject a post back to the author (in_review → draft)
 */
export const useBlogControllerReject = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerReject>>, TError,BlogControllerRejectMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerReject>>,
        TError,
        BlogControllerRejectMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerRejectMutationOptions(options), queryClient);
    }
    export const blogControllerSchedule = (
    id: string,
    schedulePostDto: SchedulePostDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}/schedule`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: schedulePostDto, signal
    },
      );
    }




export const getBlogControllerScheduleMutationKey = () => ['blogControllerSchedule'] as const;

export const getBlogControllerScheduleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerSchedule>>, TError,BlogControllerScheduleMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerSchedule>>, TError,BlogControllerScheduleMutationVariables, TContext> => {

const mutationKey = getBlogControllerScheduleMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerSchedule>>, BlogControllerScheduleMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  blogControllerSchedule(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerSchedule>>>
    export type BlogControllerScheduleMutationBody = SchedulePostDto
    export type BlogControllerScheduleMutationError = unknown
    export type BlogControllerScheduleMutationVariables = {id: string;data: SchedulePostDto}

    export const useBlogControllerSchedule = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerSchedule>>, TError,BlogControllerScheduleMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerSchedule>>,
        TError,
        BlogControllerScheduleMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerScheduleMutationOptions(options), queryClient);
    }
    /**
 * @summary Mint a shareable no-login draft preview link
 */
export const blogControllerCreatePreviewLink = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}/preview-link`, method: 'POST', signal
    },
      );
    }




export const getBlogControllerCreatePreviewLinkMutationKey = () => ['blogControllerCreatePreviewLink'] as const;

export const getBlogControllerCreatePreviewLinkMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerCreatePreviewLink>>, TError,BlogControllerCreatePreviewLinkMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerCreatePreviewLink>>, TError,BlogControllerCreatePreviewLinkMutationVariables, TContext> => {

const mutationKey = getBlogControllerCreatePreviewLinkMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerCreatePreviewLink>>, BlogControllerCreatePreviewLinkMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  blogControllerCreatePreviewLink(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerCreatePreviewLinkMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerCreatePreviewLink>>>

    export type BlogControllerCreatePreviewLinkMutationError = unknown
    export type BlogControllerCreatePreviewLinkMutationVariables = {id: string}

    /**
 * @summary Mint a shareable no-login draft preview link
 */
export const useBlogControllerCreatePreviewLink = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerCreatePreviewLink>>, TError,BlogControllerCreatePreviewLinkMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerCreatePreviewLink>>,
        TError,
        BlogControllerCreatePreviewLinkMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerCreatePreviewLinkMutationOptions(options), queryClient);
    }
    /**
 * @summary Revoke all draft preview links for a post
 */
export const blogControllerRevokePreviewLink = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}/preview-link`, method: 'DELETE', signal
    },
      );
    }




export const getBlogControllerRevokePreviewLinkMutationKey = () => ['blogControllerRevokePreviewLink'] as const;

export const getBlogControllerRevokePreviewLinkMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerRevokePreviewLink>>, TError,BlogControllerRevokePreviewLinkMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerRevokePreviewLink>>, TError,BlogControllerRevokePreviewLinkMutationVariables, TContext> => {

const mutationKey = getBlogControllerRevokePreviewLinkMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerRevokePreviewLink>>, BlogControllerRevokePreviewLinkMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  blogControllerRevokePreviewLink(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerRevokePreviewLinkMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerRevokePreviewLink>>>

    export type BlogControllerRevokePreviewLinkMutationError = unknown
    export type BlogControllerRevokePreviewLinkMutationVariables = {id: string}

    /**
 * @summary Revoke all draft preview links for a post
 */
export const useBlogControllerRevokePreviewLink = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerRevokePreviewLink>>, TError,BlogControllerRevokePreviewLinkMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerRevokePreviewLink>>,
        TError,
        BlogControllerRevokePreviewLinkMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerRevokePreviewLinkMutationOptions(options), queryClient);
    }
    /**
 * @summary Restore a trashed post
 */
export const blogControllerRestore = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}/restore`, method: 'POST', signal
    },
      );
    }




export const getBlogControllerRestoreMutationKey = () => ['blogControllerRestore'] as const;

export const getBlogControllerRestoreMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerRestore>>, TError,BlogControllerRestoreMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerRestore>>, TError,BlogControllerRestoreMutationVariables, TContext> => {

const mutationKey = getBlogControllerRestoreMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerRestore>>, BlogControllerRestoreMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  blogControllerRestore(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerRestoreMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerRestore>>>

    export type BlogControllerRestoreMutationError = unknown
    export type BlogControllerRestoreMutationVariables = {id: string}

    /**
 * @summary Restore a trashed post
 */
export const useBlogControllerRestore = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerRestore>>, TError,BlogControllerRestoreMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerRestore>>,
        TError,
        BlogControllerRestoreMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerRestoreMutationOptions(options), queryClient);
    }
    /**
 * @summary Permanently delete a trashed post
 */
export const blogControllerDestroy = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}/permanent`, method: 'DELETE', signal
    },
      );
    }




export const getBlogControllerDestroyMutationKey = () => ['blogControllerDestroy'] as const;

export const getBlogControllerDestroyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerDestroy>>, TError,BlogControllerDestroyMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blogControllerDestroy>>, TError,BlogControllerDestroyMutationVariables, TContext> => {

const mutationKey = getBlogControllerDestroyMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blogControllerDestroy>>, BlogControllerDestroyMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  blogControllerDestroy(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BlogControllerDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof blogControllerDestroy>>>

    export type BlogControllerDestroyMutationError = unknown
    export type BlogControllerDestroyMutationVariables = {id: string}

    /**
 * @summary Permanently delete a trashed post
 */
export const useBlogControllerDestroy = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blogControllerDestroy>>, TError,BlogControllerDestroyMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blogControllerDestroy>>,
        TError,
        BlogControllerDestroyMutationVariables,
        TContext
      > => {
      return useMutation(getBlogControllerDestroyMutationOptions(options), queryClient);
    }
