/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ConnectConnectorDto,
  ConnectorImportRunRequestDto,
  ConnectorsControllerImportPreviewParams
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List available connectors from the registry
 */
export const connectorsControllerList = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/connectors`, method: 'GET', signal
    },
      );
    }




export const getConnectorsControllerListQueryKey = () => {
    return [
    `/api/v1/connectors`
    ] as const;
    }


export const getConnectorsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof connectorsControllerList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConnectorsControllerListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof connectorsControllerList>>> = ({ signal }) => connectorsControllerList(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConnectorsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof connectorsControllerList>>>
export type ConnectorsControllerListQueryError = unknown


export function useConnectorsControllerList<TData = Awaited<ReturnType<typeof connectorsControllerList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectorsControllerList>>,
          TError,
          Awaited<ReturnType<typeof connectorsControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectorsControllerList<TData = Awaited<ReturnType<typeof connectorsControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectorsControllerList>>,
          TError,
          Awaited<ReturnType<typeof connectorsControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectorsControllerList<TData = Awaited<ReturnType<typeof connectorsControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List available connectors from the registry
 */

export function useConnectorsControllerList<TData = Awaited<ReturnType<typeof connectorsControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConnectorsControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary List connector import runs for the site
 */
export const connectorsControllerListImportRuns = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/connectors/import-runs`, method: 'GET', signal
    },
      );
    }




export const getConnectorsControllerListImportRunsQueryKey = () => {
    return [
    `/api/v1/connectors/import-runs`
    ] as const;
    }


export const getConnectorsControllerListImportRunsQueryOptions = <TData = Awaited<ReturnType<typeof connectorsControllerListImportRuns>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListImportRuns>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConnectorsControllerListImportRunsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof connectorsControllerListImportRuns>>> = ({ signal }) => connectorsControllerListImportRuns(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListImportRuns>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConnectorsControllerListImportRunsQueryResult = NonNullable<Awaited<ReturnType<typeof connectorsControllerListImportRuns>>>
export type ConnectorsControllerListImportRunsQueryError = unknown


export function useConnectorsControllerListImportRuns<TData = Awaited<ReturnType<typeof connectorsControllerListImportRuns>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListImportRuns>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectorsControllerListImportRuns>>,
          TError,
          Awaited<ReturnType<typeof connectorsControllerListImportRuns>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectorsControllerListImportRuns<TData = Awaited<ReturnType<typeof connectorsControllerListImportRuns>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListImportRuns>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectorsControllerListImportRuns>>,
          TError,
          Awaited<ReturnType<typeof connectorsControllerListImportRuns>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectorsControllerListImportRuns<TData = Awaited<ReturnType<typeof connectorsControllerListImportRuns>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListImportRuns>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List connector import runs for the site
 */

export function useConnectorsControllerListImportRuns<TData = Awaited<ReturnType<typeof connectorsControllerListImportRuns>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListImportRuns>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConnectorsControllerListImportRunsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Get one import run
 */
export const connectorsControllerGetImportRun = (
    runId: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/connectors/import-runs/${runId}`, method: 'GET', signal
    },
      );
    }




export const getConnectorsControllerGetImportRunQueryKey = (runId: string,) => {
    return [
    `/api/v1/connectors/import-runs/${runId}`
    ] as const;
    }


export const getConnectorsControllerGetImportRunQueryOptions = <TData = Awaited<ReturnType<typeof connectorsControllerGetImportRun>>, TError = unknown>(runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerGetImportRun>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConnectorsControllerGetImportRunQueryKey(runId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof connectorsControllerGetImportRun>>> = ({ signal }) => connectorsControllerGetImportRun(runId, signal);





   return  { queryKey, queryFn, enabled: runId !== null && runId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerGetImportRun>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConnectorsControllerGetImportRunQueryResult = NonNullable<Awaited<ReturnType<typeof connectorsControllerGetImportRun>>>
export type ConnectorsControllerGetImportRunQueryError = unknown


export function useConnectorsControllerGetImportRun<TData = Awaited<ReturnType<typeof connectorsControllerGetImportRun>>, TError = unknown>(
 runId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerGetImportRun>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectorsControllerGetImportRun>>,
          TError,
          Awaited<ReturnType<typeof connectorsControllerGetImportRun>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectorsControllerGetImportRun<TData = Awaited<ReturnType<typeof connectorsControllerGetImportRun>>, TError = unknown>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerGetImportRun>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectorsControllerGetImportRun>>,
          TError,
          Awaited<ReturnType<typeof connectorsControllerGetImportRun>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectorsControllerGetImportRun<TData = Awaited<ReturnType<typeof connectorsControllerGetImportRun>>, TError = unknown>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerGetImportRun>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get one import run
 */

export function useConnectorsControllerGetImportRun<TData = Awaited<ReturnType<typeof connectorsControllerGetImportRun>>, TError = unknown>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerGetImportRun>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConnectorsControllerGetImportRunQueryOptions(runId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary List all active connections for the site
 */
export const connectorsControllerListConnections = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/connectors/connections`, method: 'GET', signal
    },
      );
    }




export const getConnectorsControllerListConnectionsQueryKey = () => {
    return [
    `/api/v1/connectors/connections`
    ] as const;
    }


export const getConnectorsControllerListConnectionsQueryOptions = <TData = Awaited<ReturnType<typeof connectorsControllerListConnections>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListConnections>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConnectorsControllerListConnectionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof connectorsControllerListConnections>>> = ({ signal }) => connectorsControllerListConnections(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListConnections>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConnectorsControllerListConnectionsQueryResult = NonNullable<Awaited<ReturnType<typeof connectorsControllerListConnections>>>
export type ConnectorsControllerListConnectionsQueryError = unknown


export function useConnectorsControllerListConnections<TData = Awaited<ReturnType<typeof connectorsControllerListConnections>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListConnections>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectorsControllerListConnections>>,
          TError,
          Awaited<ReturnType<typeof connectorsControllerListConnections>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectorsControllerListConnections<TData = Awaited<ReturnType<typeof connectorsControllerListConnections>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListConnections>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectorsControllerListConnections>>,
          TError,
          Awaited<ReturnType<typeof connectorsControllerListConnections>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectorsControllerListConnections<TData = Awaited<ReturnType<typeof connectorsControllerListConnections>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListConnections>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all active connections for the site
 */

export function useConnectorsControllerListConnections<TData = Awaited<ReturnType<typeof connectorsControllerListConnections>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListConnections>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConnectorsControllerListConnectionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Get safe details for one connection
 */
export const connectorsControllerGetConnection = (
    connectionId: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/connectors/connections/${connectionId}`, method: 'GET', signal
    },
      );
    }




export const getConnectorsControllerGetConnectionQueryKey = (connectionId: string,) => {
    return [
    `/api/v1/connectors/connections/${connectionId}`
    ] as const;
    }


export const getConnectorsControllerGetConnectionQueryOptions = <TData = Awaited<ReturnType<typeof connectorsControllerGetConnection>>, TError = unknown>(connectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerGetConnection>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConnectorsControllerGetConnectionQueryKey(connectionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof connectorsControllerGetConnection>>> = ({ signal }) => connectorsControllerGetConnection(connectionId, signal);





   return  { queryKey, queryFn, enabled: connectionId !== null && connectionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerGetConnection>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConnectorsControllerGetConnectionQueryResult = NonNullable<Awaited<ReturnType<typeof connectorsControllerGetConnection>>>
export type ConnectorsControllerGetConnectionQueryError = unknown


export function useConnectorsControllerGetConnection<TData = Awaited<ReturnType<typeof connectorsControllerGetConnection>>, TError = unknown>(
 connectionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerGetConnection>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectorsControllerGetConnection>>,
          TError,
          Awaited<ReturnType<typeof connectorsControllerGetConnection>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectorsControllerGetConnection<TData = Awaited<ReturnType<typeof connectorsControllerGetConnection>>, TError = unknown>(
 connectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerGetConnection>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectorsControllerGetConnection>>,
          TError,
          Awaited<ReturnType<typeof connectorsControllerGetConnection>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectorsControllerGetConnection<TData = Awaited<ReturnType<typeof connectorsControllerGetConnection>>, TError = unknown>(
 connectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerGetConnection>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get safe details for one connection
 */

export function useConnectorsControllerGetConnection<TData = Awaited<ReturnType<typeof connectorsControllerGetConnection>>, TError = unknown>(
 connectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerGetConnection>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConnectorsControllerGetConnectionQueryOptions(connectionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Preview import inventory for a connected account
 */
export const connectorsControllerImportPreview = (
    connectionId: string,
    params: ConnectorsControllerImportPreviewParams,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/connectors/connections/${connectionId}/import-preview`, method: 'GET',
        params, signal
    },
      );
    }




export const getConnectorsControllerImportPreviewQueryKey = (connectionId: string,
    params?: ConnectorsControllerImportPreviewParams,) => {
    return [
    `/api/v1/connectors/connections/${connectionId}/import-preview`, ...(params ? [params] : [])
    ] as const;
    }


export const getConnectorsControllerImportPreviewQueryOptions = <TData = Awaited<ReturnType<typeof connectorsControllerImportPreview>>, TError = unknown>(connectionId: string,
    params: ConnectorsControllerImportPreviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerImportPreview>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConnectorsControllerImportPreviewQueryKey(connectionId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof connectorsControllerImportPreview>>> = ({ signal }) => connectorsControllerImportPreview(connectionId,params, signal);





   return  { queryKey, queryFn, enabled: connectionId !== null && connectionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerImportPreview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConnectorsControllerImportPreviewQueryResult = NonNullable<Awaited<ReturnType<typeof connectorsControllerImportPreview>>>
export type ConnectorsControllerImportPreviewQueryError = unknown


export function useConnectorsControllerImportPreview<TData = Awaited<ReturnType<typeof connectorsControllerImportPreview>>, TError = unknown>(
 connectionId: string,
    params: ConnectorsControllerImportPreviewParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerImportPreview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectorsControllerImportPreview>>,
          TError,
          Awaited<ReturnType<typeof connectorsControllerImportPreview>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectorsControllerImportPreview<TData = Awaited<ReturnType<typeof connectorsControllerImportPreview>>, TError = unknown>(
 connectionId: string,
    params: ConnectorsControllerImportPreviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerImportPreview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectorsControllerImportPreview>>,
          TError,
          Awaited<ReturnType<typeof connectorsControllerImportPreview>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectorsControllerImportPreview<TData = Awaited<ReturnType<typeof connectorsControllerImportPreview>>, TError = unknown>(
 connectionId: string,
    params: ConnectorsControllerImportPreviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerImportPreview>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Preview import inventory for a connected account
 */

export function useConnectorsControllerImportPreview<TData = Awaited<ReturnType<typeof connectorsControllerImportPreview>>, TError = unknown>(
 connectionId: string,
    params: ConnectorsControllerImportPreviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerImportPreview>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConnectorsControllerImportPreviewQueryOptions(connectionId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Import content from a connected account
 */
export const connectorsControllerImportRun = (
    connectionId: string,
    connectorImportRunRequestDto: ConnectorImportRunRequestDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/connectors/connections/${connectionId}/import`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: connectorImportRunRequestDto, signal
    },
      );
    }




export const getConnectorsControllerImportRunMutationKey = () => ['connectorsControllerImportRun'] as const;

export const getConnectorsControllerImportRunMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connectorsControllerImportRun>>, TError,ConnectorsControllerImportRunMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof connectorsControllerImportRun>>, TError,ConnectorsControllerImportRunMutationVariables, TContext> => {

const mutationKey = getConnectorsControllerImportRunMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof connectorsControllerImportRun>>, ConnectorsControllerImportRunMutationVariables> = (props) => {
          const {connectionId,data} = props ?? {};

          return  connectorsControllerImportRun(connectionId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ConnectorsControllerImportRunMutationResult = NonNullable<Awaited<ReturnType<typeof connectorsControllerImportRun>>>
    export type ConnectorsControllerImportRunMutationBody = ConnectorImportRunRequestDto
    export type ConnectorsControllerImportRunMutationError = unknown
    export type ConnectorsControllerImportRunMutationVariables = {connectionId: string;data: ConnectorImportRunRequestDto}

    /**
 * @summary Import content from a connected account
 */
export const useConnectorsControllerImportRun = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connectorsControllerImportRun>>, TError,ConnectorsControllerImportRunMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof connectorsControllerImportRun>>,
        TError,
        ConnectorsControllerImportRunMutationVariables,
        TContext
      > => {
      return useMutation(getConnectorsControllerImportRunMutationOptions(options), queryClient);
    }
    /**
 * @summary Disconnect one connection and clear stored credentials
 */
export const connectorsControllerDisconnectConnection = (
    connectionId: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/connectors/connections/${connectionId}/disconnect`, method: 'POST', signal
    },
      );
    }




export const getConnectorsControllerDisconnectConnectionMutationKey = () => ['connectorsControllerDisconnectConnection'] as const;

export const getConnectorsControllerDisconnectConnectionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connectorsControllerDisconnectConnection>>, TError,ConnectorsControllerDisconnectConnectionMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof connectorsControllerDisconnectConnection>>, TError,ConnectorsControllerDisconnectConnectionMutationVariables, TContext> => {

const mutationKey = getConnectorsControllerDisconnectConnectionMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof connectorsControllerDisconnectConnection>>, ConnectorsControllerDisconnectConnectionMutationVariables> = (props) => {
          const {connectionId} = props ?? {};

          return  connectorsControllerDisconnectConnection(connectionId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ConnectorsControllerDisconnectConnectionMutationResult = NonNullable<Awaited<ReturnType<typeof connectorsControllerDisconnectConnection>>>

    export type ConnectorsControllerDisconnectConnectionMutationError = unknown
    export type ConnectorsControllerDisconnectConnectionMutationVariables = {connectionId: string}

    /**
 * @summary Disconnect one connection and clear stored credentials
 */
export const useConnectorsControllerDisconnectConnection = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connectorsControllerDisconnectConnection>>, TError,ConnectorsControllerDisconnectConnectionMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof connectorsControllerDisconnectConnection>>,
        TError,
        ConnectorsControllerDisconnectConnectionMutationVariables,
        TContext
      > => {
      return useMutation(getConnectorsControllerDisconnectConnectionMutationOptions(options), queryClient);
    }
    /**
 * @summary List active connections for one connector
 */
export const connectorsControllerListConnectorConnections = (
    connectorId: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/connectors/${connectorId}/connections`, method: 'GET', signal
    },
      );
    }




export const getConnectorsControllerListConnectorConnectionsQueryKey = (connectorId: string,) => {
    return [
    `/api/v1/connectors/${connectorId}/connections`
    ] as const;
    }


export const getConnectorsControllerListConnectorConnectionsQueryOptions = <TData = Awaited<ReturnType<typeof connectorsControllerListConnectorConnections>>, TError = unknown>(connectorId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListConnectorConnections>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConnectorsControllerListConnectorConnectionsQueryKey(connectorId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof connectorsControllerListConnectorConnections>>> = ({ signal }) => connectorsControllerListConnectorConnections(connectorId, signal);





   return  { queryKey, queryFn, enabled: connectorId !== null && connectorId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListConnectorConnections>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConnectorsControllerListConnectorConnectionsQueryResult = NonNullable<Awaited<ReturnType<typeof connectorsControllerListConnectorConnections>>>
export type ConnectorsControllerListConnectorConnectionsQueryError = unknown


export function useConnectorsControllerListConnectorConnections<TData = Awaited<ReturnType<typeof connectorsControllerListConnectorConnections>>, TError = unknown>(
 connectorId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListConnectorConnections>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectorsControllerListConnectorConnections>>,
          TError,
          Awaited<ReturnType<typeof connectorsControllerListConnectorConnections>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectorsControllerListConnectorConnections<TData = Awaited<ReturnType<typeof connectorsControllerListConnectorConnections>>, TError = unknown>(
 connectorId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListConnectorConnections>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectorsControllerListConnectorConnections>>,
          TError,
          Awaited<ReturnType<typeof connectorsControllerListConnectorConnections>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectorsControllerListConnectorConnections<TData = Awaited<ReturnType<typeof connectorsControllerListConnectorConnections>>, TError = unknown>(
 connectorId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListConnectorConnections>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List active connections for one connector
 */

export function useConnectorsControllerListConnectorConnections<TData = Awaited<ReturnType<typeof connectorsControllerListConnectorConnections>>, TError = unknown>(
 connectorId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectorsControllerListConnectorConnections>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConnectorsControllerListConnectorConnectionsQueryOptions(connectorId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Validate credentials and create a new connection
 */
export const connectorsControllerCreateConnection = (
    connectorId: string,
    connectConnectorDto: ConnectConnectorDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/connectors/${connectorId}/connections`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: connectConnectorDto, signal
    },
      );
    }




export const getConnectorsControllerCreateConnectionMutationKey = () => ['connectorsControllerCreateConnection'] as const;

export const getConnectorsControllerCreateConnectionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connectorsControllerCreateConnection>>, TError,ConnectorsControllerCreateConnectionMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof connectorsControllerCreateConnection>>, TError,ConnectorsControllerCreateConnectionMutationVariables, TContext> => {

const mutationKey = getConnectorsControllerCreateConnectionMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof connectorsControllerCreateConnection>>, ConnectorsControllerCreateConnectionMutationVariables> = (props) => {
          const {connectorId,data} = props ?? {};

          return  connectorsControllerCreateConnection(connectorId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ConnectorsControllerCreateConnectionMutationResult = NonNullable<Awaited<ReturnType<typeof connectorsControllerCreateConnection>>>
    export type ConnectorsControllerCreateConnectionMutationBody = ConnectConnectorDto
    export type ConnectorsControllerCreateConnectionMutationError = unknown
    export type ConnectorsControllerCreateConnectionMutationVariables = {connectorId: string;data: ConnectConnectorDto}

    /**
 * @summary Validate credentials and create a new connection
 */
export const useConnectorsControllerCreateConnection = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connectorsControllerCreateConnection>>, TError,ConnectorsControllerCreateConnectionMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof connectorsControllerCreateConnection>>,
        TError,
        ConnectorsControllerCreateConnectionMutationVariables,
        TContext
      > => {
      return useMutation(getConnectorsControllerCreateConnectionMutationOptions(options), queryClient);
    }
