/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AcquireLockDto
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Who currently holds the edit lock on a page
 */
export const contentLocksControllerPage = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/pages/${id}/lock`, method: 'GET', signal
    },
      );
    }




export const getContentLocksControllerPageQueryKey = (id: string,) => {
    return [
    `/api/v1/pages/${id}/lock`
    ] as const;
    }


export const getContentLocksControllerPageQueryOptions = <TData = Awaited<ReturnType<typeof contentLocksControllerPage>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentLocksControllerPage>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getContentLocksControllerPageQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof contentLocksControllerPage>>> = ({ signal }) => contentLocksControllerPage(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof contentLocksControllerPage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ContentLocksControllerPageQueryResult = NonNullable<Awaited<ReturnType<typeof contentLocksControllerPage>>>
export type ContentLocksControllerPageQueryError = unknown


export function useContentLocksControllerPage<TData = Awaited<ReturnType<typeof contentLocksControllerPage>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentLocksControllerPage>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentLocksControllerPage>>,
          TError,
          Awaited<ReturnType<typeof contentLocksControllerPage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentLocksControllerPage<TData = Awaited<ReturnType<typeof contentLocksControllerPage>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentLocksControllerPage>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentLocksControllerPage>>,
          TError,
          Awaited<ReturnType<typeof contentLocksControllerPage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentLocksControllerPage<TData = Awaited<ReturnType<typeof contentLocksControllerPage>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentLocksControllerPage>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Who currently holds the edit lock on a page
 */

export function useContentLocksControllerPage<TData = Awaited<ReturnType<typeof contentLocksControllerPage>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentLocksControllerPage>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getContentLocksControllerPageQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Acquire/heartbeat the page edit lock (?takeOver to steal)
 */
export const contentLocksControllerAcquirePage = (
    id: string,
    acquireLockDto: AcquireLockDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/pages/${id}/lock`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: acquireLockDto, signal
    },
      );
    }




export const getContentLocksControllerAcquirePageMutationKey = () => ['contentLocksControllerAcquirePage'] as const;

export const getContentLocksControllerAcquirePageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contentLocksControllerAcquirePage>>, TError,ContentLocksControllerAcquirePageMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof contentLocksControllerAcquirePage>>, TError,ContentLocksControllerAcquirePageMutationVariables, TContext> => {

const mutationKey = getContentLocksControllerAcquirePageMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof contentLocksControllerAcquirePage>>, ContentLocksControllerAcquirePageMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  contentLocksControllerAcquirePage(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ContentLocksControllerAcquirePageMutationResult = NonNullable<Awaited<ReturnType<typeof contentLocksControllerAcquirePage>>>
    export type ContentLocksControllerAcquirePageMutationBody = AcquireLockDto
    export type ContentLocksControllerAcquirePageMutationError = unknown
    export type ContentLocksControllerAcquirePageMutationVariables = {id: string;data: AcquireLockDto}

    /**
 * @summary Acquire/heartbeat the page edit lock (?takeOver to steal)
 */
export const useContentLocksControllerAcquirePage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contentLocksControllerAcquirePage>>, TError,ContentLocksControllerAcquirePageMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof contentLocksControllerAcquirePage>>,
        TError,
        ContentLocksControllerAcquirePageMutationVariables,
        TContext
      > => {
      return useMutation(getContentLocksControllerAcquirePageMutationOptions(options), queryClient);
    }
    /**
 * @summary Release the page edit lock (holder only)
 */
export const contentLocksControllerReleasePage = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/pages/${id}/lock`, method: 'DELETE', signal
    },
      );
    }




export const getContentLocksControllerReleasePageMutationKey = () => ['contentLocksControllerReleasePage'] as const;

export const getContentLocksControllerReleasePageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contentLocksControllerReleasePage>>, TError,ContentLocksControllerReleasePageMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof contentLocksControllerReleasePage>>, TError,ContentLocksControllerReleasePageMutationVariables, TContext> => {

const mutationKey = getContentLocksControllerReleasePageMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof contentLocksControllerReleasePage>>, ContentLocksControllerReleasePageMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  contentLocksControllerReleasePage(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ContentLocksControllerReleasePageMutationResult = NonNullable<Awaited<ReturnType<typeof contentLocksControllerReleasePage>>>

    export type ContentLocksControllerReleasePageMutationError = unknown
    export type ContentLocksControllerReleasePageMutationVariables = {id: string}

    /**
 * @summary Release the page edit lock (holder only)
 */
export const useContentLocksControllerReleasePage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contentLocksControllerReleasePage>>, TError,ContentLocksControllerReleasePageMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof contentLocksControllerReleasePage>>,
        TError,
        ContentLocksControllerReleasePageMutationVariables,
        TContext
      > => {
      return useMutation(getContentLocksControllerReleasePageMutationOptions(options), queryClient);
    }
    /**
 * @summary Who currently holds the edit lock on a post
 */
export const contentLocksControllerPost = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}/lock`, method: 'GET', signal
    },
      );
    }




export const getContentLocksControllerPostQueryKey = (id: string,) => {
    return [
    `/api/v1/posts/${id}/lock`
    ] as const;
    }


export const getContentLocksControllerPostQueryOptions = <TData = Awaited<ReturnType<typeof contentLocksControllerPost>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentLocksControllerPost>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getContentLocksControllerPostQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof contentLocksControllerPost>>> = ({ signal }) => contentLocksControllerPost(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof contentLocksControllerPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ContentLocksControllerPostQueryResult = NonNullable<Awaited<ReturnType<typeof contentLocksControllerPost>>>
export type ContentLocksControllerPostQueryError = unknown


export function useContentLocksControllerPost<TData = Awaited<ReturnType<typeof contentLocksControllerPost>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentLocksControllerPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentLocksControllerPost>>,
          TError,
          Awaited<ReturnType<typeof contentLocksControllerPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentLocksControllerPost<TData = Awaited<ReturnType<typeof contentLocksControllerPost>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentLocksControllerPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentLocksControllerPost>>,
          TError,
          Awaited<ReturnType<typeof contentLocksControllerPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentLocksControllerPost<TData = Awaited<ReturnType<typeof contentLocksControllerPost>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentLocksControllerPost>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Who currently holds the edit lock on a post
 */

export function useContentLocksControllerPost<TData = Awaited<ReturnType<typeof contentLocksControllerPost>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentLocksControllerPost>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getContentLocksControllerPostQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Acquire/heartbeat the post edit lock (?takeOver to steal)
 */
export const contentLocksControllerAcquirePost = (
    id: string,
    acquireLockDto: AcquireLockDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}/lock`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: acquireLockDto, signal
    },
      );
    }




export const getContentLocksControllerAcquirePostMutationKey = () => ['contentLocksControllerAcquirePost'] as const;

export const getContentLocksControllerAcquirePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contentLocksControllerAcquirePost>>, TError,ContentLocksControllerAcquirePostMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof contentLocksControllerAcquirePost>>, TError,ContentLocksControllerAcquirePostMutationVariables, TContext> => {

const mutationKey = getContentLocksControllerAcquirePostMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof contentLocksControllerAcquirePost>>, ContentLocksControllerAcquirePostMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  contentLocksControllerAcquirePost(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ContentLocksControllerAcquirePostMutationResult = NonNullable<Awaited<ReturnType<typeof contentLocksControllerAcquirePost>>>
    export type ContentLocksControllerAcquirePostMutationBody = AcquireLockDto
    export type ContentLocksControllerAcquirePostMutationError = unknown
    export type ContentLocksControllerAcquirePostMutationVariables = {id: string;data: AcquireLockDto}

    /**
 * @summary Acquire/heartbeat the post edit lock (?takeOver to steal)
 */
export const useContentLocksControllerAcquirePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contentLocksControllerAcquirePost>>, TError,ContentLocksControllerAcquirePostMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof contentLocksControllerAcquirePost>>,
        TError,
        ContentLocksControllerAcquirePostMutationVariables,
        TContext
      > => {
      return useMutation(getContentLocksControllerAcquirePostMutationOptions(options), queryClient);
    }
    /**
 * @summary Release the post edit lock (holder only)
 */
export const contentLocksControllerReleasePost = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/posts/${id}/lock`, method: 'DELETE', signal
    },
      );
    }




export const getContentLocksControllerReleasePostMutationKey = () => ['contentLocksControllerReleasePost'] as const;

export const getContentLocksControllerReleasePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contentLocksControllerReleasePost>>, TError,ContentLocksControllerReleasePostMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof contentLocksControllerReleasePost>>, TError,ContentLocksControllerReleasePostMutationVariables, TContext> => {

const mutationKey = getContentLocksControllerReleasePostMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof contentLocksControllerReleasePost>>, ContentLocksControllerReleasePostMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  contentLocksControllerReleasePost(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ContentLocksControllerReleasePostMutationResult = NonNullable<Awaited<ReturnType<typeof contentLocksControllerReleasePost>>>

    export type ContentLocksControllerReleasePostMutationError = unknown
    export type ContentLocksControllerReleasePostMutationVariables = {id: string}

    /**
 * @summary Release the post edit lock (holder only)
 */
export const useContentLocksControllerReleasePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contentLocksControllerReleasePost>>, TError,ContentLocksControllerReleasePostMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof contentLocksControllerReleasePost>>,
        TError,
        ContentLocksControllerReleasePostMutationVariables,
        TContext
      > => {
      return useMutation(getContentLocksControllerReleasePostMutationOptions(options), queryClient);
    }
