/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ContentApiControllerListCollectionItemsParams,
  ContentApiControllerListMediaParams,
  ContentApiControllerListPagesParams,
  ContentApiControllerListPostsParams
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const contentApiControllerListPages = (
    params: ContentApiControllerListPagesParams,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/content/pages`, method: 'GET',
        params, signal
    },
      );
    }




export const getContentApiControllerListPagesQueryKey = (params?: ContentApiControllerListPagesParams,) => {
    return [
    `/api/v1/content/pages`, ...(params ? [params] : [])
    ] as const;
    }


export const getContentApiControllerListPagesQueryOptions = <TData = Awaited<ReturnType<typeof contentApiControllerListPages>>, TError = unknown>(params: ContentApiControllerListPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListPages>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getContentApiControllerListPagesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof contentApiControllerListPages>>> = ({ signal }) => contentApiControllerListPages(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListPages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ContentApiControllerListPagesQueryResult = NonNullable<Awaited<ReturnType<typeof contentApiControllerListPages>>>
export type ContentApiControllerListPagesQueryError = unknown


export function useContentApiControllerListPages<TData = Awaited<ReturnType<typeof contentApiControllerListPages>>, TError = unknown>(
 params: ContentApiControllerListPagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListPages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentApiControllerListPages>>,
          TError,
          Awaited<ReturnType<typeof contentApiControllerListPages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentApiControllerListPages<TData = Awaited<ReturnType<typeof contentApiControllerListPages>>, TError = unknown>(
 params: ContentApiControllerListPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListPages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentApiControllerListPages>>,
          TError,
          Awaited<ReturnType<typeof contentApiControllerListPages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentApiControllerListPages<TData = Awaited<ReturnType<typeof contentApiControllerListPages>>, TError = unknown>(
 params: ContentApiControllerListPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListPages>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useContentApiControllerListPages<TData = Awaited<ReturnType<typeof contentApiControllerListPages>>, TError = unknown>(
 params: ContentApiControllerListPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListPages>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getContentApiControllerListPagesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const contentApiControllerGetPage = (
    slug: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/content/pages/${slug}`, method: 'GET', signal
    },
      );
    }




export const getContentApiControllerGetPageQueryKey = (slug: string,) => {
    return [
    `/api/v1/content/pages/${slug}`
    ] as const;
    }


export const getContentApiControllerGetPageQueryOptions = <TData = Awaited<ReturnType<typeof contentApiControllerGetPage>>, TError = unknown>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetPage>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getContentApiControllerGetPageQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof contentApiControllerGetPage>>> = ({ signal }) => contentApiControllerGetPage(slug, signal);





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetPage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ContentApiControllerGetPageQueryResult = NonNullable<Awaited<ReturnType<typeof contentApiControllerGetPage>>>
export type ContentApiControllerGetPageQueryError = unknown


export function useContentApiControllerGetPage<TData = Awaited<ReturnType<typeof contentApiControllerGetPage>>, TError = unknown>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetPage>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentApiControllerGetPage>>,
          TError,
          Awaited<ReturnType<typeof contentApiControllerGetPage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentApiControllerGetPage<TData = Awaited<ReturnType<typeof contentApiControllerGetPage>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetPage>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentApiControllerGetPage>>,
          TError,
          Awaited<ReturnType<typeof contentApiControllerGetPage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentApiControllerGetPage<TData = Awaited<ReturnType<typeof contentApiControllerGetPage>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetPage>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useContentApiControllerGetPage<TData = Awaited<ReturnType<typeof contentApiControllerGetPage>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetPage>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getContentApiControllerGetPageQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const contentApiControllerListPosts = (
    params: ContentApiControllerListPostsParams,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/content/posts`, method: 'GET',
        params, signal
    },
      );
    }




export const getContentApiControllerListPostsQueryKey = (params?: ContentApiControllerListPostsParams,) => {
    return [
    `/api/v1/content/posts`, ...(params ? [params] : [])
    ] as const;
    }


export const getContentApiControllerListPostsQueryOptions = <TData = Awaited<ReturnType<typeof contentApiControllerListPosts>>, TError = unknown>(params: ContentApiControllerListPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListPosts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getContentApiControllerListPostsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof contentApiControllerListPosts>>> = ({ signal }) => contentApiControllerListPosts(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ContentApiControllerListPostsQueryResult = NonNullable<Awaited<ReturnType<typeof contentApiControllerListPosts>>>
export type ContentApiControllerListPostsQueryError = unknown


export function useContentApiControllerListPosts<TData = Awaited<ReturnType<typeof contentApiControllerListPosts>>, TError = unknown>(
 params: ContentApiControllerListPostsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentApiControllerListPosts>>,
          TError,
          Awaited<ReturnType<typeof contentApiControllerListPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentApiControllerListPosts<TData = Awaited<ReturnType<typeof contentApiControllerListPosts>>, TError = unknown>(
 params: ContentApiControllerListPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentApiControllerListPosts>>,
          TError,
          Awaited<ReturnType<typeof contentApiControllerListPosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentApiControllerListPosts<TData = Awaited<ReturnType<typeof contentApiControllerListPosts>>, TError = unknown>(
 params: ContentApiControllerListPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListPosts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useContentApiControllerListPosts<TData = Awaited<ReturnType<typeof contentApiControllerListPosts>>, TError = unknown>(
 params: ContentApiControllerListPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListPosts>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getContentApiControllerListPostsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const contentApiControllerGetPost = (
    slug: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/content/posts/${slug}`, method: 'GET', signal
    },
      );
    }




export const getContentApiControllerGetPostQueryKey = (slug: string,) => {
    return [
    `/api/v1/content/posts/${slug}`
    ] as const;
    }


export const getContentApiControllerGetPostQueryOptions = <TData = Awaited<ReturnType<typeof contentApiControllerGetPost>>, TError = unknown>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetPost>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getContentApiControllerGetPostQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof contentApiControllerGetPost>>> = ({ signal }) => contentApiControllerGetPost(slug, signal);





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ContentApiControllerGetPostQueryResult = NonNullable<Awaited<ReturnType<typeof contentApiControllerGetPost>>>
export type ContentApiControllerGetPostQueryError = unknown


export function useContentApiControllerGetPost<TData = Awaited<ReturnType<typeof contentApiControllerGetPost>>, TError = unknown>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentApiControllerGetPost>>,
          TError,
          Awaited<ReturnType<typeof contentApiControllerGetPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentApiControllerGetPost<TData = Awaited<ReturnType<typeof contentApiControllerGetPost>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentApiControllerGetPost>>,
          TError,
          Awaited<ReturnType<typeof contentApiControllerGetPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentApiControllerGetPost<TData = Awaited<ReturnType<typeof contentApiControllerGetPost>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetPost>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useContentApiControllerGetPost<TData = Awaited<ReturnType<typeof contentApiControllerGetPost>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetPost>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getContentApiControllerGetPostQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const contentApiControllerListCollectionItems = (
    slug: string,
    params: ContentApiControllerListCollectionItemsParams,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/content/collections/${slug}/items`, method: 'GET',
        params, signal
    },
      );
    }




export const getContentApiControllerListCollectionItemsQueryKey = (slug: string,
    params?: ContentApiControllerListCollectionItemsParams,) => {
    return [
    `/api/v1/content/collections/${slug}/items`, ...(params ? [params] : [])
    ] as const;
    }


export const getContentApiControllerListCollectionItemsQueryOptions = <TData = Awaited<ReturnType<typeof contentApiControllerListCollectionItems>>, TError = unknown>(slug: string,
    params: ContentApiControllerListCollectionItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListCollectionItems>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getContentApiControllerListCollectionItemsQueryKey(slug,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof contentApiControllerListCollectionItems>>> = ({ signal }) => contentApiControllerListCollectionItems(slug,params, signal);





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListCollectionItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ContentApiControllerListCollectionItemsQueryResult = NonNullable<Awaited<ReturnType<typeof contentApiControllerListCollectionItems>>>
export type ContentApiControllerListCollectionItemsQueryError = unknown


export function useContentApiControllerListCollectionItems<TData = Awaited<ReturnType<typeof contentApiControllerListCollectionItems>>, TError = unknown>(
 slug: string,
    params: ContentApiControllerListCollectionItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListCollectionItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentApiControllerListCollectionItems>>,
          TError,
          Awaited<ReturnType<typeof contentApiControllerListCollectionItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentApiControllerListCollectionItems<TData = Awaited<ReturnType<typeof contentApiControllerListCollectionItems>>, TError = unknown>(
 slug: string,
    params: ContentApiControllerListCollectionItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListCollectionItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentApiControllerListCollectionItems>>,
          TError,
          Awaited<ReturnType<typeof contentApiControllerListCollectionItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentApiControllerListCollectionItems<TData = Awaited<ReturnType<typeof contentApiControllerListCollectionItems>>, TError = unknown>(
 slug: string,
    params: ContentApiControllerListCollectionItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListCollectionItems>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useContentApiControllerListCollectionItems<TData = Awaited<ReturnType<typeof contentApiControllerListCollectionItems>>, TError = unknown>(
 slug: string,
    params: ContentApiControllerListCollectionItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListCollectionItems>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getContentApiControllerListCollectionItemsQueryOptions(slug,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const contentApiControllerGetCollectionItem = (
    slug: string,
    itemSlug: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/content/collections/${slug}/items/${itemSlug}`, method: 'GET', signal
    },
      );
    }




export const getContentApiControllerGetCollectionItemQueryKey = (slug: string,
    itemSlug: string,) => {
    return [
    `/api/v1/content/collections/${slug}/items/${itemSlug}`
    ] as const;
    }


export const getContentApiControllerGetCollectionItemQueryOptions = <TData = Awaited<ReturnType<typeof contentApiControllerGetCollectionItem>>, TError = unknown>(slug: string,
    itemSlug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetCollectionItem>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getContentApiControllerGetCollectionItemQueryKey(slug,itemSlug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof contentApiControllerGetCollectionItem>>> = ({ signal }) => contentApiControllerGetCollectionItem(slug,itemSlug, signal);





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined && itemSlug !== null && itemSlug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetCollectionItem>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ContentApiControllerGetCollectionItemQueryResult = NonNullable<Awaited<ReturnType<typeof contentApiControllerGetCollectionItem>>>
export type ContentApiControllerGetCollectionItemQueryError = unknown


export function useContentApiControllerGetCollectionItem<TData = Awaited<ReturnType<typeof contentApiControllerGetCollectionItem>>, TError = unknown>(
 slug: string,
    itemSlug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetCollectionItem>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentApiControllerGetCollectionItem>>,
          TError,
          Awaited<ReturnType<typeof contentApiControllerGetCollectionItem>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentApiControllerGetCollectionItem<TData = Awaited<ReturnType<typeof contentApiControllerGetCollectionItem>>, TError = unknown>(
 slug: string,
    itemSlug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetCollectionItem>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentApiControllerGetCollectionItem>>,
          TError,
          Awaited<ReturnType<typeof contentApiControllerGetCollectionItem>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentApiControllerGetCollectionItem<TData = Awaited<ReturnType<typeof contentApiControllerGetCollectionItem>>, TError = unknown>(
 slug: string,
    itemSlug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetCollectionItem>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useContentApiControllerGetCollectionItem<TData = Awaited<ReturnType<typeof contentApiControllerGetCollectionItem>>, TError = unknown>(
 slug: string,
    itemSlug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerGetCollectionItem>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getContentApiControllerGetCollectionItemQueryOptions(slug,itemSlug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const contentApiControllerListMedia = (
    params: ContentApiControllerListMediaParams,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/content/media`, method: 'GET',
        params, signal
    },
      );
    }




export const getContentApiControllerListMediaQueryKey = (params?: ContentApiControllerListMediaParams,) => {
    return [
    `/api/v1/content/media`, ...(params ? [params] : [])
    ] as const;
    }


export const getContentApiControllerListMediaQueryOptions = <TData = Awaited<ReturnType<typeof contentApiControllerListMedia>>, TError = unknown>(params: ContentApiControllerListMediaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListMedia>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getContentApiControllerListMediaQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof contentApiControllerListMedia>>> = ({ signal }) => contentApiControllerListMedia(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListMedia>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ContentApiControllerListMediaQueryResult = NonNullable<Awaited<ReturnType<typeof contentApiControllerListMedia>>>
export type ContentApiControllerListMediaQueryError = unknown


export function useContentApiControllerListMedia<TData = Awaited<ReturnType<typeof contentApiControllerListMedia>>, TError = unknown>(
 params: ContentApiControllerListMediaParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListMedia>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentApiControllerListMedia>>,
          TError,
          Awaited<ReturnType<typeof contentApiControllerListMedia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentApiControllerListMedia<TData = Awaited<ReturnType<typeof contentApiControllerListMedia>>, TError = unknown>(
 params: ContentApiControllerListMediaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListMedia>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentApiControllerListMedia>>,
          TError,
          Awaited<ReturnType<typeof contentApiControllerListMedia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useContentApiControllerListMedia<TData = Awaited<ReturnType<typeof contentApiControllerListMedia>>, TError = unknown>(
 params: ContentApiControllerListMediaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListMedia>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useContentApiControllerListMedia<TData = Awaited<ReturnType<typeof contentApiControllerListMedia>>, TError = unknown>(
 params: ContentApiControllerListMediaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof contentApiControllerListMedia>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getContentApiControllerListMediaQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
