/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HubspotPreviewDto,
  HubspotRunDto,
  HubspotRunExportDto
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





/**
 * @summary List a tenant's HubSpot CMS pages + blog posts to import
 */
export const hubspotImportControllerPreview = (
    hubspotPreviewDto: HubspotPreviewDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/hubspot-import/preview`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hubspotPreviewDto, signal
    },
      );
    }




export const getHubspotImportControllerPreviewMutationKey = () => ['hubspotImportControllerPreview'] as const;

export const getHubspotImportControllerPreviewMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof hubspotImportControllerPreview>>, TError,HubspotImportControllerPreviewMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof hubspotImportControllerPreview>>, TError,HubspotImportControllerPreviewMutationVariables, TContext> => {

const mutationKey = getHubspotImportControllerPreviewMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof hubspotImportControllerPreview>>, HubspotImportControllerPreviewMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  hubspotImportControllerPreview(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HubspotImportControllerPreviewMutationResult = NonNullable<Awaited<ReturnType<typeof hubspotImportControllerPreview>>>
    export type HubspotImportControllerPreviewMutationBody = HubspotPreviewDto
    export type HubspotImportControllerPreviewMutationError = unknown
    export type HubspotImportControllerPreviewMutationVariables = {data: HubspotPreviewDto}

    /**
 * @summary List a tenant's HubSpot CMS pages + blog posts to import
 */
export const useHubspotImportControllerPreview = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof hubspotImportControllerPreview>>, TError,HubspotImportControllerPreviewMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof hubspotImportControllerPreview>>,
        TError,
        HubspotImportControllerPreviewMutationVariables,
        TContext
      > => {
      return useMutation(getHubspotImportControllerPreviewMutationOptions(options), queryClient);
    }
    /**
 * @summary Import selected HubSpot pages/posts as OB-CMS drafts
 */
export const hubspotImportControllerRun = (
    hubspotRunDto: HubspotRunDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/hubspot-import/run`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hubspotRunDto, signal
    },
      );
    }




export const getHubspotImportControllerRunMutationKey = () => ['hubspotImportControllerRun'] as const;

export const getHubspotImportControllerRunMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof hubspotImportControllerRun>>, TError,HubspotImportControllerRunMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof hubspotImportControllerRun>>, TError,HubspotImportControllerRunMutationVariables, TContext> => {

const mutationKey = getHubspotImportControllerRunMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof hubspotImportControllerRun>>, HubspotImportControllerRunMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  hubspotImportControllerRun(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HubspotImportControllerRunMutationResult = NonNullable<Awaited<ReturnType<typeof hubspotImportControllerRun>>>
    export type HubspotImportControllerRunMutationBody = HubspotRunDto
    export type HubspotImportControllerRunMutationError = unknown
    export type HubspotImportControllerRunMutationVariables = {data: HubspotRunDto}

    /**
 * @summary Import selected HubSpot pages/posts as OB-CMS drafts
 */
export const useHubspotImportControllerRun = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof hubspotImportControllerRun>>, TError,HubspotImportControllerRunMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof hubspotImportControllerRun>>,
        TError,
        HubspotImportControllerRunMutationVariables,
        TContext
      > => {
      return useMutation(getHubspotImportControllerRunMutationOptions(options), queryClient);
    }
    /**
 * @summary Offline import from an uploaded HubSpot export JSON (no live token)
 */
export const hubspotImportControllerRunExport = (
    hubspotRunExportDto: HubspotRunExportDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/hubspot-import/run-export`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hubspotRunExportDto, signal
    },
      );
    }




export const getHubspotImportControllerRunExportMutationKey = () => ['hubspotImportControllerRunExport'] as const;

export const getHubspotImportControllerRunExportMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof hubspotImportControllerRunExport>>, TError,HubspotImportControllerRunExportMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof hubspotImportControllerRunExport>>, TError,HubspotImportControllerRunExportMutationVariables, TContext> => {

const mutationKey = getHubspotImportControllerRunExportMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof hubspotImportControllerRunExport>>, HubspotImportControllerRunExportMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  hubspotImportControllerRunExport(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HubspotImportControllerRunExportMutationResult = NonNullable<Awaited<ReturnType<typeof hubspotImportControllerRunExport>>>
    export type HubspotImportControllerRunExportMutationBody = HubspotRunExportDto
    export type HubspotImportControllerRunExportMutationError = unknown
    export type HubspotImportControllerRunExportMutationVariables = {data: HubspotRunExportDto}

    /**
 * @summary Offline import from an uploaded HubSpot export JSON (no live token)
 */
export const useHubspotImportControllerRunExport = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof hubspotImportControllerRunExport>>, TError,HubspotImportControllerRunExportMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof hubspotImportControllerRunExport>>,
        TError,
        HubspotImportControllerRunExportMutationVariables,
        TContext
      > => {
      return useMutation(getHubspotImportControllerRunExportMutationOptions(options), queryClient);
    }
