/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AcceptInvitationDto,
  CreateInvitationDto
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List this site's invitations
 */
export const invitationsControllerList = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/invitations`, method: 'GET', signal
    },
      );
    }




export const getInvitationsControllerListQueryKey = () => {
    return [
    `/api/v1/invitations`
    ] as const;
    }


export const getInvitationsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof invitationsControllerList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invitationsControllerList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInvitationsControllerListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof invitationsControllerList>>> = ({ signal }) => invitationsControllerList(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof invitationsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InvitationsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof invitationsControllerList>>>
export type InvitationsControllerListQueryError = unknown


export function useInvitationsControllerList<TData = Awaited<ReturnType<typeof invitationsControllerList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof invitationsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invitationsControllerList>>,
          TError,
          Awaited<ReturnType<typeof invitationsControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvitationsControllerList<TData = Awaited<ReturnType<typeof invitationsControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invitationsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invitationsControllerList>>,
          TError,
          Awaited<ReturnType<typeof invitationsControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvitationsControllerList<TData = Awaited<ReturnType<typeof invitationsControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invitationsControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List this site's invitations
 */

export function useInvitationsControllerList<TData = Awaited<ReturnType<typeof invitationsControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invitationsControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInvitationsControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Invite a teammate by email
 */
export const invitationsControllerCreate = (
    createInvitationDto: CreateInvitationDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/invitations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createInvitationDto, signal
    },
      );
    }




export const getInvitationsControllerCreateMutationKey = () => ['invitationsControllerCreate'] as const;

export const getInvitationsControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerCreate>>, TError,InvitationsControllerCreateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerCreate>>, TError,InvitationsControllerCreateMutationVariables, TContext> => {

const mutationKey = getInvitationsControllerCreateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof invitationsControllerCreate>>, InvitationsControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  invitationsControllerCreate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type InvitationsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof invitationsControllerCreate>>>
    export type InvitationsControllerCreateMutationBody = CreateInvitationDto
    export type InvitationsControllerCreateMutationError = unknown
    export type InvitationsControllerCreateMutationVariables = {data: CreateInvitationDto}

    /**
 * @summary Invite a teammate by email
 */
export const useInvitationsControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerCreate>>, TError,InvitationsControllerCreateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof invitationsControllerCreate>>,
        TError,
        InvitationsControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getInvitationsControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary Resend a pending invitation
 */
export const invitationsControllerResend = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/invitations/${id}/resend`, method: 'POST', signal
    },
      );
    }




export const getInvitationsControllerResendMutationKey = () => ['invitationsControllerResend'] as const;

export const getInvitationsControllerResendMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerResend>>, TError,InvitationsControllerResendMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerResend>>, TError,InvitationsControllerResendMutationVariables, TContext> => {

const mutationKey = getInvitationsControllerResendMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof invitationsControllerResend>>, InvitationsControllerResendMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  invitationsControllerResend(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type InvitationsControllerResendMutationResult = NonNullable<Awaited<ReturnType<typeof invitationsControllerResend>>>

    export type InvitationsControllerResendMutationError = unknown
    export type InvitationsControllerResendMutationVariables = {id: string}

    /**
 * @summary Resend a pending invitation
 */
export const useInvitationsControllerResend = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerResend>>, TError,InvitationsControllerResendMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof invitationsControllerResend>>,
        TError,
        InvitationsControllerResendMutationVariables,
        TContext
      > => {
      return useMutation(getInvitationsControllerResendMutationOptions(options), queryClient);
    }
    /**
 * @summary Revoke an invitation
 */
export const invitationsControllerRevoke = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/invitations/${id}`, method: 'DELETE', signal
    },
      );
    }




export const getInvitationsControllerRevokeMutationKey = () => ['invitationsControllerRevoke'] as const;

export const getInvitationsControllerRevokeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerRevoke>>, TError,InvitationsControllerRevokeMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerRevoke>>, TError,InvitationsControllerRevokeMutationVariables, TContext> => {

const mutationKey = getInvitationsControllerRevokeMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof invitationsControllerRevoke>>, InvitationsControllerRevokeMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  invitationsControllerRevoke(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type InvitationsControllerRevokeMutationResult = NonNullable<Awaited<ReturnType<typeof invitationsControllerRevoke>>>

    export type InvitationsControllerRevokeMutationError = unknown
    export type InvitationsControllerRevokeMutationVariables = {id: string}

    /**
 * @summary Revoke an invitation
 */
export const useInvitationsControllerRevoke = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerRevoke>>, TError,InvitationsControllerRevokeMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof invitationsControllerRevoke>>,
        TError,
        InvitationsControllerRevokeMutationVariables,
        TContext
      > => {
      return useMutation(getInvitationsControllerRevokeMutationOptions(options), queryClient);
    }
    /**
 * @summary Preview an invitation (public)
 */
export const publicInvitationsControllerPreview = (
    token: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/public/invitations/${token}`, method: 'GET', signal
    },
      );
    }




export const getPublicInvitationsControllerPreviewQueryKey = (token: string,) => {
    return [
    `/api/v1/public/invitations/${token}`
    ] as const;
    }


export const getPublicInvitationsControllerPreviewQueryOptions = <TData = Awaited<ReturnType<typeof publicInvitationsControllerPreview>>, TError = unknown>(token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicInvitationsControllerPreview>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPublicInvitationsControllerPreviewQueryKey(token);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof publicInvitationsControllerPreview>>> = ({ signal }) => publicInvitationsControllerPreview(token, signal);





   return  { queryKey, queryFn, enabled: token !== null && token !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof publicInvitationsControllerPreview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PublicInvitationsControllerPreviewQueryResult = NonNullable<Awaited<ReturnType<typeof publicInvitationsControllerPreview>>>
export type PublicInvitationsControllerPreviewQueryError = unknown


export function usePublicInvitationsControllerPreview<TData = Awaited<ReturnType<typeof publicInvitationsControllerPreview>>, TError = unknown>(
 token: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicInvitationsControllerPreview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicInvitationsControllerPreview>>,
          TError,
          Awaited<ReturnType<typeof publicInvitationsControllerPreview>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicInvitationsControllerPreview<TData = Awaited<ReturnType<typeof publicInvitationsControllerPreview>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicInvitationsControllerPreview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicInvitationsControllerPreview>>,
          TError,
          Awaited<ReturnType<typeof publicInvitationsControllerPreview>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicInvitationsControllerPreview<TData = Awaited<ReturnType<typeof publicInvitationsControllerPreview>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicInvitationsControllerPreview>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Preview an invitation (public)
 */

export function usePublicInvitationsControllerPreview<TData = Awaited<ReturnType<typeof publicInvitationsControllerPreview>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicInvitationsControllerPreview>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPublicInvitationsControllerPreviewQueryOptions(token,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Accept an invitation (public)
 */
export const publicInvitationsControllerAccept = (
    token: string,
    acceptInvitationDto: AcceptInvitationDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/public/invitations/${token}/accept`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: acceptInvitationDto, signal
    },
      );
    }




export const getPublicInvitationsControllerAcceptMutationKey = () => ['publicInvitationsControllerAccept'] as const;

export const getPublicInvitationsControllerAcceptMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publicInvitationsControllerAccept>>, TError,PublicInvitationsControllerAcceptMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof publicInvitationsControllerAccept>>, TError,PublicInvitationsControllerAcceptMutationVariables, TContext> => {

const mutationKey = getPublicInvitationsControllerAcceptMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof publicInvitationsControllerAccept>>, PublicInvitationsControllerAcceptMutationVariables> = (props) => {
          const {token,data} = props ?? {};

          return  publicInvitationsControllerAccept(token,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PublicInvitationsControllerAcceptMutationResult = NonNullable<Awaited<ReturnType<typeof publicInvitationsControllerAccept>>>
    export type PublicInvitationsControllerAcceptMutationBody = AcceptInvitationDto
    export type PublicInvitationsControllerAcceptMutationError = unknown
    export type PublicInvitationsControllerAcceptMutationVariables = {token: string;data: AcceptInvitationDto}

    /**
 * @summary Accept an invitation (public)
 */
export const usePublicInvitationsControllerAccept = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publicInvitationsControllerAccept>>, TError,PublicInvitationsControllerAcceptMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof publicInvitationsControllerAccept>>,
        TError,
        PublicInvitationsControllerAcceptMutationVariables,
        TContext
      > => {
      return useMutation(getPublicInvitationsControllerAcceptMutationOptions(options), queryClient);
    }
