/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  IngestErrorDto,
  MonitoringControllerAuditsParams,
  MonitoringControllerCrmDeliveriesParams,
  MonitoringControllerErrorsParams,
  MonitoringControllerLinksParams,
  RunAuditDto,
  UpdateAuditConfigDto
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List this site's forms→CRM delivery rows
 */
export const monitoringControllerCrmDeliveries = (
    params?: MonitoringControllerCrmDeliveriesParams,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/monitoring/crm-deliveries`, method: 'GET',
        params, signal
    },
      );
    }




export const getMonitoringControllerCrmDeliveriesQueryKey = (params?: MonitoringControllerCrmDeliveriesParams,) => {
    return [
    `/api/v1/monitoring/crm-deliveries`, ...(params ? [params] : [])
    ] as const;
    }


export const getMonitoringControllerCrmDeliveriesQueryOptions = <TData = Awaited<ReturnType<typeof monitoringControllerCrmDeliveries>>, TError = unknown>(params?: MonitoringControllerCrmDeliveriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerCrmDeliveries>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMonitoringControllerCrmDeliveriesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof monitoringControllerCrmDeliveries>>> = ({ signal }) => monitoringControllerCrmDeliveries(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerCrmDeliveries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MonitoringControllerCrmDeliveriesQueryResult = NonNullable<Awaited<ReturnType<typeof monitoringControllerCrmDeliveries>>>
export type MonitoringControllerCrmDeliveriesQueryError = unknown


export function useMonitoringControllerCrmDeliveries<TData = Awaited<ReturnType<typeof monitoringControllerCrmDeliveries>>, TError = unknown>(
 params: undefined |  MonitoringControllerCrmDeliveriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerCrmDeliveries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof monitoringControllerCrmDeliveries>>,
          TError,
          Awaited<ReturnType<typeof monitoringControllerCrmDeliveries>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMonitoringControllerCrmDeliveries<TData = Awaited<ReturnType<typeof monitoringControllerCrmDeliveries>>, TError = unknown>(
 params?: MonitoringControllerCrmDeliveriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerCrmDeliveries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof monitoringControllerCrmDeliveries>>,
          TError,
          Awaited<ReturnType<typeof monitoringControllerCrmDeliveries>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMonitoringControllerCrmDeliveries<TData = Awaited<ReturnType<typeof monitoringControllerCrmDeliveries>>, TError = unknown>(
 params?: MonitoringControllerCrmDeliveriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerCrmDeliveries>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List this site's forms→CRM delivery rows
 */

export function useMonitoringControllerCrmDeliveries<TData = Awaited<ReturnType<typeof monitoringControllerCrmDeliveries>>, TError = unknown>(
 params?: MonitoringControllerCrmDeliveriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerCrmDeliveries>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMonitoringControllerCrmDeliveriesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Re-enqueue a forms→CRM delivery
 */
export const monitoringControllerRetryCrm = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/monitoring/crm-deliveries/${id}/retry`, method: 'POST', signal
    },
      );
    }




export const getMonitoringControllerRetryCrmMutationKey = () => ['monitoringControllerRetryCrm'] as const;

export const getMonitoringControllerRetryCrmMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerRetryCrm>>, TError,MonitoringControllerRetryCrmMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerRetryCrm>>, TError,MonitoringControllerRetryCrmMutationVariables, TContext> => {

const mutationKey = getMonitoringControllerRetryCrmMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof monitoringControllerRetryCrm>>, MonitoringControllerRetryCrmMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  monitoringControllerRetryCrm(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MonitoringControllerRetryCrmMutationResult = NonNullable<Awaited<ReturnType<typeof monitoringControllerRetryCrm>>>

    export type MonitoringControllerRetryCrmMutationError = unknown
    export type MonitoringControllerRetryCrmMutationVariables = {id: string}

    /**
 * @summary Re-enqueue a forms→CRM delivery
 */
export const useMonitoringControllerRetryCrm = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerRetryCrm>>, TError,MonitoringControllerRetryCrmMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof monitoringControllerRetryCrm>>,
        TError,
        MonitoringControllerRetryCrmMutationVariables,
        TContext
      > => {
      return useMutation(getMonitoringControllerRetryCrmMutationOptions(options), queryClient);
    }
    /**
 * @summary Ingest a runtime error (host-resolved, deduped, rate-limited)
 */
export const monitoringControllerIngestError = (
    ingestErrorDto: IngestErrorDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/monitoring/errors`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: ingestErrorDto, signal
    },
      );
    }




export const getMonitoringControllerIngestErrorMutationKey = () => ['monitoringControllerIngestError'] as const;

export const getMonitoringControllerIngestErrorMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerIngestError>>, TError,MonitoringControllerIngestErrorMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerIngestError>>, TError,MonitoringControllerIngestErrorMutationVariables, TContext> => {

const mutationKey = getMonitoringControllerIngestErrorMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof monitoringControllerIngestError>>, MonitoringControllerIngestErrorMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  monitoringControllerIngestError(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MonitoringControllerIngestErrorMutationResult = NonNullable<Awaited<ReturnType<typeof monitoringControllerIngestError>>>
    export type MonitoringControllerIngestErrorMutationBody = IngestErrorDto
    export type MonitoringControllerIngestErrorMutationError = unknown
    export type MonitoringControllerIngestErrorMutationVariables = {data: IngestErrorDto}

    /**
 * @summary Ingest a runtime error (host-resolved, deduped, rate-limited)
 */
export const useMonitoringControllerIngestError = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerIngestError>>, TError,MonitoringControllerIngestErrorMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof monitoringControllerIngestError>>,
        TError,
        MonitoringControllerIngestErrorMutationVariables,
        TContext
      > => {
      return useMutation(getMonitoringControllerIngestErrorMutationOptions(options), queryClient);
    }
    /**
 * @summary List captured runtime errors for this site
 */
export const monitoringControllerErrors = (
    params?: MonitoringControllerErrorsParams,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/monitoring/errors`, method: 'GET',
        params, signal
    },
      );
    }




export const getMonitoringControllerErrorsQueryKey = (params?: MonitoringControllerErrorsParams,) => {
    return [
    `/api/v1/monitoring/errors`, ...(params ? [params] : [])
    ] as const;
    }


export const getMonitoringControllerErrorsQueryOptions = <TData = Awaited<ReturnType<typeof monitoringControllerErrors>>, TError = unknown>(params?: MonitoringControllerErrorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerErrors>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMonitoringControllerErrorsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof monitoringControllerErrors>>> = ({ signal }) => monitoringControllerErrors(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerErrors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MonitoringControllerErrorsQueryResult = NonNullable<Awaited<ReturnType<typeof monitoringControllerErrors>>>
export type MonitoringControllerErrorsQueryError = unknown


export function useMonitoringControllerErrors<TData = Awaited<ReturnType<typeof monitoringControllerErrors>>, TError = unknown>(
 params: undefined |  MonitoringControllerErrorsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerErrors>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof monitoringControllerErrors>>,
          TError,
          Awaited<ReturnType<typeof monitoringControllerErrors>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMonitoringControllerErrors<TData = Awaited<ReturnType<typeof monitoringControllerErrors>>, TError = unknown>(
 params?: MonitoringControllerErrorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerErrors>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof monitoringControllerErrors>>,
          TError,
          Awaited<ReturnType<typeof monitoringControllerErrors>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMonitoringControllerErrors<TData = Awaited<ReturnType<typeof monitoringControllerErrors>>, TError = unknown>(
 params?: MonitoringControllerErrorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerErrors>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List captured runtime errors for this site
 */

export function useMonitoringControllerErrors<TData = Awaited<ReturnType<typeof monitoringControllerErrors>>, TError = unknown>(
 params?: MonitoringControllerErrorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerErrors>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMonitoringControllerErrorsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary List page-audit / certification rows
 */
export const monitoringControllerAudits = (
    params?: MonitoringControllerAuditsParams,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/monitoring/audits`, method: 'GET',
        params, signal
    },
      );
    }




export const getMonitoringControllerAuditsQueryKey = (params?: MonitoringControllerAuditsParams,) => {
    return [
    `/api/v1/monitoring/audits`, ...(params ? [params] : [])
    ] as const;
    }


export const getMonitoringControllerAuditsQueryOptions = <TData = Awaited<ReturnType<typeof monitoringControllerAudits>>, TError = unknown>(params?: MonitoringControllerAuditsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAudits>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMonitoringControllerAuditsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof monitoringControllerAudits>>> = ({ signal }) => monitoringControllerAudits(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAudits>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MonitoringControllerAuditsQueryResult = NonNullable<Awaited<ReturnType<typeof monitoringControllerAudits>>>
export type MonitoringControllerAuditsQueryError = unknown


export function useMonitoringControllerAudits<TData = Awaited<ReturnType<typeof monitoringControllerAudits>>, TError = unknown>(
 params: undefined |  MonitoringControllerAuditsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAudits>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof monitoringControllerAudits>>,
          TError,
          Awaited<ReturnType<typeof monitoringControllerAudits>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMonitoringControllerAudits<TData = Awaited<ReturnType<typeof monitoringControllerAudits>>, TError = unknown>(
 params?: MonitoringControllerAuditsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAudits>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof monitoringControllerAudits>>,
          TError,
          Awaited<ReturnType<typeof monitoringControllerAudits>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMonitoringControllerAudits<TData = Awaited<ReturnType<typeof monitoringControllerAudits>>, TError = unknown>(
 params?: MonitoringControllerAuditsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAudits>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List page-audit / certification rows
 */

export function useMonitoringControllerAudits<TData = Awaited<ReturnType<typeof monitoringControllerAudits>>, TError = unknown>(
 params?: MonitoringControllerAuditsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAudits>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMonitoringControllerAuditsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Enqueue a real Lighthouse page-audit run for a path
 */
export const monitoringControllerRunAudit = (
    runAuditDto: RunAuditDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/monitoring/audits/run`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: runAuditDto, signal
    },
      );
    }




export const getMonitoringControllerRunAuditMutationKey = () => ['monitoringControllerRunAudit'] as const;

export const getMonitoringControllerRunAuditMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerRunAudit>>, TError,MonitoringControllerRunAuditMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerRunAudit>>, TError,MonitoringControllerRunAuditMutationVariables, TContext> => {

const mutationKey = getMonitoringControllerRunAuditMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof monitoringControllerRunAudit>>, MonitoringControllerRunAuditMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  monitoringControllerRunAudit(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MonitoringControllerRunAuditMutationResult = NonNullable<Awaited<ReturnType<typeof monitoringControllerRunAudit>>>
    export type MonitoringControllerRunAuditMutationBody = RunAuditDto
    export type MonitoringControllerRunAuditMutationError = unknown
    export type MonitoringControllerRunAuditMutationVariables = {data: RunAuditDto}

    /**
 * @summary Enqueue a real Lighthouse page-audit run for a path
 */
export const useMonitoringControllerRunAudit = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerRunAudit>>, TError,MonitoringControllerRunAuditMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof monitoringControllerRunAudit>>,
        TError,
        MonitoringControllerRunAuditMutationVariables,
        TContext
      > => {
      return useMutation(getMonitoringControllerRunAuditMutationOptions(options), queryClient);
    }
    /**
 * @summary Enqueue a Lighthouse audit for every published page (bulk scan)
 */
export const monitoringControllerScanAllAudits = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/monitoring/audits/scan-all`, method: 'POST', signal
    },
      );
    }




export const getMonitoringControllerScanAllAuditsMutationKey = () => ['monitoringControllerScanAllAudits'] as const;

export const getMonitoringControllerScanAllAuditsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerScanAllAudits>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerScanAllAudits>>, TError,void, TContext> => {

const mutationKey = getMonitoringControllerScanAllAuditsMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof monitoringControllerScanAllAudits>>, void> = () => {


          return  monitoringControllerScanAllAudits()
        }






  return  { mutationFn, ...mutationOptions }}

    export type MonitoringControllerScanAllAuditsMutationResult = NonNullable<Awaited<ReturnType<typeof monitoringControllerScanAllAudits>>>

    export type MonitoringControllerScanAllAuditsMutationError = unknown


    /**
 * @summary Enqueue a Lighthouse audit for every published page (bulk scan)
 */
export const useMonitoringControllerScanAllAudits = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerScanAllAudits>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof monitoringControllerScanAllAudits>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getMonitoringControllerScanAllAuditsMutationOptions(options), queryClient);
    }
    /**
 * @summary Site-wide PageSpeed dashboard rollup (health, averages, best/worst)
 */
export const monitoringControllerAuditSummary = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/monitoring/audits/summary`, method: 'GET', signal
    },
      );
    }




export const getMonitoringControllerAuditSummaryQueryKey = () => {
    return [
    `/api/v1/monitoring/audits/summary`
    ] as const;
    }


export const getMonitoringControllerAuditSummaryQueryOptions = <TData = Awaited<ReturnType<typeof monitoringControllerAuditSummary>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditSummary>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMonitoringControllerAuditSummaryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof monitoringControllerAuditSummary>>> = ({ signal }) => monitoringControllerAuditSummary(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MonitoringControllerAuditSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof monitoringControllerAuditSummary>>>
export type MonitoringControllerAuditSummaryQueryError = unknown


export function useMonitoringControllerAuditSummary<TData = Awaited<ReturnType<typeof monitoringControllerAuditSummary>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof monitoringControllerAuditSummary>>,
          TError,
          Awaited<ReturnType<typeof monitoringControllerAuditSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMonitoringControllerAuditSummary<TData = Awaited<ReturnType<typeof monitoringControllerAuditSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof monitoringControllerAuditSummary>>,
          TError,
          Awaited<ReturnType<typeof monitoringControllerAuditSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMonitoringControllerAuditSummary<TData = Awaited<ReturnType<typeof monitoringControllerAuditSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditSummary>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Site-wide PageSpeed dashboard rollup (health, averages, best/worst)
 */

export function useMonitoringControllerAuditSummary<TData = Awaited<ReturnType<typeof monitoringControllerAuditSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditSummary>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMonitoringControllerAuditSummaryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Read the site's scheduled-scan + performance-alert config
 */
export const monitoringControllerAuditConfig = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/monitoring/audits/config`, method: 'GET', signal
    },
      );
    }




export const getMonitoringControllerAuditConfigQueryKey = () => {
    return [
    `/api/v1/monitoring/audits/config`
    ] as const;
    }


export const getMonitoringControllerAuditConfigQueryOptions = <TData = Awaited<ReturnType<typeof monitoringControllerAuditConfig>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditConfig>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMonitoringControllerAuditConfigQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof monitoringControllerAuditConfig>>> = ({ signal }) => monitoringControllerAuditConfig(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MonitoringControllerAuditConfigQueryResult = NonNullable<Awaited<ReturnType<typeof monitoringControllerAuditConfig>>>
export type MonitoringControllerAuditConfigQueryError = unknown


export function useMonitoringControllerAuditConfig<TData = Awaited<ReturnType<typeof monitoringControllerAuditConfig>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditConfig>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof monitoringControllerAuditConfig>>,
          TError,
          Awaited<ReturnType<typeof monitoringControllerAuditConfig>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMonitoringControllerAuditConfig<TData = Awaited<ReturnType<typeof monitoringControllerAuditConfig>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditConfig>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof monitoringControllerAuditConfig>>,
          TError,
          Awaited<ReturnType<typeof monitoringControllerAuditConfig>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMonitoringControllerAuditConfig<TData = Awaited<ReturnType<typeof monitoringControllerAuditConfig>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditConfig>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read the site's scheduled-scan + performance-alert config
 */

export function useMonitoringControllerAuditConfig<TData = Awaited<ReturnType<typeof monitoringControllerAuditConfig>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditConfig>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMonitoringControllerAuditConfigQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Update the site's scheduled-scan + performance-alert config
 */
export const monitoringControllerUpdateAuditConfig = (
    updateAuditConfigDto: UpdateAuditConfigDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/monitoring/audits/config`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateAuditConfigDto, signal
    },
      );
    }




export const getMonitoringControllerUpdateAuditConfigMutationKey = () => ['monitoringControllerUpdateAuditConfig'] as const;

export const getMonitoringControllerUpdateAuditConfigMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerUpdateAuditConfig>>, TError,MonitoringControllerUpdateAuditConfigMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerUpdateAuditConfig>>, TError,MonitoringControllerUpdateAuditConfigMutationVariables, TContext> => {

const mutationKey = getMonitoringControllerUpdateAuditConfigMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof monitoringControllerUpdateAuditConfig>>, MonitoringControllerUpdateAuditConfigMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  monitoringControllerUpdateAuditConfig(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MonitoringControllerUpdateAuditConfigMutationResult = NonNullable<Awaited<ReturnType<typeof monitoringControllerUpdateAuditConfig>>>
    export type MonitoringControllerUpdateAuditConfigMutationBody = UpdateAuditConfigDto
    export type MonitoringControllerUpdateAuditConfigMutationError = unknown
    export type MonitoringControllerUpdateAuditConfigMutationVariables = {data: UpdateAuditConfigDto}

    /**
 * @summary Update the site's scheduled-scan + performance-alert config
 */
export const useMonitoringControllerUpdateAuditConfig = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerUpdateAuditConfig>>, TError,MonitoringControllerUpdateAuditConfigMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof monitoringControllerUpdateAuditConfig>>,
        TError,
        MonitoringControllerUpdateAuditConfigMutationVariables,
        TContext
      > => {
      return useMutation(getMonitoringControllerUpdateAuditConfigMutationOptions(options), queryClient);
    }
    /**
 * @summary Progress + rows for a bulk page-audit scan
 */
export const monitoringControllerAuditBatch = (
    batchId: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/monitoring/audits/batch/${batchId}`, method: 'GET', signal
    },
      );
    }




export const getMonitoringControllerAuditBatchQueryKey = (batchId: string,) => {
    return [
    `/api/v1/monitoring/audits/batch/${batchId}`
    ] as const;
    }


export const getMonitoringControllerAuditBatchQueryOptions = <TData = Awaited<ReturnType<typeof monitoringControllerAuditBatch>>, TError = unknown>(batchId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditBatch>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMonitoringControllerAuditBatchQueryKey(batchId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof monitoringControllerAuditBatch>>> = ({ signal }) => monitoringControllerAuditBatch(batchId, signal);





   return  { queryKey, queryFn, enabled: batchId !== null && batchId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditBatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MonitoringControllerAuditBatchQueryResult = NonNullable<Awaited<ReturnType<typeof monitoringControllerAuditBatch>>>
export type MonitoringControllerAuditBatchQueryError = unknown


export function useMonitoringControllerAuditBatch<TData = Awaited<ReturnType<typeof monitoringControllerAuditBatch>>, TError = unknown>(
 batchId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditBatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof monitoringControllerAuditBatch>>,
          TError,
          Awaited<ReturnType<typeof monitoringControllerAuditBatch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMonitoringControllerAuditBatch<TData = Awaited<ReturnType<typeof monitoringControllerAuditBatch>>, TError = unknown>(
 batchId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditBatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof monitoringControllerAuditBatch>>,
          TError,
          Awaited<ReturnType<typeof monitoringControllerAuditBatch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMonitoringControllerAuditBatch<TData = Awaited<ReturnType<typeof monitoringControllerAuditBatch>>, TError = unknown>(
 batchId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditBatch>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Progress + rows for a bulk page-audit scan
 */

export function useMonitoringControllerAuditBatch<TData = Awaited<ReturnType<typeof monitoringControllerAuditBatch>>, TError = unknown>(
 batchId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditBatch>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMonitoringControllerAuditBatchQueryOptions(batchId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Preview the auto-fixes available for an audit's page
 */
export const monitoringControllerAuditFixes = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/monitoring/audits/${id}/fixes`, method: 'GET', signal
    },
      );
    }




export const getMonitoringControllerAuditFixesQueryKey = (id: string,) => {
    return [
    `/api/v1/monitoring/audits/${id}/fixes`
    ] as const;
    }


export const getMonitoringControllerAuditFixesQueryOptions = <TData = Awaited<ReturnType<typeof monitoringControllerAuditFixes>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditFixes>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMonitoringControllerAuditFixesQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof monitoringControllerAuditFixes>>> = ({ signal }) => monitoringControllerAuditFixes(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditFixes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MonitoringControllerAuditFixesQueryResult = NonNullable<Awaited<ReturnType<typeof monitoringControllerAuditFixes>>>
export type MonitoringControllerAuditFixesQueryError = unknown


export function useMonitoringControllerAuditFixes<TData = Awaited<ReturnType<typeof monitoringControllerAuditFixes>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditFixes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof monitoringControllerAuditFixes>>,
          TError,
          Awaited<ReturnType<typeof monitoringControllerAuditFixes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMonitoringControllerAuditFixes<TData = Awaited<ReturnType<typeof monitoringControllerAuditFixes>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditFixes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof monitoringControllerAuditFixes>>,
          TError,
          Awaited<ReturnType<typeof monitoringControllerAuditFixes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMonitoringControllerAuditFixes<TData = Awaited<ReturnType<typeof monitoringControllerAuditFixes>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditFixes>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Preview the auto-fixes available for an audit's page
 */

export function useMonitoringControllerAuditFixes<TData = Awaited<ReturnType<typeof monitoringControllerAuditFixes>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerAuditFixes>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMonitoringControllerAuditFixesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Apply every automatic auto-fix flagged on the audit's page
 */
export const monitoringControllerApplyAllAutomaticFixes = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/monitoring/audits/${id}/fixes/apply-automatic`, method: 'POST', signal
    },
      );
    }




export const getMonitoringControllerApplyAllAutomaticFixesMutationKey = () => ['monitoringControllerApplyAllAutomaticFixes'] as const;

export const getMonitoringControllerApplyAllAutomaticFixesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerApplyAllAutomaticFixes>>, TError,MonitoringControllerApplyAllAutomaticFixesMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerApplyAllAutomaticFixes>>, TError,MonitoringControllerApplyAllAutomaticFixesMutationVariables, TContext> => {

const mutationKey = getMonitoringControllerApplyAllAutomaticFixesMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof monitoringControllerApplyAllAutomaticFixes>>, MonitoringControllerApplyAllAutomaticFixesMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  monitoringControllerApplyAllAutomaticFixes(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MonitoringControllerApplyAllAutomaticFixesMutationResult = NonNullable<Awaited<ReturnType<typeof monitoringControllerApplyAllAutomaticFixes>>>

    export type MonitoringControllerApplyAllAutomaticFixesMutationError = unknown
    export type MonitoringControllerApplyAllAutomaticFixesMutationVariables = {id: string}

    /**
 * @summary Apply every automatic auto-fix flagged on the audit's page
 */
export const useMonitoringControllerApplyAllAutomaticFixes = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerApplyAllAutomaticFixes>>, TError,MonitoringControllerApplyAllAutomaticFixesMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof monitoringControllerApplyAllAutomaticFixes>>,
        TError,
        MonitoringControllerApplyAllAutomaticFixesMutationVariables,
        TContext
      > => {
      return useMutation(getMonitoringControllerApplyAllAutomaticFixesMutationOptions(options), queryClient);
    }
    /**
 * @summary Apply one auto-fix to the audit's page draft
 */
export const monitoringControllerApplyAuditFix = (
    id: string,
    ruleId: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/monitoring/audits/${id}/fixes/${ruleId}/apply`, method: 'POST', signal
    },
      );
    }




export const getMonitoringControllerApplyAuditFixMutationKey = () => ['monitoringControllerApplyAuditFix'] as const;

export const getMonitoringControllerApplyAuditFixMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerApplyAuditFix>>, TError,MonitoringControllerApplyAuditFixMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerApplyAuditFix>>, TError,MonitoringControllerApplyAuditFixMutationVariables, TContext> => {

const mutationKey = getMonitoringControllerApplyAuditFixMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof monitoringControllerApplyAuditFix>>, MonitoringControllerApplyAuditFixMutationVariables> = (props) => {
          const {id,ruleId} = props ?? {};

          return  monitoringControllerApplyAuditFix(id,ruleId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MonitoringControllerApplyAuditFixMutationResult = NonNullable<Awaited<ReturnType<typeof monitoringControllerApplyAuditFix>>>

    export type MonitoringControllerApplyAuditFixMutationError = unknown
    export type MonitoringControllerApplyAuditFixMutationVariables = {id: string;ruleId: string}

    /**
 * @summary Apply one auto-fix to the audit's page draft
 */
export const useMonitoringControllerApplyAuditFix = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerApplyAuditFix>>, TError,MonitoringControllerApplyAuditFixMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof monitoringControllerApplyAuditFix>>,
        TError,
        MonitoringControllerApplyAuditFixMutationVariables,
        TContext
      > => {
      return useMutation(getMonitoringControllerApplyAuditFixMutationOptions(options), queryClient);
    }
    /**
 * @summary Enqueue a broken-link crawl of this site's published pages
 */
export const monitoringControllerRunLinkCheck = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/monitoring/links/check`, method: 'POST', signal
    },
      );
    }




export const getMonitoringControllerRunLinkCheckMutationKey = () => ['monitoringControllerRunLinkCheck'] as const;

export const getMonitoringControllerRunLinkCheckMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerRunLinkCheck>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerRunLinkCheck>>, TError,void, TContext> => {

const mutationKey = getMonitoringControllerRunLinkCheckMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof monitoringControllerRunLinkCheck>>, void> = () => {


          return  monitoringControllerRunLinkCheck()
        }






  return  { mutationFn, ...mutationOptions }}

    export type MonitoringControllerRunLinkCheckMutationResult = NonNullable<Awaited<ReturnType<typeof monitoringControllerRunLinkCheck>>>

    export type MonitoringControllerRunLinkCheckMutationError = unknown


    /**
 * @summary Enqueue a broken-link crawl of this site's published pages
 */
export const useMonitoringControllerRunLinkCheck = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof monitoringControllerRunLinkCheck>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof monitoringControllerRunLinkCheck>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getMonitoringControllerRunLinkCheckMutationOptions(options), queryClient);
    }
    /**
 * @summary Latest broken-link crawl run + its broken links
 */
export const monitoringControllerLinks = (
    params?: MonitoringControllerLinksParams,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/monitoring/links`, method: 'GET',
        params, signal
    },
      );
    }




export const getMonitoringControllerLinksQueryKey = (params?: MonitoringControllerLinksParams,) => {
    return [
    `/api/v1/monitoring/links`, ...(params ? [params] : [])
    ] as const;
    }


export const getMonitoringControllerLinksQueryOptions = <TData = Awaited<ReturnType<typeof monitoringControllerLinks>>, TError = unknown>(params?: MonitoringControllerLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerLinks>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMonitoringControllerLinksQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof monitoringControllerLinks>>> = ({ signal }) => monitoringControllerLinks(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerLinks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MonitoringControllerLinksQueryResult = NonNullable<Awaited<ReturnType<typeof monitoringControllerLinks>>>
export type MonitoringControllerLinksQueryError = unknown


export function useMonitoringControllerLinks<TData = Awaited<ReturnType<typeof monitoringControllerLinks>>, TError = unknown>(
 params: undefined |  MonitoringControllerLinksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerLinks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof monitoringControllerLinks>>,
          TError,
          Awaited<ReturnType<typeof monitoringControllerLinks>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMonitoringControllerLinks<TData = Awaited<ReturnType<typeof monitoringControllerLinks>>, TError = unknown>(
 params?: MonitoringControllerLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerLinks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof monitoringControllerLinks>>,
          TError,
          Awaited<ReturnType<typeof monitoringControllerLinks>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMonitoringControllerLinks<TData = Awaited<ReturnType<typeof monitoringControllerLinks>>, TError = unknown>(
 params?: MonitoringControllerLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerLinks>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Latest broken-link crawl run + its broken links
 */

export function useMonitoringControllerLinks<TData = Awaited<ReturnType<typeof monitoringControllerLinks>>, TError = unknown>(
 params?: MonitoringControllerLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof monitoringControllerLinks>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMonitoringControllerLinksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
