/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List my recent notifications + my unread count
 */
export const notificationsControllerList = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/notifications`, method: 'GET', signal
    },
      );
    }




export const getNotificationsControllerListQueryKey = () => {
    return [
    `/api/v1/notifications`
    ] as const;
    }


export const getNotificationsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof notificationsControllerList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsControllerList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationsControllerListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationsControllerList>>> = ({ signal }) => notificationsControllerList(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notificationsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificationsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof notificationsControllerList>>>
export type NotificationsControllerListQueryError = unknown


export function useNotificationsControllerList<TData = Awaited<ReturnType<typeof notificationsControllerList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationsControllerList>>,
          TError,
          Awaited<ReturnType<typeof notificationsControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationsControllerList<TData = Awaited<ReturnType<typeof notificationsControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationsControllerList>>,
          TError,
          Awaited<ReturnType<typeof notificationsControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationsControllerList<TData = Awaited<ReturnType<typeof notificationsControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List my recent notifications + my unread count
 */

export function useNotificationsControllerList<TData = Awaited<ReturnType<typeof notificationsControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNotificationsControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Mark one of my notifications read
 */
export const notificationsControllerMarkRead = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/notifications/${id}/read`, method: 'POST', signal
    },
      );
    }




export const getNotificationsControllerMarkReadMutationKey = () => ['notificationsControllerMarkRead'] as const;

export const getNotificationsControllerMarkReadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationsControllerMarkRead>>, TError,NotificationsControllerMarkReadMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof notificationsControllerMarkRead>>, TError,NotificationsControllerMarkReadMutationVariables, TContext> => {

const mutationKey = getNotificationsControllerMarkReadMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notificationsControllerMarkRead>>, NotificationsControllerMarkReadMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  notificationsControllerMarkRead(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotificationsControllerMarkReadMutationResult = NonNullable<Awaited<ReturnType<typeof notificationsControllerMarkRead>>>

    export type NotificationsControllerMarkReadMutationError = unknown
    export type NotificationsControllerMarkReadMutationVariables = {id: string}

    /**
 * @summary Mark one of my notifications read
 */
export const useNotificationsControllerMarkRead = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationsControllerMarkRead>>, TError,NotificationsControllerMarkReadMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof notificationsControllerMarkRead>>,
        TError,
        NotificationsControllerMarkReadMutationVariables,
        TContext
      > => {
      return useMutation(getNotificationsControllerMarkReadMutationOptions(options), queryClient);
    }
    /**
 * @summary Mark all my notifications read
 */
export const notificationsControllerMarkAllRead = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/notifications/read-all`, method: 'POST', signal
    },
      );
    }




export const getNotificationsControllerMarkAllReadMutationKey = () => ['notificationsControllerMarkAllRead'] as const;

export const getNotificationsControllerMarkAllReadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationsControllerMarkAllRead>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof notificationsControllerMarkAllRead>>, TError,void, TContext> => {

const mutationKey = getNotificationsControllerMarkAllReadMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notificationsControllerMarkAllRead>>, void> = () => {


          return  notificationsControllerMarkAllRead()
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotificationsControllerMarkAllReadMutationResult = NonNullable<Awaited<ReturnType<typeof notificationsControllerMarkAllRead>>>

    export type NotificationsControllerMarkAllReadMutationError = unknown


    /**
 * @summary Mark all my notifications read
 */
export const useNotificationsControllerMarkAllRead = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationsControllerMarkAllRead>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof notificationsControllerMarkAllRead>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getNotificationsControllerMarkAllReadMutationOptions(options), queryClient);
    }
