/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  RestoreBackupDto
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List all database backups (platform admin only)
 */
export const backupsControllerList = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/platform/backups`, method: 'GET', signal
    },
      );
    }




export const getBackupsControllerListQueryKey = () => {
    return [
    `/api/v1/platform/backups`
    ] as const;
    }


export const getBackupsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof backupsControllerList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof backupsControllerList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBackupsControllerListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof backupsControllerList>>> = ({ signal }) => backupsControllerList(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof backupsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BackupsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof backupsControllerList>>>
export type BackupsControllerListQueryError = unknown


export function useBackupsControllerList<TData = Awaited<ReturnType<typeof backupsControllerList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof backupsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof backupsControllerList>>,
          TError,
          Awaited<ReturnType<typeof backupsControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBackupsControllerList<TData = Awaited<ReturnType<typeof backupsControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof backupsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof backupsControllerList>>,
          TError,
          Awaited<ReturnType<typeof backupsControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBackupsControllerList<TData = Awaited<ReturnType<typeof backupsControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof backupsControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all database backups (platform admin only)
 */

export function useBackupsControllerList<TData = Awaited<ReturnType<typeof backupsControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof backupsControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBackupsControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Trigger a manual backup → enqueues a worker job, returns the pending row
 */
export const backupsControllerTrigger = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/platform/backups`, method: 'POST', signal
    },
      );
    }




export const getBackupsControllerTriggerMutationKey = () => ['backupsControllerTrigger'] as const;

export const getBackupsControllerTriggerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof backupsControllerTrigger>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof backupsControllerTrigger>>, TError,void, TContext> => {

const mutationKey = getBackupsControllerTriggerMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof backupsControllerTrigger>>, void> = () => {


          return  backupsControllerTrigger()
        }






  return  { mutationFn, ...mutationOptions }}

    export type BackupsControllerTriggerMutationResult = NonNullable<Awaited<ReturnType<typeof backupsControllerTrigger>>>

    export type BackupsControllerTriggerMutationError = unknown


    /**
 * @summary Trigger a manual backup → enqueues a worker job, returns the pending row
 */
export const useBackupsControllerTrigger = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof backupsControllerTrigger>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof backupsControllerTrigger>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getBackupsControllerTriggerMutationOptions(options), queryClient);
    }
    /**
 * @summary Get a download URL for a completed backup dump
 */
export const backupsControllerDownload = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/platform/backups/${id}/download`, method: 'GET', signal
    },
      );
    }




export const getBackupsControllerDownloadQueryKey = (id: string,) => {
    return [
    `/api/v1/platform/backups/${id}/download`
    ] as const;
    }


export const getBackupsControllerDownloadQueryOptions = <TData = Awaited<ReturnType<typeof backupsControllerDownload>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof backupsControllerDownload>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBackupsControllerDownloadQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof backupsControllerDownload>>> = ({ signal }) => backupsControllerDownload(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof backupsControllerDownload>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BackupsControllerDownloadQueryResult = NonNullable<Awaited<ReturnType<typeof backupsControllerDownload>>>
export type BackupsControllerDownloadQueryError = unknown


export function useBackupsControllerDownload<TData = Awaited<ReturnType<typeof backupsControllerDownload>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof backupsControllerDownload>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof backupsControllerDownload>>,
          TError,
          Awaited<ReturnType<typeof backupsControllerDownload>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBackupsControllerDownload<TData = Awaited<ReturnType<typeof backupsControllerDownload>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof backupsControllerDownload>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof backupsControllerDownload>>,
          TError,
          Awaited<ReturnType<typeof backupsControllerDownload>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBackupsControllerDownload<TData = Awaited<ReturnType<typeof backupsControllerDownload>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof backupsControllerDownload>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a download URL for a completed backup dump
 */

export function useBackupsControllerDownload<TData = Awaited<ReturnType<typeof backupsControllerDownload>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof backupsControllerDownload>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBackupsControllerDownloadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Restore a backup (enqueues a restore job). DESTRUCTIVE — requires { confirm: true }; overwrites all current data.
 */
export const backupsControllerRestore = (
    id: string,
    restoreBackupDto: RestoreBackupDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/platform/backups/${id}/restore`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: restoreBackupDto, signal
    },
      );
    }




export const getBackupsControllerRestoreMutationKey = () => ['backupsControllerRestore'] as const;

export const getBackupsControllerRestoreMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof backupsControllerRestore>>, TError,BackupsControllerRestoreMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof backupsControllerRestore>>, TError,BackupsControllerRestoreMutationVariables, TContext> => {

const mutationKey = getBackupsControllerRestoreMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof backupsControllerRestore>>, BackupsControllerRestoreMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  backupsControllerRestore(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BackupsControllerRestoreMutationResult = NonNullable<Awaited<ReturnType<typeof backupsControllerRestore>>>
    export type BackupsControllerRestoreMutationBody = RestoreBackupDto
    export type BackupsControllerRestoreMutationError = unknown
    export type BackupsControllerRestoreMutationVariables = {id: string;data: RestoreBackupDto}

    /**
 * @summary Restore a backup (enqueues a restore job). DESTRUCTIVE — requires { confirm: true }; overwrites all current data.
 */
export const useBackupsControllerRestore = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof backupsControllerRestore>>, TError,BackupsControllerRestoreMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof backupsControllerRestore>>,
        TError,
        BackupsControllerRestoreMutationVariables,
        TContext
      > => {
      return useMutation(getBackupsControllerRestoreMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a backup dump + its ledger row
 */
export const backupsControllerRemove = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/platform/backups/${id}`, method: 'DELETE', signal
    },
      );
    }




export const getBackupsControllerRemoveMutationKey = () => ['backupsControllerRemove'] as const;

export const getBackupsControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof backupsControllerRemove>>, TError,BackupsControllerRemoveMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof backupsControllerRemove>>, TError,BackupsControllerRemoveMutationVariables, TContext> => {

const mutationKey = getBackupsControllerRemoveMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof backupsControllerRemove>>, BackupsControllerRemoveMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  backupsControllerRemove(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BackupsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof backupsControllerRemove>>>

    export type BackupsControllerRemoveMutationError = unknown
    export type BackupsControllerRemoveMutationVariables = {id: string}

    /**
 * @summary Delete a backup dump + its ledger row
 */
export const useBackupsControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof backupsControllerRemove>>, TError,BackupsControllerRemoveMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof backupsControllerRemove>>,
        TError,
        BackupsControllerRemoveMutationVariables,
        TContext
      > => {
      return useMutation(getBackupsControllerRemoveMutationOptions(options), queryClient);
    }
