/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PrivacyControllerEraseParams,
  PrivacyControllerExportParams,
  PrivacyControllerSummaryParams
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Summary of all data held for an email or visitorId (counts + identity)
 */
export const privacyControllerSummary = (
    params: PrivacyControllerSummaryParams,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/privacy/subject`, method: 'GET',
        params, signal
    },
      );
    }




export const getPrivacyControllerSummaryQueryKey = (params?: PrivacyControllerSummaryParams,) => {
    return [
    `/api/v1/privacy/subject`, ...(params ? [params] : [])
    ] as const;
    }


export const getPrivacyControllerSummaryQueryOptions = <TData = Awaited<ReturnType<typeof privacyControllerSummary>>, TError = unknown>(params: PrivacyControllerSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof privacyControllerSummary>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrivacyControllerSummaryQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof privacyControllerSummary>>> = ({ signal }) => privacyControllerSummary(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof privacyControllerSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PrivacyControllerSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof privacyControllerSummary>>>
export type PrivacyControllerSummaryQueryError = unknown


export function usePrivacyControllerSummary<TData = Awaited<ReturnType<typeof privacyControllerSummary>>, TError = unknown>(
 params: PrivacyControllerSummaryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof privacyControllerSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof privacyControllerSummary>>,
          TError,
          Awaited<ReturnType<typeof privacyControllerSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrivacyControllerSummary<TData = Awaited<ReturnType<typeof privacyControllerSummary>>, TError = unknown>(
 params: PrivacyControllerSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof privacyControllerSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof privacyControllerSummary>>,
          TError,
          Awaited<ReturnType<typeof privacyControllerSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrivacyControllerSummary<TData = Awaited<ReturnType<typeof privacyControllerSummary>>, TError = unknown>(
 params: PrivacyControllerSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof privacyControllerSummary>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Summary of all data held for an email or visitorId (counts + identity)
 */

export function usePrivacyControllerSummary<TData = Awaited<ReturnType<typeof privacyControllerSummary>>, TError = unknown>(
 params: PrivacyControllerSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof privacyControllerSummary>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPrivacyControllerSummaryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Erase / anonymize all data for an email or visitorId (audited)
 */
export const privacyControllerErase = (
    params: PrivacyControllerEraseParams,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/privacy/subject`, method: 'DELETE',
        params, signal
    },
      );
    }




export const getPrivacyControllerEraseMutationKey = () => ['privacyControllerErase'] as const;

export const getPrivacyControllerEraseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof privacyControllerErase>>, TError,PrivacyControllerEraseMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof privacyControllerErase>>, TError,PrivacyControllerEraseMutationVariables, TContext> => {

const mutationKey = getPrivacyControllerEraseMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof privacyControllerErase>>, PrivacyControllerEraseMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  privacyControllerErase(params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PrivacyControllerEraseMutationResult = NonNullable<Awaited<ReturnType<typeof privacyControllerErase>>>

    export type PrivacyControllerEraseMutationError = unknown
    export type PrivacyControllerEraseMutationVariables = {params: PrivacyControllerEraseParams}

    /**
 * @summary Erase / anonymize all data for an email or visitorId (audited)
 */
export const usePrivacyControllerErase = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof privacyControllerErase>>, TError,PrivacyControllerEraseMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof privacyControllerErase>>,
        TError,
        PrivacyControllerEraseMutationVariables,
        TContext
      > => {
      return useMutation(getPrivacyControllerEraseMutationOptions(options), queryClient);
    }
    /**
 * @summary Full JSON export of every row held across all tables
 */
export const privacyControllerExport = (
    params: PrivacyControllerExportParams,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/privacy/subject/export`, method: 'GET',
        params, signal
    },
      );
    }




export const getPrivacyControllerExportQueryKey = (params?: PrivacyControllerExportParams,) => {
    return [
    `/api/v1/privacy/subject/export`, ...(params ? [params] : [])
    ] as const;
    }


export const getPrivacyControllerExportQueryOptions = <TData = Awaited<ReturnType<typeof privacyControllerExport>>, TError = unknown>(params: PrivacyControllerExportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof privacyControllerExport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrivacyControllerExportQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof privacyControllerExport>>> = ({ signal }) => privacyControllerExport(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof privacyControllerExport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PrivacyControllerExportQueryResult = NonNullable<Awaited<ReturnType<typeof privacyControllerExport>>>
export type PrivacyControllerExportQueryError = unknown


export function usePrivacyControllerExport<TData = Awaited<ReturnType<typeof privacyControllerExport>>, TError = unknown>(
 params: PrivacyControllerExportParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof privacyControllerExport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof privacyControllerExport>>,
          TError,
          Awaited<ReturnType<typeof privacyControllerExport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrivacyControllerExport<TData = Awaited<ReturnType<typeof privacyControllerExport>>, TError = unknown>(
 params: PrivacyControllerExportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof privacyControllerExport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof privacyControllerExport>>,
          TError,
          Awaited<ReturnType<typeof privacyControllerExport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrivacyControllerExport<TData = Awaited<ReturnType<typeof privacyControllerExport>>, TError = unknown>(
 params: PrivacyControllerExportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof privacyControllerExport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Full JSON export of every row held across all tables
 */

export function usePrivacyControllerExport<TData = Awaited<ReturnType<typeof privacyControllerExport>>, TError = unknown>(
 params: PrivacyControllerExportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof privacyControllerExport>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPrivacyControllerExportQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
