/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FormUploadPresignDto,
  SubmitFormDto
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Public form schema for render (fields + settings only)
 */
export const publicFormsControllerGetForm = (
    formId: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/public/forms/${formId}`, method: 'GET', signal
    },
      );
    }




export const getPublicFormsControllerGetFormQueryKey = (formId: string,) => {
    return [
    `/api/v1/public/forms/${formId}`
    ] as const;
    }


export const getPublicFormsControllerGetFormQueryOptions = <TData = Awaited<ReturnType<typeof publicFormsControllerGetForm>>, TError = unknown>(formId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicFormsControllerGetForm>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPublicFormsControllerGetFormQueryKey(formId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof publicFormsControllerGetForm>>> = ({ signal }) => publicFormsControllerGetForm(formId, signal);





   return  { queryKey, queryFn, enabled: formId !== null && formId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof publicFormsControllerGetForm>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PublicFormsControllerGetFormQueryResult = NonNullable<Awaited<ReturnType<typeof publicFormsControllerGetForm>>>
export type PublicFormsControllerGetFormQueryError = unknown


export function usePublicFormsControllerGetForm<TData = Awaited<ReturnType<typeof publicFormsControllerGetForm>>, TError = unknown>(
 formId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicFormsControllerGetForm>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicFormsControllerGetForm>>,
          TError,
          Awaited<ReturnType<typeof publicFormsControllerGetForm>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicFormsControllerGetForm<TData = Awaited<ReturnType<typeof publicFormsControllerGetForm>>, TError = unknown>(
 formId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicFormsControllerGetForm>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicFormsControllerGetForm>>,
          TError,
          Awaited<ReturnType<typeof publicFormsControllerGetForm>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicFormsControllerGetForm<TData = Awaited<ReturnType<typeof publicFormsControllerGetForm>>, TError = unknown>(
 formId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicFormsControllerGetForm>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Public form schema for render (fields + settings only)
 */

export function usePublicFormsControllerGetForm<TData = Awaited<ReturnType<typeof publicFormsControllerGetForm>>, TError = unknown>(
 formId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicFormsControllerGetForm>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPublicFormsControllerGetFormQueryOptions(formId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Public form submission — persists then enqueues CRM delivery
 */
export const publicFormsControllerSubmit = (
    formId: string,
    submitFormDto: SubmitFormDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/public/forms/${formId}/submit`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: submitFormDto, signal
    },
      );
    }




export const getPublicFormsControllerSubmitMutationKey = () => ['publicFormsControllerSubmit'] as const;

export const getPublicFormsControllerSubmitMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publicFormsControllerSubmit>>, TError,PublicFormsControllerSubmitMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof publicFormsControllerSubmit>>, TError,PublicFormsControllerSubmitMutationVariables, TContext> => {

const mutationKey = getPublicFormsControllerSubmitMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof publicFormsControllerSubmit>>, PublicFormsControllerSubmitMutationVariables> = (props) => {
          const {formId,data} = props ?? {};

          return  publicFormsControllerSubmit(formId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PublicFormsControllerSubmitMutationResult = NonNullable<Awaited<ReturnType<typeof publicFormsControllerSubmit>>>
    export type PublicFormsControllerSubmitMutationBody = SubmitFormDto
    export type PublicFormsControllerSubmitMutationError = unknown
    export type PublicFormsControllerSubmitMutationVariables = {formId: string;data: SubmitFormDto}

    /**
 * @summary Public form submission — persists then enqueues CRM delivery
 */
export const usePublicFormsControllerSubmit = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publicFormsControllerSubmit>>, TError,PublicFormsControllerSubmitMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof publicFormsControllerSubmit>>,
        TError,
        PublicFormsControllerSubmitMutationVariables,
        TContext
      > => {
      return useMutation(getPublicFormsControllerSubmitMutationOptions(options), queryClient);
    }
    /**
 * @summary Presign a file-upload for a form field (direct browser PUT to S3)
 */
export const publicFormsControllerPresignUpload = (
    formId: string,
    formUploadPresignDto: FormUploadPresignDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/public/forms/${formId}/upload`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: formUploadPresignDto, signal
    },
      );
    }




export const getPublicFormsControllerPresignUploadMutationKey = () => ['publicFormsControllerPresignUpload'] as const;

export const getPublicFormsControllerPresignUploadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publicFormsControllerPresignUpload>>, TError,PublicFormsControllerPresignUploadMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof publicFormsControllerPresignUpload>>, TError,PublicFormsControllerPresignUploadMutationVariables, TContext> => {

const mutationKey = getPublicFormsControllerPresignUploadMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof publicFormsControllerPresignUpload>>, PublicFormsControllerPresignUploadMutationVariables> = (props) => {
          const {formId,data} = props ?? {};

          return  publicFormsControllerPresignUpload(formId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PublicFormsControllerPresignUploadMutationResult = NonNullable<Awaited<ReturnType<typeof publicFormsControllerPresignUpload>>>
    export type PublicFormsControllerPresignUploadMutationBody = FormUploadPresignDto
    export type PublicFormsControllerPresignUploadMutationError = unknown
    export type PublicFormsControllerPresignUploadMutationVariables = {formId: string;data: FormUploadPresignDto}

    /**
 * @summary Presign a file-upload for a form field (direct browser PUT to S3)
 */
export const usePublicFormsControllerPresignUpload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publicFormsControllerPresignUpload>>, TError,PublicFormsControllerPresignUploadMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof publicFormsControllerPresignUpload>>,
        TError,
        PublicFormsControllerPresignUploadMutationVariables,
        TContext
      > => {
      return useMutation(getPublicFormsControllerPresignUploadMutationOptions(options), queryClient);
    }
