/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Published items of a collection (limit/sort)
 */
export const publicCollectionsControllerListItems = (
    slug: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/public/collections/${slug}/items`, method: 'GET', signal
    },
      );
    }




export const getPublicCollectionsControllerListItemsQueryKey = (slug: string,) => {
    return [
    `/api/v1/public/collections/${slug}/items`
    ] as const;
    }


export const getPublicCollectionsControllerListItemsQueryOptions = <TData = Awaited<ReturnType<typeof publicCollectionsControllerListItems>>, TError = unknown>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicCollectionsControllerListItems>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPublicCollectionsControllerListItemsQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof publicCollectionsControllerListItems>>> = ({ signal }) => publicCollectionsControllerListItems(slug, signal);





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof publicCollectionsControllerListItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PublicCollectionsControllerListItemsQueryResult = NonNullable<Awaited<ReturnType<typeof publicCollectionsControllerListItems>>>
export type PublicCollectionsControllerListItemsQueryError = unknown


export function usePublicCollectionsControllerListItems<TData = Awaited<ReturnType<typeof publicCollectionsControllerListItems>>, TError = unknown>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicCollectionsControllerListItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicCollectionsControllerListItems>>,
          TError,
          Awaited<ReturnType<typeof publicCollectionsControllerListItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicCollectionsControllerListItems<TData = Awaited<ReturnType<typeof publicCollectionsControllerListItems>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicCollectionsControllerListItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicCollectionsControllerListItems>>,
          TError,
          Awaited<ReturnType<typeof publicCollectionsControllerListItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicCollectionsControllerListItems<TData = Awaited<ReturnType<typeof publicCollectionsControllerListItems>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicCollectionsControllerListItems>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Published items of a collection (limit/sort)
 */

export function usePublicCollectionsControllerListItems<TData = Awaited<ReturnType<typeof publicCollectionsControllerListItems>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicCollectionsControllerListItems>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPublicCollectionsControllerListItemsQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary A single published item by collection + item slug
 */
export const publicCollectionsControllerGetItem = (
    slug: string,
    itemSlug: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/public/collections/${slug}/items/${itemSlug}`, method: 'GET', signal
    },
      );
    }




export const getPublicCollectionsControllerGetItemQueryKey = (slug: string,
    itemSlug: string,) => {
    return [
    `/api/v1/public/collections/${slug}/items/${itemSlug}`
    ] as const;
    }


export const getPublicCollectionsControllerGetItemQueryOptions = <TData = Awaited<ReturnType<typeof publicCollectionsControllerGetItem>>, TError = unknown>(slug: string,
    itemSlug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicCollectionsControllerGetItem>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPublicCollectionsControllerGetItemQueryKey(slug,itemSlug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof publicCollectionsControllerGetItem>>> = ({ signal }) => publicCollectionsControllerGetItem(slug,itemSlug, signal);





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined && itemSlug !== null && itemSlug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof publicCollectionsControllerGetItem>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PublicCollectionsControllerGetItemQueryResult = NonNullable<Awaited<ReturnType<typeof publicCollectionsControllerGetItem>>>
export type PublicCollectionsControllerGetItemQueryError = unknown


export function usePublicCollectionsControllerGetItem<TData = Awaited<ReturnType<typeof publicCollectionsControllerGetItem>>, TError = unknown>(
 slug: string,
    itemSlug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicCollectionsControllerGetItem>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicCollectionsControllerGetItem>>,
          TError,
          Awaited<ReturnType<typeof publicCollectionsControllerGetItem>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicCollectionsControllerGetItem<TData = Awaited<ReturnType<typeof publicCollectionsControllerGetItem>>, TError = unknown>(
 slug: string,
    itemSlug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicCollectionsControllerGetItem>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicCollectionsControllerGetItem>>,
          TError,
          Awaited<ReturnType<typeof publicCollectionsControllerGetItem>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicCollectionsControllerGetItem<TData = Awaited<ReturnType<typeof publicCollectionsControllerGetItem>>, TError = unknown>(
 slug: string,
    itemSlug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicCollectionsControllerGetItem>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary A single published item by collection + item slug
 */

export function usePublicCollectionsControllerGetItem<TData = Awaited<ReturnType<typeof publicCollectionsControllerGetItem>>, TError = unknown>(
 slug: string,
    itemSlug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicCollectionsControllerGetItem>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPublicCollectionsControllerGetItemQueryOptions(slug,itemSlug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
