/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PublicSearchControllerQueryParams
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Public full-text search of published pages/posts/collections (host-resolved)
 */
export const publicSearchControllerQuery = (
    params?: PublicSearchControllerQueryParams,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/public/search`, method: 'GET',
        params, signal
    },
      );
    }




export const getPublicSearchControllerQueryQueryKey = (params?: PublicSearchControllerQueryParams,) => {
    return [
    `/api/v1/public/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getPublicSearchControllerQueryQueryOptions = <TData = Awaited<ReturnType<typeof publicSearchControllerQuery>>, TError = unknown>(params?: PublicSearchControllerQueryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicSearchControllerQuery>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPublicSearchControllerQueryQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof publicSearchControllerQuery>>> = ({ signal }) => publicSearchControllerQuery(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof publicSearchControllerQuery>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PublicSearchControllerQueryQueryResult = NonNullable<Awaited<ReturnType<typeof publicSearchControllerQuery>>>
export type PublicSearchControllerQueryQueryError = unknown


export function usePublicSearchControllerQuery<TData = Awaited<ReturnType<typeof publicSearchControllerQuery>>, TError = unknown>(
 params: undefined |  PublicSearchControllerQueryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicSearchControllerQuery>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicSearchControllerQuery>>,
          TError,
          Awaited<ReturnType<typeof publicSearchControllerQuery>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicSearchControllerQuery<TData = Awaited<ReturnType<typeof publicSearchControllerQuery>>, TError = unknown>(
 params?: PublicSearchControllerQueryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicSearchControllerQuery>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicSearchControllerQuery>>,
          TError,
          Awaited<ReturnType<typeof publicSearchControllerQuery>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicSearchControllerQuery<TData = Awaited<ReturnType<typeof publicSearchControllerQuery>>, TError = unknown>(
 params?: PublicSearchControllerQueryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicSearchControllerQuery>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Public full-text search of published pages/posts/collections (host-resolved)
 */

export function usePublicSearchControllerQuery<TData = Awaited<ReturnType<typeof publicSearchControllerQuery>>, TError = unknown>(
 params?: PublicSearchControllerQueryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicSearchControllerQuery>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPublicSearchControllerQueryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
