/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Public reusable-block layout for render (host-resolved)
 */
export const publicReusableBlocksControllerGet = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/public/reusable-blocks/${id}`, method: 'GET', signal
    },
      );
    }




export const getPublicReusableBlocksControllerGetQueryKey = (id: string,) => {
    return [
    `/api/v1/public/reusable-blocks/${id}`
    ] as const;
    }


export const getPublicReusableBlocksControllerGetQueryOptions = <TData = Awaited<ReturnType<typeof publicReusableBlocksControllerGet>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicReusableBlocksControllerGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPublicReusableBlocksControllerGetQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof publicReusableBlocksControllerGet>>> = ({ signal }) => publicReusableBlocksControllerGet(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof publicReusableBlocksControllerGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PublicReusableBlocksControllerGetQueryResult = NonNullable<Awaited<ReturnType<typeof publicReusableBlocksControllerGet>>>
export type PublicReusableBlocksControllerGetQueryError = unknown


export function usePublicReusableBlocksControllerGet<TData = Awaited<ReturnType<typeof publicReusableBlocksControllerGet>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicReusableBlocksControllerGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicReusableBlocksControllerGet>>,
          TError,
          Awaited<ReturnType<typeof publicReusableBlocksControllerGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicReusableBlocksControllerGet<TData = Awaited<ReturnType<typeof publicReusableBlocksControllerGet>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicReusableBlocksControllerGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicReusableBlocksControllerGet>>,
          TError,
          Awaited<ReturnType<typeof publicReusableBlocksControllerGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePublicReusableBlocksControllerGet<TData = Awaited<ReturnType<typeof publicReusableBlocksControllerGet>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicReusableBlocksControllerGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Public reusable-block layout for render (host-resolved)
 */

export function usePublicReusableBlocksControllerGet<TData = Awaited<ReturnType<typeof publicReusableBlocksControllerGet>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof publicReusableBlocksControllerGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPublicReusableBlocksControllerGetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
