/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssignCustomRoleDto,
  CreateCustomRoleDto,
  UpdateCustomRoleDto
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary The permission catalog (domain-grouped)
 */
export const rolesControllerCatalog = (
    siteId: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/sites/${siteId}/roles/permissions`, method: 'GET', signal
    },
      );
    }




export const getRolesControllerCatalogQueryKey = (siteId: string,) => {
    return [
    `/api/v1/sites/${siteId}/roles/permissions`
    ] as const;
    }


export const getRolesControllerCatalogQueryOptions = <TData = Awaited<ReturnType<typeof rolesControllerCatalog>>, TError = unknown>(siteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesControllerCatalog>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRolesControllerCatalogQueryKey(siteId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof rolesControllerCatalog>>> = ({ signal }) => rolesControllerCatalog(siteId, signal);





   return  { queryKey, queryFn, enabled: siteId !== null && siteId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof rolesControllerCatalog>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RolesControllerCatalogQueryResult = NonNullable<Awaited<ReturnType<typeof rolesControllerCatalog>>>
export type RolesControllerCatalogQueryError = unknown


export function useRolesControllerCatalog<TData = Awaited<ReturnType<typeof rolesControllerCatalog>>, TError = unknown>(
 siteId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesControllerCatalog>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolesControllerCatalog>>,
          TError,
          Awaited<ReturnType<typeof rolesControllerCatalog>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesControllerCatalog<TData = Awaited<ReturnType<typeof rolesControllerCatalog>>, TError = unknown>(
 siteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesControllerCatalog>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolesControllerCatalog>>,
          TError,
          Awaited<ReturnType<typeof rolesControllerCatalog>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesControllerCatalog<TData = Awaited<ReturnType<typeof rolesControllerCatalog>>, TError = unknown>(
 siteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesControllerCatalog>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The permission catalog (domain-grouped)
 */

export function useRolesControllerCatalog<TData = Awaited<ReturnType<typeof rolesControllerCatalog>>, TError = unknown>(
 siteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesControllerCatalog>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRolesControllerCatalogQueryOptions(siteId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary List built-in + custom roles for this site
 */
export const rolesControllerList = (
    siteId: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/sites/${siteId}/roles`, method: 'GET', signal
    },
      );
    }




export const getRolesControllerListQueryKey = (siteId: string,) => {
    return [
    `/api/v1/sites/${siteId}/roles`
    ] as const;
    }


export const getRolesControllerListQueryOptions = <TData = Awaited<ReturnType<typeof rolesControllerList>>, TError = unknown>(siteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesControllerList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRolesControllerListQueryKey(siteId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof rolesControllerList>>> = ({ signal }) => rolesControllerList(siteId, signal);





   return  { queryKey, queryFn, enabled: siteId !== null && siteId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof rolesControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RolesControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof rolesControllerList>>>
export type RolesControllerListQueryError = unknown


export function useRolesControllerList<TData = Awaited<ReturnType<typeof rolesControllerList>>, TError = unknown>(
 siteId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolesControllerList>>,
          TError,
          Awaited<ReturnType<typeof rolesControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesControllerList<TData = Awaited<ReturnType<typeof rolesControllerList>>, TError = unknown>(
 siteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolesControllerList>>,
          TError,
          Awaited<ReturnType<typeof rolesControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesControllerList<TData = Awaited<ReturnType<typeof rolesControllerList>>, TError = unknown>(
 siteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List built-in + custom roles for this site
 */

export function useRolesControllerList<TData = Awaited<ReturnType<typeof rolesControllerList>>, TError = unknown>(
 siteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRolesControllerListQueryOptions(siteId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Create a custom role
 */
export const rolesControllerCreate = (
    siteId: string,
    createCustomRoleDto: CreateCustomRoleDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/sites/${siteId}/roles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCustomRoleDto, signal
    },
      );
    }




export const getRolesControllerCreateMutationKey = () => ['rolesControllerCreate'] as const;

export const getRolesControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rolesControllerCreate>>, TError,RolesControllerCreateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof rolesControllerCreate>>, TError,RolesControllerCreateMutationVariables, TContext> => {

const mutationKey = getRolesControllerCreateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rolesControllerCreate>>, RolesControllerCreateMutationVariables> = (props) => {
          const {siteId,data} = props ?? {};

          return  rolesControllerCreate(siteId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RolesControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof rolesControllerCreate>>>
    export type RolesControllerCreateMutationBody = CreateCustomRoleDto
    export type RolesControllerCreateMutationError = unknown
    export type RolesControllerCreateMutationVariables = {siteId: string;data: CreateCustomRoleDto}

    /**
 * @summary Create a custom role
 */
export const useRolesControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rolesControllerCreate>>, TError,RolesControllerCreateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rolesControllerCreate>>,
        TError,
        RolesControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getRolesControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary Update a custom role
 */
export const rolesControllerUpdate = (
    siteId: string,
    roleId: string,
    updateCustomRoleDto: UpdateCustomRoleDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/sites/${siteId}/roles/${roleId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCustomRoleDto, signal
    },
      );
    }




export const getRolesControllerUpdateMutationKey = () => ['rolesControllerUpdate'] as const;

export const getRolesControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rolesControllerUpdate>>, TError,RolesControllerUpdateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof rolesControllerUpdate>>, TError,RolesControllerUpdateMutationVariables, TContext> => {

const mutationKey = getRolesControllerUpdateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rolesControllerUpdate>>, RolesControllerUpdateMutationVariables> = (props) => {
          const {siteId,roleId,data} = props ?? {};

          return  rolesControllerUpdate(siteId,roleId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RolesControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof rolesControllerUpdate>>>
    export type RolesControllerUpdateMutationBody = UpdateCustomRoleDto
    export type RolesControllerUpdateMutationError = unknown
    export type RolesControllerUpdateMutationVariables = {siteId: string;roleId: string;data: UpdateCustomRoleDto}

    /**
 * @summary Update a custom role
 */
export const useRolesControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rolesControllerUpdate>>, TError,RolesControllerUpdateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rolesControllerUpdate>>,
        TError,
        RolesControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getRolesControllerUpdateMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a custom role
 */
export const rolesControllerRemove = (
    siteId: string,
    roleId: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/sites/${siteId}/roles/${roleId}`, method: 'DELETE', signal
    },
      );
    }




export const getRolesControllerRemoveMutationKey = () => ['rolesControllerRemove'] as const;

export const getRolesControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rolesControllerRemove>>, TError,RolesControllerRemoveMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof rolesControllerRemove>>, TError,RolesControllerRemoveMutationVariables, TContext> => {

const mutationKey = getRolesControllerRemoveMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rolesControllerRemove>>, RolesControllerRemoveMutationVariables> = (props) => {
          const {siteId,roleId} = props ?? {};

          return  rolesControllerRemove(siteId,roleId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RolesControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof rolesControllerRemove>>>

    export type RolesControllerRemoveMutationError = unknown
    export type RolesControllerRemoveMutationVariables = {siteId: string;roleId: string}

    /**
 * @summary Delete a custom role
 */
export const useRolesControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rolesControllerRemove>>, TError,RolesControllerRemoveMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rolesControllerRemove>>,
        TError,
        RolesControllerRemoveMutationVariables,
        TContext
      > => {
      return useMutation(getRolesControllerRemoveMutationOptions(options), queryClient);
    }
    /**
 * @summary Assign (or clear) a custom role for a member
 */
export const rolesControllerAssign = (
    siteId: string,
    userId: string,
    assignCustomRoleDto: AssignCustomRoleDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/sites/${siteId}/roles/members/${userId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: assignCustomRoleDto, signal
    },
      );
    }




export const getRolesControllerAssignMutationKey = () => ['rolesControllerAssign'] as const;

export const getRolesControllerAssignMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rolesControllerAssign>>, TError,RolesControllerAssignMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof rolesControllerAssign>>, TError,RolesControllerAssignMutationVariables, TContext> => {

const mutationKey = getRolesControllerAssignMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rolesControllerAssign>>, RolesControllerAssignMutationVariables> = (props) => {
          const {siteId,userId,data} = props ?? {};

          return  rolesControllerAssign(siteId,userId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RolesControllerAssignMutationResult = NonNullable<Awaited<ReturnType<typeof rolesControllerAssign>>>
    export type RolesControllerAssignMutationBody = AssignCustomRoleDto
    export type RolesControllerAssignMutationError = unknown
    export type RolesControllerAssignMutationVariables = {siteId: string;userId: string;data: AssignCustomRoleDto}

    /**
 * @summary Assign (or clear) a custom role for a member
 */
export const useRolesControllerAssign = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rolesControllerAssign>>, TError,RolesControllerAssignMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rolesControllerAssign>>,
        TError,
        RolesControllerAssignMutationVariables,
        TContext
      > => {
      return useMutation(getRolesControllerAssignMutationOptions(options), queryClient);
    }
