/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  UpdateSiteChromeDto
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Get the active site's global header + footer layouts
 */
export const siteChromeControllerGet = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/site-chrome`, method: 'GET', signal
    },
      );
    }




export const getSiteChromeControllerGetQueryKey = () => {
    return [
    `/api/v1/site-chrome`
    ] as const;
    }


export const getSiteChromeControllerGetQueryOptions = <TData = Awaited<ReturnType<typeof siteChromeControllerGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof siteChromeControllerGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSiteChromeControllerGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof siteChromeControllerGet>>> = ({ signal }) => siteChromeControllerGet(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof siteChromeControllerGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SiteChromeControllerGetQueryResult = NonNullable<Awaited<ReturnType<typeof siteChromeControllerGet>>>
export type SiteChromeControllerGetQueryError = unknown


export function useSiteChromeControllerGet<TData = Awaited<ReturnType<typeof siteChromeControllerGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof siteChromeControllerGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof siteChromeControllerGet>>,
          TError,
          Awaited<ReturnType<typeof siteChromeControllerGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSiteChromeControllerGet<TData = Awaited<ReturnType<typeof siteChromeControllerGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof siteChromeControllerGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof siteChromeControllerGet>>,
          TError,
          Awaited<ReturnType<typeof siteChromeControllerGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSiteChromeControllerGet<TData = Awaited<ReturnType<typeof siteChromeControllerGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof siteChromeControllerGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get the active site's global header + footer layouts
 */

export function useSiteChromeControllerGet<TData = Awaited<ReturnType<typeof siteChromeControllerGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof siteChromeControllerGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSiteChromeControllerGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Save the global header and/or footer (save = live; purges cache)
 */
export const siteChromeControllerUpdate = (
    updateSiteChromeDto: UpdateSiteChromeDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/site-chrome`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateSiteChromeDto, signal
    },
      );
    }




export const getSiteChromeControllerUpdateMutationKey = () => ['siteChromeControllerUpdate'] as const;

export const getSiteChromeControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof siteChromeControllerUpdate>>, TError,SiteChromeControllerUpdateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof siteChromeControllerUpdate>>, TError,SiteChromeControllerUpdateMutationVariables, TContext> => {

const mutationKey = getSiteChromeControllerUpdateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof siteChromeControllerUpdate>>, SiteChromeControllerUpdateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  siteChromeControllerUpdate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SiteChromeControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof siteChromeControllerUpdate>>>
    export type SiteChromeControllerUpdateMutationBody = UpdateSiteChromeDto
    export type SiteChromeControllerUpdateMutationError = unknown
    export type SiteChromeControllerUpdateMutationVariables = {data: UpdateSiteChromeDto}

    /**
 * @summary Save the global header and/or footer (save = live; purges cache)
 */
export const useSiteChromeControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof siteChromeControllerUpdate>>, TError,SiteChromeControllerUpdateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof siteChromeControllerUpdate>>,
        TError,
        SiteChromeControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getSiteChromeControllerUpdateMutationOptions(options), queryClient);
    }
