/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddMemberDto,
  UpdateRoleDto
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List members of this site
 */
export const siteMembersControllerList = (
    siteId: unknown,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/sites/${siteId}/members`, method: 'GET', signal
    },
      );
    }




export const getSiteMembersControllerListQueryKey = (siteId: unknown,) => {
    return [
    `/api/v1/sites/${siteId}/members`
    ] as const;
    }


export const getSiteMembersControllerListQueryOptions = <TData = Awaited<ReturnType<typeof siteMembersControllerList>>, TError = unknown>(siteId: unknown, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof siteMembersControllerList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSiteMembersControllerListQueryKey(siteId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof siteMembersControllerList>>> = ({ signal }) => siteMembersControllerList(siteId, signal);





   return  { queryKey, queryFn, enabled: siteId != null && siteId !== '', ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof siteMembersControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SiteMembersControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof siteMembersControllerList>>>
export type SiteMembersControllerListQueryError = unknown


export function useSiteMembersControllerList<TData = Awaited<ReturnType<typeof siteMembersControllerList>>, TError = unknown>(
 siteId: unknown, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof siteMembersControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof siteMembersControllerList>>,
          TError,
          Awaited<ReturnType<typeof siteMembersControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSiteMembersControllerList<TData = Awaited<ReturnType<typeof siteMembersControllerList>>, TError = unknown>(
 siteId: unknown, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof siteMembersControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof siteMembersControllerList>>,
          TError,
          Awaited<ReturnType<typeof siteMembersControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSiteMembersControllerList<TData = Awaited<ReturnType<typeof siteMembersControllerList>>, TError = unknown>(
 siteId: unknown, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof siteMembersControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List members of this site
 */

export function useSiteMembersControllerList<TData = Awaited<ReturnType<typeof siteMembersControllerList>>, TError = unknown>(
 siteId: unknown, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof siteMembersControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSiteMembersControllerListQueryOptions(siteId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Add an existing user as a member
 */
export const siteMembersControllerAdd = (
    siteId: unknown,
    addMemberDto: AddMemberDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/sites/${siteId}/members`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addMemberDto, signal
    },
      );
    }




export const getSiteMembersControllerAddMutationKey = () => ['siteMembersControllerAdd'] as const;

export const getSiteMembersControllerAddMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof siteMembersControllerAdd>>, TError,SiteMembersControllerAddMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof siteMembersControllerAdd>>, TError,SiteMembersControllerAddMutationVariables, TContext> => {

const mutationKey = getSiteMembersControllerAddMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof siteMembersControllerAdd>>, SiteMembersControllerAddMutationVariables> = (props) => {
          const {siteId,data} = props ?? {};

          return  siteMembersControllerAdd(siteId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SiteMembersControllerAddMutationResult = NonNullable<Awaited<ReturnType<typeof siteMembersControllerAdd>>>
    export type SiteMembersControllerAddMutationBody = AddMemberDto
    export type SiteMembersControllerAddMutationError = unknown
    export type SiteMembersControllerAddMutationVariables = {siteId: unknown;data: AddMemberDto}

    /**
 * @summary Add an existing user as a member
 */
export const useSiteMembersControllerAdd = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof siteMembersControllerAdd>>, TError,SiteMembersControllerAddMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof siteMembersControllerAdd>>,
        TError,
        SiteMembersControllerAddMutationVariables,
        TContext
      > => {
      return useMutation(getSiteMembersControllerAddMutationOptions(options), queryClient);
    }
    /**
 * @summary Change a member's role
 */
export const siteMembersControllerUpdateRole = (
    siteId: unknown,
    userId: string,
    updateRoleDto: UpdateRoleDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/sites/${siteId}/members/${userId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateRoleDto, signal
    },
      );
    }




export const getSiteMembersControllerUpdateRoleMutationKey = () => ['siteMembersControllerUpdateRole'] as const;

export const getSiteMembersControllerUpdateRoleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof siteMembersControllerUpdateRole>>, TError,SiteMembersControllerUpdateRoleMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof siteMembersControllerUpdateRole>>, TError,SiteMembersControllerUpdateRoleMutationVariables, TContext> => {

const mutationKey = getSiteMembersControllerUpdateRoleMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof siteMembersControllerUpdateRole>>, SiteMembersControllerUpdateRoleMutationVariables> = (props) => {
          const {siteId,userId,data} = props ?? {};

          return  siteMembersControllerUpdateRole(siteId,userId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SiteMembersControllerUpdateRoleMutationResult = NonNullable<Awaited<ReturnType<typeof siteMembersControllerUpdateRole>>>
    export type SiteMembersControllerUpdateRoleMutationBody = UpdateRoleDto
    export type SiteMembersControllerUpdateRoleMutationError = unknown
    export type SiteMembersControllerUpdateRoleMutationVariables = {siteId: unknown;userId: string;data: UpdateRoleDto}

    /**
 * @summary Change a member's role
 */
export const useSiteMembersControllerUpdateRole = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof siteMembersControllerUpdateRole>>, TError,SiteMembersControllerUpdateRoleMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof siteMembersControllerUpdateRole>>,
        TError,
        SiteMembersControllerUpdateRoleMutationVariables,
        TContext
      > => {
      return useMutation(getSiteMembersControllerUpdateRoleMutationOptions(options), queryClient);
    }
    /**
 * @summary Remove a member
 */
export const siteMembersControllerRemove = (
    siteId: unknown,
    userId: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/sites/${siteId}/members/${userId}`, method: 'DELETE', signal
    },
      );
    }




export const getSiteMembersControllerRemoveMutationKey = () => ['siteMembersControllerRemove'] as const;

export const getSiteMembersControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof siteMembersControllerRemove>>, TError,SiteMembersControllerRemoveMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof siteMembersControllerRemove>>, TError,SiteMembersControllerRemoveMutationVariables, TContext> => {

const mutationKey = getSiteMembersControllerRemoveMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof siteMembersControllerRemove>>, SiteMembersControllerRemoveMutationVariables> = (props) => {
          const {siteId,userId} = props ?? {};

          return  siteMembersControllerRemove(siteId,userId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SiteMembersControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof siteMembersControllerRemove>>>

    export type SiteMembersControllerRemoveMutationError = unknown
    export type SiteMembersControllerRemoveMutationVariables = {siteId: unknown;userId: string}

    /**
 * @summary Remove a member
 */
export const useSiteMembersControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof siteMembersControllerRemove>>, TError,SiteMembersControllerRemoveMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof siteMembersControllerRemove>>,
        TError,
        SiteMembersControllerRemoveMutationVariables,
        TContext
      > => {
      return useMutation(getSiteMembersControllerRemoveMutationOptions(options), queryClient);
    }
