/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  TemplateSkeletonsControllerListParams
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List template skeletons (catalog filters)
 */
export const templateSkeletonsControllerList = (
    params?: TemplateSkeletonsControllerListParams,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/template-skeletons`, method: 'GET',
        params, signal
    },
      );
    }




export const getTemplateSkeletonsControllerListQueryKey = (params?: TemplateSkeletonsControllerListParams,) => {
    return [
    `/api/v1/template-skeletons`, ...(params ? [params] : [])
    ] as const;
    }


export const getTemplateSkeletonsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof templateSkeletonsControllerList>>, TError = unknown>(params?: TemplateSkeletonsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTemplateSkeletonsControllerListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof templateSkeletonsControllerList>>> = ({ signal }) => templateSkeletonsControllerList(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TemplateSkeletonsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof templateSkeletonsControllerList>>>
export type TemplateSkeletonsControllerListQueryError = unknown


export function useTemplateSkeletonsControllerList<TData = Awaited<ReturnType<typeof templateSkeletonsControllerList>>, TError = unknown>(
 params: undefined |  TemplateSkeletonsControllerListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateSkeletonsControllerList>>,
          TError,
          Awaited<ReturnType<typeof templateSkeletonsControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateSkeletonsControllerList<TData = Awaited<ReturnType<typeof templateSkeletonsControllerList>>, TError = unknown>(
 params?: TemplateSkeletonsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateSkeletonsControllerList>>,
          TError,
          Awaited<ReturnType<typeof templateSkeletonsControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateSkeletonsControllerList<TData = Awaited<ReturnType<typeof templateSkeletonsControllerList>>, TError = unknown>(
 params?: TemplateSkeletonsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List template skeletons (catalog filters)
 */

export function useTemplateSkeletonsControllerList<TData = Awaited<ReturnType<typeof templateSkeletonsControllerList>>, TError = unknown>(
 params?: TemplateSkeletonsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTemplateSkeletonsControllerListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Create a template skeleton (platform admin only)
 */
export const templateSkeletonsControllerCreate = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/template-skeletons`, method: 'POST', signal
    },
      );
    }




export const getTemplateSkeletonsControllerCreateMutationKey = () => ['templateSkeletonsControllerCreate'] as const;

export const getTemplateSkeletonsControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerCreate>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerCreate>>, TError,void, TContext> => {

const mutationKey = getTemplateSkeletonsControllerCreateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof templateSkeletonsControllerCreate>>, void> = () => {


          return  templateSkeletonsControllerCreate()
        }






  return  { mutationFn, ...mutationOptions }}

    export type TemplateSkeletonsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof templateSkeletonsControllerCreate>>>

    export type TemplateSkeletonsControllerCreateMutationError = unknown


    /**
 * @summary Create a template skeleton (platform admin only)
 */
export const useTemplateSkeletonsControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerCreate>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof templateSkeletonsControllerCreate>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getTemplateSkeletonsControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary Fetch a template skeleton by stable registry key
 */
export const templateSkeletonsControllerGetByKey = (
    templateKey: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/template-skeletons/by-key/${templateKey}`, method: 'GET', signal
    },
      );
    }




export const getTemplateSkeletonsControllerGetByKeyQueryKey = (templateKey: string,) => {
    return [
    `/api/v1/template-skeletons/by-key/${templateKey}`
    ] as const;
    }


export const getTemplateSkeletonsControllerGetByKeyQueryOptions = <TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetByKey>>, TError = unknown>(templateKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetByKey>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTemplateSkeletonsControllerGetByKeyQueryKey(templateKey);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof templateSkeletonsControllerGetByKey>>> = ({ signal }) => templateSkeletonsControllerGetByKey(templateKey, signal);





   return  { queryKey, queryFn, enabled: templateKey !== null && templateKey !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetByKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TemplateSkeletonsControllerGetByKeyQueryResult = NonNullable<Awaited<ReturnType<typeof templateSkeletonsControllerGetByKey>>>
export type TemplateSkeletonsControllerGetByKeyQueryError = unknown


export function useTemplateSkeletonsControllerGetByKey<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetByKey>>, TError = unknown>(
 templateKey: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetByKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateSkeletonsControllerGetByKey>>,
          TError,
          Awaited<ReturnType<typeof templateSkeletonsControllerGetByKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateSkeletonsControllerGetByKey<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetByKey>>, TError = unknown>(
 templateKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetByKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateSkeletonsControllerGetByKey>>,
          TError,
          Awaited<ReturnType<typeof templateSkeletonsControllerGetByKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateSkeletonsControllerGetByKey<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetByKey>>, TError = unknown>(
 templateKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetByKey>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch a template skeleton by stable registry key
 */

export function useTemplateSkeletonsControllerGetByKey<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetByKey>>, TError = unknown>(
 templateKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetByKey>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTemplateSkeletonsControllerGetByKeyQueryOptions(templateKey,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Most-used starter templates on the active site
 */
export const templateSkeletonsControllerGetTopUsage = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/template-skeletons/analytics/top`, method: 'GET', signal
    },
      );
    }




export const getTemplateSkeletonsControllerGetTopUsageQueryKey = () => {
    return [
    `/api/v1/template-skeletons/analytics/top`
    ] as const;
    }


export const getTemplateSkeletonsControllerGetTopUsageQueryOptions = <TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetTopUsage>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetTopUsage>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTemplateSkeletonsControllerGetTopUsageQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof templateSkeletonsControllerGetTopUsage>>> = ({ signal }) => templateSkeletonsControllerGetTopUsage(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetTopUsage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TemplateSkeletonsControllerGetTopUsageQueryResult = NonNullable<Awaited<ReturnType<typeof templateSkeletonsControllerGetTopUsage>>>
export type TemplateSkeletonsControllerGetTopUsageQueryError = unknown


export function useTemplateSkeletonsControllerGetTopUsage<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetTopUsage>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetTopUsage>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateSkeletonsControllerGetTopUsage>>,
          TError,
          Awaited<ReturnType<typeof templateSkeletonsControllerGetTopUsage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateSkeletonsControllerGetTopUsage<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetTopUsage>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetTopUsage>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateSkeletonsControllerGetTopUsage>>,
          TError,
          Awaited<ReturnType<typeof templateSkeletonsControllerGetTopUsage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateSkeletonsControllerGetTopUsage<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetTopUsage>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetTopUsage>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Most-used starter templates on the active site
 */

export function useTemplateSkeletonsControllerGetTopUsage<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetTopUsage>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetTopUsage>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTemplateSkeletonsControllerGetTopUsageQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary List immutable version snapshots for a template skeleton
 */
export const templateSkeletonsControllerListHistory = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/template-skeletons/${id}/history`, method: 'GET', signal
    },
      );
    }




export const getTemplateSkeletonsControllerListHistoryQueryKey = (id: string,) => {
    return [
    `/api/v1/template-skeletons/${id}/history`
    ] as const;
    }


export const getTemplateSkeletonsControllerListHistoryQueryOptions = <TData = Awaited<ReturnType<typeof templateSkeletonsControllerListHistory>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerListHistory>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTemplateSkeletonsControllerListHistoryQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof templateSkeletonsControllerListHistory>>> = ({ signal }) => templateSkeletonsControllerListHistory(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerListHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TemplateSkeletonsControllerListHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof templateSkeletonsControllerListHistory>>>
export type TemplateSkeletonsControllerListHistoryQueryError = unknown


export function useTemplateSkeletonsControllerListHistory<TData = Awaited<ReturnType<typeof templateSkeletonsControllerListHistory>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerListHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateSkeletonsControllerListHistory>>,
          TError,
          Awaited<ReturnType<typeof templateSkeletonsControllerListHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateSkeletonsControllerListHistory<TData = Awaited<ReturnType<typeof templateSkeletonsControllerListHistory>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerListHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateSkeletonsControllerListHistory>>,
          TError,
          Awaited<ReturnType<typeof templateSkeletonsControllerListHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateSkeletonsControllerListHistory<TData = Awaited<ReturnType<typeof templateSkeletonsControllerListHistory>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerListHistory>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List immutable version snapshots for a template skeleton
 */

export function useTemplateSkeletonsControllerListHistory<TData = Awaited<ReturnType<typeof templateSkeletonsControllerListHistory>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerListHistory>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTemplateSkeletonsControllerListHistoryQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Fetch a specific template skeleton version snapshot
 */
export const templateSkeletonsControllerGetHistoryVersion = (
    id: string,
    version: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/template-skeletons/${id}/history/${version}`, method: 'GET', signal
    },
      );
    }




export const getTemplateSkeletonsControllerGetHistoryVersionQueryKey = (id: string,
    version: string,) => {
    return [
    `/api/v1/template-skeletons/${id}/history/${version}`
    ] as const;
    }


export const getTemplateSkeletonsControllerGetHistoryVersionQueryOptions = <TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetHistoryVersion>>, TError = unknown>(id: string,
    version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetHistoryVersion>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTemplateSkeletonsControllerGetHistoryVersionQueryKey(id,version);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof templateSkeletonsControllerGetHistoryVersion>>> = ({ signal }) => templateSkeletonsControllerGetHistoryVersion(id,version, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && version !== null && version !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetHistoryVersion>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TemplateSkeletonsControllerGetHistoryVersionQueryResult = NonNullable<Awaited<ReturnType<typeof templateSkeletonsControllerGetHistoryVersion>>>
export type TemplateSkeletonsControllerGetHistoryVersionQueryError = unknown


export function useTemplateSkeletonsControllerGetHistoryVersion<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetHistoryVersion>>, TError = unknown>(
 id: string,
    version: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetHistoryVersion>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateSkeletonsControllerGetHistoryVersion>>,
          TError,
          Awaited<ReturnType<typeof templateSkeletonsControllerGetHistoryVersion>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateSkeletonsControllerGetHistoryVersion<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetHistoryVersion>>, TError = unknown>(
 id: string,
    version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetHistoryVersion>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateSkeletonsControllerGetHistoryVersion>>,
          TError,
          Awaited<ReturnType<typeof templateSkeletonsControllerGetHistoryVersion>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateSkeletonsControllerGetHistoryVersion<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetHistoryVersion>>, TError = unknown>(
 id: string,
    version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetHistoryVersion>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch a specific template skeleton version snapshot
 */

export function useTemplateSkeletonsControllerGetHistoryVersion<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetHistoryVersion>>, TError = unknown>(
 id: string,
    version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetHistoryVersion>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTemplateSkeletonsControllerGetHistoryVersionQueryOptions(id,version,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Template usage analytics for a starter skeleton
 */
export const templateSkeletonsControllerGetUsage = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/template-skeletons/${id}/usage`, method: 'GET', signal
    },
      );
    }




export const getTemplateSkeletonsControllerGetUsageQueryKey = (id: string,) => {
    return [
    `/api/v1/template-skeletons/${id}/usage`
    ] as const;
    }


export const getTemplateSkeletonsControllerGetUsageQueryOptions = <TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetUsage>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetUsage>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTemplateSkeletonsControllerGetUsageQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof templateSkeletonsControllerGetUsage>>> = ({ signal }) => templateSkeletonsControllerGetUsage(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetUsage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TemplateSkeletonsControllerGetUsageQueryResult = NonNullable<Awaited<ReturnType<typeof templateSkeletonsControllerGetUsage>>>
export type TemplateSkeletonsControllerGetUsageQueryError = unknown


export function useTemplateSkeletonsControllerGetUsage<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetUsage>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetUsage>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateSkeletonsControllerGetUsage>>,
          TError,
          Awaited<ReturnType<typeof templateSkeletonsControllerGetUsage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateSkeletonsControllerGetUsage<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetUsage>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetUsage>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateSkeletonsControllerGetUsage>>,
          TError,
          Awaited<ReturnType<typeof templateSkeletonsControllerGetUsage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateSkeletonsControllerGetUsage<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetUsage>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetUsage>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Template usage analytics for a starter skeleton
 */

export function useTemplateSkeletonsControllerGetUsage<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetUsage>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetUsage>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTemplateSkeletonsControllerGetUsageQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Fetch a template skeleton by id
 */
export const templateSkeletonsControllerGetById = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/template-skeletons/${id}`, method: 'GET', signal
    },
      );
    }




export const getTemplateSkeletonsControllerGetByIdQueryKey = (id: string,) => {
    return [
    `/api/v1/template-skeletons/${id}`
    ] as const;
    }


export const getTemplateSkeletonsControllerGetByIdQueryOptions = <TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTemplateSkeletonsControllerGetByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof templateSkeletonsControllerGetById>>> = ({ signal }) => templateSkeletonsControllerGetById(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TemplateSkeletonsControllerGetByIdQueryResult = NonNullable<Awaited<ReturnType<typeof templateSkeletonsControllerGetById>>>
export type TemplateSkeletonsControllerGetByIdQueryError = unknown


export function useTemplateSkeletonsControllerGetById<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateSkeletonsControllerGetById>>,
          TError,
          Awaited<ReturnType<typeof templateSkeletonsControllerGetById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateSkeletonsControllerGetById<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateSkeletonsControllerGetById>>,
          TError,
          Awaited<ReturnType<typeof templateSkeletonsControllerGetById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateSkeletonsControllerGetById<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch a template skeleton by id
 */

export function useTemplateSkeletonsControllerGetById<TData = Awaited<ReturnType<typeof templateSkeletonsControllerGetById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerGetById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTemplateSkeletonsControllerGetByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Update template skeleton metadata and/or content
 */
export const templateSkeletonsControllerUpdate = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/template-skeletons/${id}`, method: 'PATCH', signal
    },
      );
    }




export const getTemplateSkeletonsControllerUpdateMutationKey = () => ['templateSkeletonsControllerUpdate'] as const;

export const getTemplateSkeletonsControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerUpdate>>, TError,TemplateSkeletonsControllerUpdateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerUpdate>>, TError,TemplateSkeletonsControllerUpdateMutationVariables, TContext> => {

const mutationKey = getTemplateSkeletonsControllerUpdateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof templateSkeletonsControllerUpdate>>, TemplateSkeletonsControllerUpdateMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  templateSkeletonsControllerUpdate(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TemplateSkeletonsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof templateSkeletonsControllerUpdate>>>

    export type TemplateSkeletonsControllerUpdateMutationError = unknown
    export type TemplateSkeletonsControllerUpdateMutationVariables = {id: string}

    /**
 * @summary Update template skeleton metadata and/or content
 */
export const useTemplateSkeletonsControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerUpdate>>, TError,TemplateSkeletonsControllerUpdateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof templateSkeletonsControllerUpdate>>,
        TError,
        TemplateSkeletonsControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getTemplateSkeletonsControllerUpdateMutationOptions(options), queryClient);
    }
    /**
 * @summary Soft-delete a template skeleton
 */
export const templateSkeletonsControllerRemove = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/template-skeletons/${id}`, method: 'DELETE', signal
    },
      );
    }




export const getTemplateSkeletonsControllerRemoveMutationKey = () => ['templateSkeletonsControllerRemove'] as const;

export const getTemplateSkeletonsControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerRemove>>, TError,TemplateSkeletonsControllerRemoveMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerRemove>>, TError,TemplateSkeletonsControllerRemoveMutationVariables, TContext> => {

const mutationKey = getTemplateSkeletonsControllerRemoveMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof templateSkeletonsControllerRemove>>, TemplateSkeletonsControllerRemoveMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  templateSkeletonsControllerRemove(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TemplateSkeletonsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof templateSkeletonsControllerRemove>>>

    export type TemplateSkeletonsControllerRemoveMutationError = unknown
    export type TemplateSkeletonsControllerRemoveMutationVariables = {id: string}

    /**
 * @summary Soft-delete a template skeleton
 */
export const useTemplateSkeletonsControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerRemove>>, TError,TemplateSkeletonsControllerRemoveMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof templateSkeletonsControllerRemove>>,
        TError,
        TemplateSkeletonsControllerRemoveMutationVariables,
        TContext
      > => {
      return useMutation(getTemplateSkeletonsControllerRemoveMutationOptions(options), queryClient);
    }
    /**
 * @summary List preview assets for a template skeleton
 */
export const templateSkeletonsControllerListAssets = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/template-skeletons/${id}/assets`, method: 'GET', signal
    },
      );
    }




export const getTemplateSkeletonsControllerListAssetsQueryKey = (id: string,) => {
    return [
    `/api/v1/template-skeletons/${id}/assets`
    ] as const;
    }


export const getTemplateSkeletonsControllerListAssetsQueryOptions = <TData = Awaited<ReturnType<typeof templateSkeletonsControllerListAssets>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerListAssets>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTemplateSkeletonsControllerListAssetsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof templateSkeletonsControllerListAssets>>> = ({ signal }) => templateSkeletonsControllerListAssets(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerListAssets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TemplateSkeletonsControllerListAssetsQueryResult = NonNullable<Awaited<ReturnType<typeof templateSkeletonsControllerListAssets>>>
export type TemplateSkeletonsControllerListAssetsQueryError = unknown


export function useTemplateSkeletonsControllerListAssets<TData = Awaited<ReturnType<typeof templateSkeletonsControllerListAssets>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerListAssets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateSkeletonsControllerListAssets>>,
          TError,
          Awaited<ReturnType<typeof templateSkeletonsControllerListAssets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateSkeletonsControllerListAssets<TData = Awaited<ReturnType<typeof templateSkeletonsControllerListAssets>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerListAssets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateSkeletonsControllerListAssets>>,
          TError,
          Awaited<ReturnType<typeof templateSkeletonsControllerListAssets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateSkeletonsControllerListAssets<TData = Awaited<ReturnType<typeof templateSkeletonsControllerListAssets>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerListAssets>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List preview assets for a template skeleton
 */

export function useTemplateSkeletonsControllerListAssets<TData = Awaited<ReturnType<typeof templateSkeletonsControllerListAssets>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateSkeletonsControllerListAssets>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTemplateSkeletonsControllerListAssetsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Attach a preview asset reference to a skeleton
 */
export const templateSkeletonsControllerCreateAsset = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/template-skeletons/${id}/assets`, method: 'POST', signal
    },
      );
    }




export const getTemplateSkeletonsControllerCreateAssetMutationKey = () => ['templateSkeletonsControllerCreateAsset'] as const;

export const getTemplateSkeletonsControllerCreateAssetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerCreateAsset>>, TError,TemplateSkeletonsControllerCreateAssetMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerCreateAsset>>, TError,TemplateSkeletonsControllerCreateAssetMutationVariables, TContext> => {

const mutationKey = getTemplateSkeletonsControllerCreateAssetMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof templateSkeletonsControllerCreateAsset>>, TemplateSkeletonsControllerCreateAssetMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  templateSkeletonsControllerCreateAsset(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TemplateSkeletonsControllerCreateAssetMutationResult = NonNullable<Awaited<ReturnType<typeof templateSkeletonsControllerCreateAsset>>>

    export type TemplateSkeletonsControllerCreateAssetMutationError = unknown
    export type TemplateSkeletonsControllerCreateAssetMutationVariables = {id: string}

    /**
 * @summary Attach a preview asset reference to a skeleton
 */
export const useTemplateSkeletonsControllerCreateAsset = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerCreateAsset>>, TError,TemplateSkeletonsControllerCreateAssetMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof templateSkeletonsControllerCreateAsset>>,
        TError,
        TemplateSkeletonsControllerCreateAssetMutationVariables,
        TContext
      > => {
      return useMutation(getTemplateSkeletonsControllerCreateAssetMutationOptions(options), queryClient);
    }
    /**
 * @summary Update a preview asset reference
 */
export const templateSkeletonsControllerUpdateAsset = (
    id: string,
    assetId: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/template-skeletons/${id}/assets/${assetId}`, method: 'PATCH', signal
    },
      );
    }




export const getTemplateSkeletonsControllerUpdateAssetMutationKey = () => ['templateSkeletonsControllerUpdateAsset'] as const;

export const getTemplateSkeletonsControllerUpdateAssetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerUpdateAsset>>, TError,TemplateSkeletonsControllerUpdateAssetMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerUpdateAsset>>, TError,TemplateSkeletonsControllerUpdateAssetMutationVariables, TContext> => {

const mutationKey = getTemplateSkeletonsControllerUpdateAssetMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof templateSkeletonsControllerUpdateAsset>>, TemplateSkeletonsControllerUpdateAssetMutationVariables> = (props) => {
          const {id,assetId} = props ?? {};

          return  templateSkeletonsControllerUpdateAsset(id,assetId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TemplateSkeletonsControllerUpdateAssetMutationResult = NonNullable<Awaited<ReturnType<typeof templateSkeletonsControllerUpdateAsset>>>

    export type TemplateSkeletonsControllerUpdateAssetMutationError = unknown
    export type TemplateSkeletonsControllerUpdateAssetMutationVariables = {id: string;assetId: string}

    /**
 * @summary Update a preview asset reference
 */
export const useTemplateSkeletonsControllerUpdateAsset = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerUpdateAsset>>, TError,TemplateSkeletonsControllerUpdateAssetMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof templateSkeletonsControllerUpdateAsset>>,
        TError,
        TemplateSkeletonsControllerUpdateAssetMutationVariables,
        TContext
      > => {
      return useMutation(getTemplateSkeletonsControllerUpdateAssetMutationOptions(options), queryClient);
    }
    /**
 * @summary Remove a preview asset reference
 */
export const templateSkeletonsControllerRemoveAsset = (
    id: string,
    assetId: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/template-skeletons/${id}/assets/${assetId}`, method: 'DELETE', signal
    },
      );
    }




export const getTemplateSkeletonsControllerRemoveAssetMutationKey = () => ['templateSkeletonsControllerRemoveAsset'] as const;

export const getTemplateSkeletonsControllerRemoveAssetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerRemoveAsset>>, TError,TemplateSkeletonsControllerRemoveAssetMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerRemoveAsset>>, TError,TemplateSkeletonsControllerRemoveAssetMutationVariables, TContext> => {

const mutationKey = getTemplateSkeletonsControllerRemoveAssetMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof templateSkeletonsControllerRemoveAsset>>, TemplateSkeletonsControllerRemoveAssetMutationVariables> = (props) => {
          const {id,assetId} = props ?? {};

          return  templateSkeletonsControllerRemoveAsset(id,assetId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TemplateSkeletonsControllerRemoveAssetMutationResult = NonNullable<Awaited<ReturnType<typeof templateSkeletonsControllerRemoveAsset>>>

    export type TemplateSkeletonsControllerRemoveAssetMutationError = unknown
    export type TemplateSkeletonsControllerRemoveAssetMutationVariables = {id: string;assetId: string}

    /**
 * @summary Remove a preview asset reference
 */
export const useTemplateSkeletonsControllerRemoveAsset = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateSkeletonsControllerRemoveAsset>>, TError,TemplateSkeletonsControllerRemoveAssetMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof templateSkeletonsControllerRemoveAsset>>,
        TError,
        TemplateSkeletonsControllerRemoveAssetMutationVariables,
        TContext
      > => {
      return useMutation(getTemplateSkeletonsControllerRemoveAssetMutationOptions(options), queryClient);
    }
