/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OB-CMS API
 * Multi-tenant CMS API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateWebhookDto,
  UpdateWebhookDto
} from './obCmsApi.schemas';

import { request } from '../services/AxiosService';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const webhooksControllerList = (

 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/webhooks`, method: 'GET', signal
    },
      );
    }




export const getWebhooksControllerListQueryKey = () => {
    return [
    `/api/v1/webhooks`
    ] as const;
    }


export const getWebhooksControllerListQueryOptions = <TData = Awaited<ReturnType<typeof webhooksControllerList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhooksControllerList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWebhooksControllerListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof webhooksControllerList>>> = ({ signal }) => webhooksControllerList(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof webhooksControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WebhooksControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof webhooksControllerList>>>
export type WebhooksControllerListQueryError = unknown


export function useWebhooksControllerList<TData = Awaited<ReturnType<typeof webhooksControllerList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhooksControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof webhooksControllerList>>,
          TError,
          Awaited<ReturnType<typeof webhooksControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWebhooksControllerList<TData = Awaited<ReturnType<typeof webhooksControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhooksControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof webhooksControllerList>>,
          TError,
          Awaited<ReturnType<typeof webhooksControllerList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWebhooksControllerList<TData = Awaited<ReturnType<typeof webhooksControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhooksControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useWebhooksControllerList<TData = Awaited<ReturnType<typeof webhooksControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhooksControllerList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWebhooksControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const webhooksControllerCreate = (
    createWebhookDto: CreateWebhookDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/webhooks`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWebhookDto, signal
    },
      );
    }




export const getWebhooksControllerCreateMutationKey = () => ['webhooksControllerCreate'] as const;

export const getWebhooksControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhooksControllerCreate>>, TError,WebhooksControllerCreateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof webhooksControllerCreate>>, TError,WebhooksControllerCreateMutationVariables, TContext> => {

const mutationKey = getWebhooksControllerCreateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof webhooksControllerCreate>>, WebhooksControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  webhooksControllerCreate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WebhooksControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof webhooksControllerCreate>>>
    export type WebhooksControllerCreateMutationBody = CreateWebhookDto
    export type WebhooksControllerCreateMutationError = unknown
    export type WebhooksControllerCreateMutationVariables = {data: CreateWebhookDto}

    export const useWebhooksControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhooksControllerCreate>>, TError,WebhooksControllerCreateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof webhooksControllerCreate>>,
        TError,
        WebhooksControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getWebhooksControllerCreateMutationOptions(options), queryClient);
    }
    export const webhooksControllerUpdate = (
    id: string,
    updateWebhookDto: UpdateWebhookDto,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/webhooks/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateWebhookDto, signal
    },
      );
    }




export const getWebhooksControllerUpdateMutationKey = () => ['webhooksControllerUpdate'] as const;

export const getWebhooksControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhooksControllerUpdate>>, TError,WebhooksControllerUpdateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof webhooksControllerUpdate>>, TError,WebhooksControllerUpdateMutationVariables, TContext> => {

const mutationKey = getWebhooksControllerUpdateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof webhooksControllerUpdate>>, WebhooksControllerUpdateMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  webhooksControllerUpdate(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WebhooksControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof webhooksControllerUpdate>>>
    export type WebhooksControllerUpdateMutationBody = UpdateWebhookDto
    export type WebhooksControllerUpdateMutationError = unknown
    export type WebhooksControllerUpdateMutationVariables = {id: string;data: UpdateWebhookDto}

    export const useWebhooksControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhooksControllerUpdate>>, TError,WebhooksControllerUpdateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof webhooksControllerUpdate>>,
        TError,
        WebhooksControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getWebhooksControllerUpdateMutationOptions(options), queryClient);
    }
    export const webhooksControllerRemove = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/webhooks/${id}`, method: 'DELETE', signal
    },
      );
    }




export const getWebhooksControllerRemoveMutationKey = () => ['webhooksControllerRemove'] as const;

export const getWebhooksControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhooksControllerRemove>>, TError,WebhooksControllerRemoveMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof webhooksControllerRemove>>, TError,WebhooksControllerRemoveMutationVariables, TContext> => {

const mutationKey = getWebhooksControllerRemoveMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof webhooksControllerRemove>>, WebhooksControllerRemoveMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  webhooksControllerRemove(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WebhooksControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof webhooksControllerRemove>>>

    export type WebhooksControllerRemoveMutationError = unknown
    export type WebhooksControllerRemoveMutationVariables = {id: string}

    export const useWebhooksControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhooksControllerRemove>>, TError,WebhooksControllerRemoveMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof webhooksControllerRemove>>,
        TError,
        WebhooksControllerRemoveMutationVariables,
        TContext
      > => {
      return useMutation(getWebhooksControllerRemoveMutationOptions(options), queryClient);
    }
    export const webhooksControllerDeliveries = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/webhooks/${id}/deliveries`, method: 'GET', signal
    },
      );
    }




export const getWebhooksControllerDeliveriesQueryKey = (id: string,) => {
    return [
    `/api/v1/webhooks/${id}/deliveries`
    ] as const;
    }


export const getWebhooksControllerDeliveriesQueryOptions = <TData = Awaited<ReturnType<typeof webhooksControllerDeliveries>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhooksControllerDeliveries>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWebhooksControllerDeliveriesQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof webhooksControllerDeliveries>>> = ({ signal }) => webhooksControllerDeliveries(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof webhooksControllerDeliveries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WebhooksControllerDeliveriesQueryResult = NonNullable<Awaited<ReturnType<typeof webhooksControllerDeliveries>>>
export type WebhooksControllerDeliveriesQueryError = unknown


export function useWebhooksControllerDeliveries<TData = Awaited<ReturnType<typeof webhooksControllerDeliveries>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhooksControllerDeliveries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof webhooksControllerDeliveries>>,
          TError,
          Awaited<ReturnType<typeof webhooksControllerDeliveries>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWebhooksControllerDeliveries<TData = Awaited<ReturnType<typeof webhooksControllerDeliveries>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhooksControllerDeliveries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof webhooksControllerDeliveries>>,
          TError,
          Awaited<ReturnType<typeof webhooksControllerDeliveries>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWebhooksControllerDeliveries<TData = Awaited<ReturnType<typeof webhooksControllerDeliveries>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhooksControllerDeliveries>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useWebhooksControllerDeliveries<TData = Awaited<ReturnType<typeof webhooksControllerDeliveries>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhooksControllerDeliveries>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWebhooksControllerDeliveriesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Send a signed test event to this subscription
 */
export const webhooksControllerSendTest = (
    id: string,
 signal?: AbortSignal
) => {


      return request<void>(
      {url: `/api/v1/webhooks/${id}/test`, method: 'POST', signal
    },
      );
    }




export const getWebhooksControllerSendTestMutationKey = () => ['webhooksControllerSendTest'] as const;

export const getWebhooksControllerSendTestMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhooksControllerSendTest>>, TError,WebhooksControllerSendTestMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof webhooksControllerSendTest>>, TError,WebhooksControllerSendTestMutationVariables, TContext> => {

const mutationKey = getWebhooksControllerSendTestMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof webhooksControllerSendTest>>, WebhooksControllerSendTestMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  webhooksControllerSendTest(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WebhooksControllerSendTestMutationResult = NonNullable<Awaited<ReturnType<typeof webhooksControllerSendTest>>>

    export type WebhooksControllerSendTestMutationError = unknown
    export type WebhooksControllerSendTestMutationVariables = {id: string}

    /**
 * @summary Send a signed test event to this subscription
 */
export const useWebhooksControllerSendTest = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhooksControllerSendTest>>, TError,WebhooksControllerSendTestMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof webhooksControllerSendTest>>,
        TError,
        WebhooksControllerSendTestMutationVariables,
        TContext
      > => {
      return useMutation(getWebhooksControllerSendTestMutationOptions(options), queryClient);
    }
