/** Structured diagnostics for HubSpot → OB asset migration (J1). */
export const HUBSPOT_ASSET_MIGRATION_DIAGNOSTIC_CODES = {
  ASSET_DOWNLOAD_FAILED: "HUBSPOT_ASSET_DOWNLOAD_FAILED",
  ASSET_UPLOAD_FAILED: "HUBSPOT_ASSET_UPLOAD_FAILED",
  ASSET_UNSUPPORTED_TYPE: "HUBSPOT_ASSET_UNSUPPORTED_TYPE",
  ASSET_SKIPPED_NON_MEDIA: "HUBSPOT_ASSET_SKIPPED_NON_MEDIA",
  ASSET_REUSED_EXISTING: "HUBSPOT_ASSET_REUSED_EXISTING",
  /** HubSpot module uses picture/srcset/mobile image OB cannot represent on a single Image block yet. */
  ASSET_RESPONSIVE_VARIANT_UNSUPPORTED: "HUBSPOT_ASSET_RESPONSIVE_VARIANT_UNSUPPORTED",
  /** Distinct responsive URL discovered and migrated; layout may still use desktop-only props. */
  ASSET_RESPONSIVE_SOURCE_PRESERVED: "HUBSPOT_ASSET_RESPONSIVE_SOURCE_PRESERVED",
} as const;

export type HubspotAssetMigrationDiagnosticCode =
  (typeof HUBSPOT_ASSET_MIGRATION_DIAGNOSTIC_CODES)[keyof typeof HUBSPOT_ASSET_MIGRATION_DIAGNOSTIC_CODES];
